### ISSUE TITLE
Wrong email template used when resending verification email

### ISSUE THREAD

**Issue by mr-kojo** [yunity/karrot-frontend#1011]
Steps to reproduce:
1. Signup
2. Go to settings -> email
3. Click the link 'Resend verification email'

It will use the `change-email-request` template. 
However, it should use the `signup-request` template instead.

The `change-email-request` template should be used only if the 'Resend verification email' was clicked after _actually_ changing the email address.

**Comment by tiltec** [comment]
Should be tagged `backend` instead of `frontend`, I guess?

**Comment by sharad-vm** [comment]
I'm new to this project and contribution on GitHub. I'd like to take a stab at this if nobody else is working on it.

**Comment by mr-kojo** [comment]
Great!

Please have a look at the [contribution guidelines](https://github.com/yunity/karrot-frontend/blob/master/CONTRIBUTE.md) at first. If you have any general questions, feel free to join the karrot_dev [slack channel](https://slackin.yunity.org/).

**Comment by kirakrishnan** [comment]
Hi mr-kojo, I am newbie to opensource. can I work on this or is it finished.?

**Comment by mr-kojo** [comment]
Hey kirakrishnan,

Welcome to Karrot :-)
No work has been done on this issue yet so feel free to assign it to yourself.

**Comment by sharad-vm** [comment]
Hi @kirakrishnan ,

I did not get a chance to get to this yet. Please feel free to grab it from me.
I'll pick another issue at a later time.

Thanks!

**Comment by pogopaule** [comment]
Opened PR: https://github.com/yunity/karrot-backend/pull/542
