### ISSUE TITLE
Verify email link does not work when user is logged in

### ISSUE THREAD

**Issue by km333** [yunity/karrot-frontend#1012]
Reproduce:
1. Signup with new account
2. Karrot logs me in even though my email not verified (I guess this is intentional)
3. I click the link in the email 
eg. (changed)
https://karrot.world/#/email/verify?code=gz3uhx7oRIVs7j4p28xWxQwSVCooB9fyD4BR12js
4. It takes me to blank page (the bug)
5. I logout from Karrot
6. I click the email link again
7. It gives me the Success email verified page

**Comment by tiltec** [comment]
Hi @km333 thanks for the report!
Could you try again on https://dev.karrot.world? Which browser are you using?

**Comment by kellyhogan** [comment]
Hello, I was not able to reproduce this issue with Google Chrome Version 65.0.3325.181 (Official Build) (64-bit).

1. Signup with new account
2. Karrot logs me in
3. Click on link in verification email
4. Successful email verification
![image](https://user-images.githubusercontent.com/17225886/39410922-c540b2ee-4bcd-11e8-89b0-8700b30ee158.png)

If after step 2:
3. Log out
4. Click on link in verification email
5. Successful email verification
![image](https://user-images.githubusercontent.com/17225886/39410959-78c83c56-4bce-11e8-9ece-2949b512411b.png)

If after step 4:
5. Click on link in verification email again
6. Verification code is invalid
![image](https://user-images.githubusercontent.com/17225886/39410975-a35b0f5c-4bce-11e8-92fe-b928f202e82e.png)

**Comment by tiltec** [comment]
Seems good then! I also couldn't reproduce it, maybe @km333 used an older browser?
I'll close in the meantime, would reopen if someone else can reproduce the bug.
