### ISSUE TITLE
Add option to make pickups mutually exclusive

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#1013]
Feedback from Bilbao:
Mutually exclusive pickups would be appreciated. The exact use case is still unclear but I already inquired.

Original message from Unai:

> It would be great to have the option to set 2 mutually exclusive pick ups, meaning that there’s the chance to do it both for example on Thursday evening and on Friday morning, and the moment somebody signs up for one of them the other option becomes no longer available.

**Comment by djahnie** [comment]
This is the thinking behind the feature request:
 

> It’s because the shop owners are happy if we do the pick up both at night or the next morning. There might be some foodsavers who can make it at night and cannot in the morning and viceversa. And this way we could offer both options.

**Comment by tiltec** [comment]
It seems related to #709

**Comment by tiltec** [comment]
It seems to be _one_ pickup, but the time is not fixed: has a range (10am-6pm) or two options (6pm, 10am)

**Comment by tiltec** [comment]
I'll merge this with #709
