### ISSUE TITLE
Improve KNotice on small screens

### ISSUE THREAD

**Issue by pogopaule** [yunity/karrot-frontend#1018]
The no pickups message hides the navigation bar. The screenshot was taken on an iPhone.
This UI glitch isn't visible on chrome's device simulation.

![img_6202](https://user-images.githubusercontent.com/576949/40205471-6d8ee6f2-5a2c-11e8-9edb-cd0069bc3cc2.PNG)

**Comment by tiltec** [comment]
Thanks! Karrot is not well-tested on Apple devices, so every feedback is helpful. I can't reproduce this in Chrome on Android and Firefox Focus.

Can it be reproduced in Safari on MacOS?

**Comment by pogopaule** [comment]
Yes, that is possible. I'll try to fix it.

![screenshot at may 21 15-36-01](https://user-images.githubusercontent.com/576949/40310332-b1e052fe-5d0c-11e8-94ca-7d775a556d8d.png)

**Comment by pogopaule** [comment]
Intermediate result: There [seems to be a bug](https://css-tricks.com/forums/topic/safari-for-ios-z-index-ordering-bug-while-scrolling-a-page-with-a-fixed-element/) with `translate` in Safari.
It can be fixed by removing the rotation:

![screenshot at may 21 16-08-27](https://user-images.githubusercontent.com/576949/40312048-ffb12ad0-5d11-11e8-8dc0-4f58f71dd93b.png)

**Comment by tiltec** [comment]
Maybe the green card should look different on mobile anyways? It doesn't look very good...
