### ISSUE TITLE
Upcoming pickups from archived stores are visible in group wall and group pickups page

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1026]
From foodsharing Poland

> upcoming pickups from the archivised stores still visible in the pickup section and on the main page. i had to restore those archived stores, delete old pickup dates and then move them again to the archive. it's no big deal, but i think it's worth fixing

They should be filtered out properly.

It would be better to disable pickup generation in backend if the store is not active. I remember that I didn't do it last time because it would make the code more complicated. Seems worth revisiting.

**Comment by oldPadavan** [comment]
Is this issue still valid? I've tried to reproduce this behavior, but didn't succeed. I archived the store and don't see its pickups any more. Wasn't the issue closed by yunity/karrot-backend#483?

**Comment by tiltec** [comment]
This is resolved :)
