### ISSUE TITLE
Screen reader thinks that karrot is always in English

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1029]
From foodsharing Poland:

> ok, this is a long shot but i think it's worth mentioning: one of our most active users is a blind person and she uses some software that reads to her the web content. what is problematic is that the software detects english as the code language and automatically switches to english even when karrot is in polish. i don't understand exactly how it works and i don't know if that can be fixed at all, so i don't expect you to look into that, but maybe you happen to have an idea what is going on :slightly_smiling_face: after all, we want to make karrot accessible to all people. anyway, there is always somebody to sign up for her so it kinda works in some way...

We maybe need to set the [`lang` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang) dynamically, currently my browser shows it as `en-us`. I don't know where it is defined, but overriding like this could be worth a try: https://forum.vuejs.org/t/settings-lang-sv-to-the-html-tag/7047

**Comment by mike-ap** [comment]
Would it make sense to add a global Navigation Guard to @store/plugins/router.js to set the 'lang' meta attribute based on store.i18n.locale? I could give that a shot.

**Comment by tiltec** [comment]
Hey @mike-ap, welcome!
I'd put the `lang` set code in our [vuex store plugin](https://github.com/yunity/karrot-frontend/blob/master/src/store/plugins/i18n.js), as the language changes are unrelated to route transitions.

And we should make sure to check with a screen reader if it really did the trick :)

**Comment by mike-ap** [comment]
Great! I've added this functionality to the i18n store plugin and confirmed that this fixes the issue in the case of macOS VoiceOver.

There is a different voice for each language. Without setting the lang tag, VoiceOver will continue using the voice that matches the **browser's** language. When the tag is set, VoiceOver uses the lang attribute voice. The user was likely hearing the screen reader's English voice executing a (English) phonetic pronunciation of the Polish text.

I extracted this to a function with an eye toward testing, but I'm not sure what would be appropriate. Can you suggest a testing strategy?

**Comment by tiltec** [comment]
Sounds good. From my POV, no testing is needed and you can directly call `document.documentElement.setAttribute('lang', locale)` from the store plugin.

Ping @nicksellen because he has stronger opinions about testing than me ;)

**Comment by mike-ap** [comment]
OK, I've inlined it and pushed in case nicksellen is in agreement.
