### ISSUE TITLE
Group-specific welcome emails

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1038]
Teddy wrote in Slack:

> I send out a seperate welcome mail to the new members with explanations (because i know not everybody reads the describtions). Is there a way to develop a welcom message that every member gets automatically?

Bruno added:

> The welcome message could be basically the same feature as the terms and conditions (but without the "I accept" tickbox) that was discussed earlier? That would also be cool for us

**Comment by tiltec** [comment]
Could need some discussing or coding :)

**Comment by cstefanj** [comment]
Hi @tiltec. I'm wondering, is the idea for this be implemented through a few changes to the application_accepted.mjml email template, allowing for adding a custom welcome message per group there? Or is the idea to have this as a separate email setup, with a new template, a new entry to emails.py and perhaps tasks.py?

**Comment by tiltec** [comment]
Yeah, I think adding it to the application_accepted email would cover most use cases.

There are two more ways how a user can become member: 
- by invitation of another group member
- by joining an open group

But we can care about those later.

**Comment by cstefanj** [comment]
Ok, sounds good. And then I guess the `Group` model needs to have a new attribute `welcome_message` or similar, since the message would be group-specific. I can take a stab at this and see how far I get. :-) Not sure I can do much about the frontend part... But as a thought, would Edit Group be the place for the group admin/editor(s) to edit the message?

**Comment by tiltec** [comment]
Sounds right to me!

**Comment by cstefanj** [comment]
@tiltec Sorry but I have a strange issue. (Doesn't belong here I guess but I'll delete this post after resolving). When I worked on the previous PR I never had problems with the local docker-compose setup, but now I can't get the backend working even after a fair bit of trying:
<img width="948" alt="screenshot 2019-03-04 at 16 05 02" src="https://user-images.githubusercontent.com/1835675/53741931-c3f35a00-3e97-11e9-9cac-c933a3b27562.png">
karrot-docker, karrot-frontend and karrot-backend locally are all up-to-date. Is this something you recognise? If not then I'll just delete this post and keep looking. :-)

**Comment by tiltec** [comment]
@cstefanj Weird, maybe remove the docker-compose setup? Perhaps those commands might help:
```
docker-compose stop
docker-compose rm -v
```

**Comment by cstefanj** [comment]
@tiltec Thanks, that did the trick! Will get to work and try to make myself useful. :-)

As a side note, I still get one test failure when I run the whole suite. I had the same failure last time I worked and it didn't interfere with what I was doing so I should be good to go now as well, but it's a bit odd: ![image](https://user-images.githubusercontent.com/1835675/53757165-3e81a100-3ebb-11e9-8d4f-de759a3f0cef.png)

**Comment by tiltec** [comment]
Thanks for tackling the backend part @cstefanj!
Would you also be interested in frontend development?

**Comment by cstefanj** [comment]
I wish I could help and I did have a look at the frontend code a couple of days ago, thinking I could perhaps figure something out based on the existing description text input field in the Edit Group section. Have to admit I couldn't make much sense of it... Perhaps if you could point me to the relevant lines I could have another look?

**Comment by tiltec** [comment]
Sure! You might be able to duplicate the group description input: https://github.com/yunity/karrot-frontend/blob/84c9ce1908f91de7202ab533cfa6d8c95aa61a53/src/group/components/GroupEdit.vue#L50-L64
Just replace everything that says `description` with `welcomeMessage`. It is converted to `welcome_message` before it gets sent to the backend. Then you can set and edit a welcome message.

**Comment by tiltec** [comment]
@cstefanj how is it going? anything I could help you with?

**Comment by cstefanj** [comment]
@tiltec Hi! Thanks for the nudge, this had given way to other priorities. I've implemented the code change but can't find a way to test it out locally --  none of the test users have admin rights or even validated emails I think?

**Comment by tiltec** [comment]
>  none of the test users have admin rights or even validated emails I think

Indeed, that's not ideal with the sample data.
As a workaround, you can create a new group with `http://127.0.0.1:8080/#/group/create`

**Comment by cstefanj** [comment]
Thanks, that helped. I got it to work now, left you a question [here](https://github.com/cstefanj/karrot-frontend/commit/dc94b4acf232d34dbbb785bc7c62af5f85321b8a).

**Comment by tiltec** [comment]
Closed via #1375

**Comment by tiltec** [comment]
As a next step, we should publish a description of this feature in the forum: https://community.foodsaving.world/

**Comment by cstefanj** [comment]
Cool! Do you want to bundle this into a bigger announcement with other features as well or should I draft a small note just for this?

**Comment by tiltec** [comment]
A note and a screenshot should be good for now :) Let's see what the feedback from the community is!

**Comment by cstefanj** [comment]
Good point with the Markdown rendering. How about something like this for a simple feature text:

"New feature: you can now create a welcome message for your group, which will be included in the welcome email to newly accepted applicants. You can find the new input field under Edit Group, below the description field. Hopefully this will be a useful way to extend a warm welcome (and provide some guidance) to new members!"

![Screen Shot 2019-04-06 at 00 02 02 ](https://user-images.githubusercontent.com/1835675/55658864-861f8380-57ff-11e9-8e84-0326defca298.png)

**Comment by tiltec** [comment]
Thanks! Should we add a screenshot of the resulting email as well? For example:

![Screenshot_2019-04-04_11-51-55](https://user-images.githubusercontent.com/4410802/55729234-0ddedb00-5a16-11e9-8206-6c64b327b46f.png)

I remembered some things that we could/should do:
- send the welcome message if someone accepted an email invitation
- hide/disable the "welcome message" setting in open groups (they don't have applications and will not send the welcome message)

**Comment by cstefanj** [comment]
Yes, good idea. It would be nice to put them side-by-side with the same, nicer, example welcome message in each, as text in the input field and rendered in the email. But perhaps just using these two images is enough. About the two additional points: 

- I can have a look at sending the email if someone accepts an invitation.
- Hiding the edit box for the welcome message would be an `if` condition I guess. Would this addition do the trick: `v-if="!edit.isOpen"`  ?

**Comment by tiltec** [comment]
> Would this addition do the trick: v-if="!edit.isOpen"?

Yes, that should do it. 

> I can have a look at sending the email if someone accepts an invitation.

You might need to add a new email template for those.

**Comment by tiltec** [comment]
I made a post here: https://community.foodsaving.world/t/new-feature-welcome-messages-for-new-users/269

**Comment by cstefanj** [comment]
@tiltec Cool! And thanks for the credit! :-) I hope someone finds it useful. 

I haven't forgotten about the new email template for when someone accepts an invitation, but we just had a baby + tons of work is keeping me from spending as much time on this as I would like. I'll get to it, and might be able to sink my teeth into something new after that. Thanks for all the guidance so far!

**Comment by tiltec** [comment]
@cstefanj I hope your family is well!

So far, 6 active groups on karrot.world have adopted a welcome message (also Foodsharing Warszawa, one of the most active ones). I think it's worth adding the welcome message to invitations, too.

If you don't have much time available, that's also fine, maybe somebody else can pick that up then!

**Comment by cstefanj** [comment]
Hi! Great to hear that the feature is being used! :-)

Time is indeed really scarce but I'd like to be able to complete this. I'll start looking at it. If someone else with more bandwidth wants to implement this then of course that's great too, I guess we just coordinate here in the comments to avoid double work.
