### ISSUE TITLE
Signup flow

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#104]
As @Xbaal mentioned, I removed the password repeat check. I did it out of personal preference. I'm very happy that many modern websites don't use it anymore, and I never had a problem with mistyped passwords. Plus, many browsers save passwords.
But I have more on my mind, that's why I'm creating this issue.

My proposal for a signup form: just enter your mail. Then the user already gets access to the page and can look around. The user also gets a mail to verify his address and clicks on a link, where he can set his password and optional first+last name. (This is inspired by Slack signup)

When we have users, I would introduce some logging how many users mistyped their passwords on the first try and use the password recovery option.
## Further resources:
- Generally I prefer SSO solutions like [OpenID](https://en.wikipedia.org/wiki/OpenID), including facebook and google auth
- https://ux.stackexchange.com/users/signup is a nice example of preferring SSO providers, but also allowing a 1-step signup with 3 input fields
- People argue [here](https://ux.stackexchange.com/questions/20953/why-should-we-ask-the-password-twice-during-registration) if optional unmasking of the password increases UX

**Comment by D0nPiano** [comment]
Sounds good! I like the idea of splitting it in two. - does this mean we will mostly use the display name then? (e.g. for the members of a pickup in a pickupList)?

**Comment by tiltec** [comment]
Yes, I would prefer only to use the display name for now.

The first name and last name option are for later use, e.g. to verify the identity of user with their passport (like in Germany). It's actually a leftover from our previous development goals (replacing foodsharing.de) and I wasn't strict enough to completely remove it. What do you think?
