### ISSUE TITLE
using github is indirectly supporting fascism

### ISSUE THREAD

**Issue by PaulFree14** [yunity/karrot-frontend#1043]
As many of you propably know, github got bought by microsoft.
Yet there is many to say about microsoft, but I believe it's important to have current events in mind, and how the struggle for free software can be linked with those of others.

That's how resisting becomes more powerfull, when the opressed give visability to each others struggle and take action of solidary.

Microsoft is currently supporting ICE.
Take on that matter also a look at this:
https://boingboing.net/2018/06/20/godwins-law-suspended.html
(myself haven't really made any research on that sybject)

This is a call for directAction in solidarity with anyone being effected by the fascist activities conducted by the US agency ICE.

Since being here on github, we can start to use this proprietary plattform instead of sharing code, colaborating on code and being constructive about coding to use it to exclusivly share informations about microsoft supporting fascism, what it has to do with ones own use of this plattform and deconstructing fascist ideology.

Also start writing issues about this into any other software projects you empathise with
and encourage people to do the same.

Thought their is potential of making a trend out of this, that could damage the trademark github and microsoft and raises more awareness about ICE within the coder scene.

Maybe someone could come up with a much better writing then this one, incl. some more research and possibilities that can be taken to resist ICE in specific or racism in general.

**Comment by nicksellen** [comment]
Thanks for your thoughts :)

**Comment by spaceywolfi** [comment]
@PaulFree14 looks like there are already people taking action...
https://github.com/selfagency/microsoft-drop-ice

i'm personally not so worried about github become a "fascist" and "evil" organization. Microsoft changed the CEO and he actually seems pretty cool, he is a strong supporter of open source and was actually part of the linux community for some time. The structure of github is not going to change much for now and Microsft is planning to leave it be an independant project, just like they did with Mojang (the organization behind Minecraft).

**Comment by PaulFree14** [comment]
@spaceywolfi
thx for the link. 

do you mean Satya Nadella?
When reading their respond to employees that signed a petition so that microsoft steps out from working with ICE, it was in a nutshell: We don't do anything wrong, because we don't work directly with child detention. We provide software and hosting service for ICE. This is ethical correct and inline with our values. 

...aka we only served them the punshed cards

**Comment by nicksellen** [comment]
@PaulFree14 / @spaceywolfi - as neither of you are contributors or users of the karrot software, and this is a closed issue, I think you can find a better place for your discussion. Mastodon seems the best place, given you have both already been discussing it there.

**Comment by PaulFree14** [comment]
I contribute issues. :-p

**Comment by spaceywolfi** [comment]
paul has a point, if it were in our interest we could participate in this direct action that i have linked above, but since majority of people here are not interested in this direct action we might as well close this discussion here
