### ISSUE TITLE
[Brainstorming] User trust/permission levels

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1062]
This issue discusses the high-level topic of different user levels and their permission handling.

Inspired by
- the [Discourse user trust levels](https://blog.discourse.org/2018/06/understanding-discourse-trust-levels/)
- the self-regulated hierarchy proposal #878
- the request for a student mode for newcomers #546
- the necessity for a group approval process #894

I talked to @nicksellen today and we came to the conclusion that this needs a good concept before we should start implementing.

**We could conceptualize the relation between a user and a group in 4 user levels (UL):**

- UL0: no relation
- UL1: user wants to become a member of the group
- UL2: user is a newcomer in the group (aka *student mode*)
- UL3: user is a full member

(There's also the role of site admins as there are people with server/database access. This should also be taken into account, as they have quite much power.)

**The main features of each user level are:**

- UL0: can see public group information
- UL1: can communicate with the group in a yet-to-be-defined chat interface, the group approval chat
- UL2: can join pickups and read all group information
- UL3: same as currently implemented membership status

**How does a user transition between the trust levels?**

Basic principle: *the only way is up*, except
- if a user removal process was successful (for which the details need to be defined yet in #853)
- UL1 user is declined access to the group (or timed out)

Transitions:
- UL0 -> UL1: user clicks button "I want to join this group"
- UL1 -> UL2: some group members give their approval, additionally: some days passed without anyone objecting, or voting process
- UL2 -> UL3: some more members give their approval, additionally: some weeks passed without anyone objecting, or voting process

There's the option of having a simple *approval* system where a number of members need to click a button. The required approvals could potentially increase with the number of active group members. This is particularly related to the proposal of a user trust system #878.

There might be the problem that people can't join a group because nobody in the group feels responsible for giving approval. We have to implement a proper notification system so that active users are being notified of the pending request. Optionally, we could add that requests are automatically accepted after some days, except if there's an objection. This requires the new concept of *objections*.

If we take the requirement of approvals and objections as given, and take the ideas for member removal into account (#853), then we could implement a general-purpose lightweight voting system for these purposes.

**What are the technical difficulties?**

As the current implementation only has UL0 and UL3, **permission handling** is a major task. The backend needs to have a proper infrastructure to determine permissions and filter objects based on user level. It must tell the frontend about permissions, ideally in a fine-grained way (`can_edit_store`, `can_add_store`).
We already have the `GroupMembership.roles` field that could be used for some purposes, but we probably shouldn't store the information about UL1 in the `GroupMembership` table, as this is a pre-membership status. The existing PR https://github.com/yunity/karrot-backend/pull/519 could be reused for UL2

For the group approval chat of UL1, we need a **chat with group members**, without being part of the group. While the `Conversations` model supports this, user profiles are not available to non-members. We need to add the concept of a site-wide user profile that is visible to logged-in users.

The **voting system** is a completely new feature, which needs to fit into the context of group members, group approval chat and role changes.

The **invitation feature** should be reworked, as it would allow to bypass UL1 and hijack the membership removal process #853 - could be done later, too.

**Comment by brnsolikyl** [comment]
I like the proposal! Some questions: does passing from UL1 to UL2 require the approval of more than one member? And would the invitation feature bring the invited user directly to UL2? I think some groups would appreciate having a more straightforward process of joining the group and beginning doing pickups, and that would require the approval or invitation of only one member, whereas others would appreciate a higher threshold for joining (say the approval of at least two members). How much work and complexity would it add to make this feature something you could customize at the moment of creating a group? Or is this a one-size-fits-all solution?

**Comment by tiltec** [comment]
@brnsolikyl 
The first implementation will require only one member to accept or decline the application. It would be good to support other cases as well in future and ideally make it flexible, but I would like to test this feature for a few months in production before extending it.

My feeling is that student mode (UL2->UL3) should be implemented before that (so it's actually not super critical if someone becomes member of the group, because they can't do all the things).

Invitations will bring an user directly to UL2.
