### ISSUE TITLE
Re-organize frontend into modules

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#1066]
We are gathering quite a lot of frontend files now, store modules, components, etc, and it might be a good approach to re-organize them into modules that contain all related things for a given area of the page, e.g. conversation routes, store modules, API methods, and components would all live inside a `conversations/` module directory.

It would be nice to have increased test coverage if possible to make sure everything doesn't break.

This would also harmonize the structure with the approach used in the backend.

**Comment by nicksellen** [comment]
Could take some inspiration for component structures from http://atomicdesign.bradfrost.com/chapter-2/

**Comment by tiltec** [comment]
I moved this into the "Current Development" milestone to have it as part of the _Refactoring winter_ ;)

**Comment by tiltec** [comment]
I came up with module structure similar to our backend:

```
pickups/
  - routes.js                 # routes for this app
  - assets/                   # mostly images
    - apple.png
  - api/                      # backend communications
    - pickup.js
    - pickup.spec.js
    - ...
  - db/                       # vuex namespaced modules and plugins
    - pickup.js
    - pickup.spec.js
    - ...
  - components/               # reusable components (atoms, molecules, organism)
    - PickupUser.vue
    - PickupUser.spec.js
    - PickupSlot.vue
    - PickupList.vue
    - PickupEdit.vue
    - ...
    - Pickups.story.js        # storybook story
  - pages/                    # page templates and instances
    - PickupsManage.vue       # page connected via mapGetters etc
    - PickupsManageUI.vue     # or via vuex-connect
    - PickupsManage.spec.js   # ...then can also have a test
    - ...
```

These modules would reside directly in the `src/` folder. There would be some other folders that don't follow the module structure, like `base`, `utils`, `statics`, `cordova`.

I would first try to move files around without changing file content too much.
