### ISSUE TITLE
Fonts are not served from correct path on cordova android app

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#1076]
As a result of https://github.com/yunity/karrot-frontend/pull/1075 the font asset path is not correct when running on the cordova android app.

I checked _5_ different environments whether it worked, but not the 6th :/

**Comment by tiltec** [comment]
Images from `/assets/images/` are also not served in cordova, apparently cordova doesn't resolve the absolute path correctly. I assume cordova root is something with `file:///android_asset/`.

There's a global variable available: `cordova.file.applicationDirectory`, which should contain the root directory: https://github.com/apache/cordova-plugin-file/#android-file-system-layout

So I guess we need to conditionally prefix image and font URLs in webpack.
