### ISSUE TITLE
Replying to wall messages via email should open a replies thread

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1079]
Currently when someone writes on the group wall and another user replies via email, it will create another wall message. As we have the replies feature now, it would be better to stick the reply into a replies thread.

Steps:
- Disable email batching for wall messages, so that we can clearly find out which message the user replied to
- Insert message id as thread_id
- ???

**Comment by brnsolikyl** [comment]
I see there's a closed issue here, but this problem still appears to be happening. I see many actual replies to a wall message that are sent by e-mail and end up on the wall instead of a thread. Could it possibly be something that the user is doing? Or is still failing?

**Comment by tiltec** [comment]
It used to work, but maybe it got broken? @nicksellen I remember you refactored this area recently, could it be....?

**Comment by nicksellen** [comment]
It wasn't me boss!

... but potentially could be. Maybe our tests are not covering this very well?

**Comment by tiltec** [comment]
I think there's no test coverage for this.

Indeed, `make_local_part(conversation, user)` should be `make_local_part(conversation, user, thread)` if it's a group or wall conversation.

**Comment by nicksellen** [comment]
Ah, so I did break it probably by overlooking that. You want to fix? With a test? If not I would add it in my queue.

**Comment by tiltec** [comment]
Depends on your queue length ;) I'm a bit unconcentrated but could have a look!

**Comment by nicksellen** [comment]
Maybe have a look then, skip the test if needed... seems useful to get the fix in.

**Comment by tiltec** [comment]
I went for the more explicit variant, defining and checking `conversation_supports_threads` property on the conversation target - should be harder to miss out in future.

https://github.com/yunity/karrot-backend/commit/cd750d46501870dc2848aa941afe40e723d4a287
