### ISSUE TITLE
Weekly summary emails say Saturday to Saturday

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#1083]
e.g. `Saturday, August 11, 2018 to Saturday, August 18, 2018`

It should show Sunday to Saturday, otherwise it seems like each Saturday will be counted twice (i.e. 11th August will be included in this weeks one and the previous weeks one). I think the counting is fine, just the date printing is wrong.

A bonus point would be to also change the sending time to be timezone specific (at the moment it just sends them at a fixed time in UTC).

**Comment by the-bionic** [comment]
Hello, I am willing to pick this up.

**Comment by sapanpatel123** [comment]
Hi! Does this still need to be done? I can if @the-bionic can not get to it.

**Comment by tiltec** [comment]
It's still open :)

**Comment by wes977** [comment]
If this is still available I'll pick it up!

**Comment by tiltec** [comment]
Please do! Would be interesting to us if you had any problems setting up the backend and how quickly you could find the responsible code!

**Comment by lwm** [comment]
I'll pick this one up then next time if no one is already working on it. I'll extend the good work of https://github.com/yunity/karrot-backend/pull/588 based on feedback in https://github.com/yunity/karrot-backend/pull/588#issuecomment-443783631.
