### ISSUE TITLE
Emoji in emails are huge

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#1087]
This was a notification mail for a wall post.

Not that I wouldn't like it, but I somehow guess this is not the intended look...^^

![image](https://user-images.githubusercontent.com/17573771/44350967-f9f36280-a4a0-11e8-8fac-30cad29203fe.png)

**Comment by tiltec** [comment]
Hm, I fixed that already a while ago in https://github.com/yunity/karrot-backend/blob/0884b2ceebcd809b5c2708e8f0ac233ae3eefca4/foodsaving/base/templates/_base-head.mjml#L58

Maybe the used CSS isn't supported by your e-mail client? You could forward the email to me and I'll compare.
We could also try switch to switch to other styling options, for example inline CSS could be more supported?

**Comment by tiltec** [comment]
Looks wrong for me too, in K9 Mail and Google mail... needs further investigation.
