### ISSUE TITLE
Group messages from same author

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1093]
Messages from the same author could be grouped if they have been sent within the same hour or so. This would improve readability and save some screen space.

**How it is right now:**
![image](https://user-images.githubusercontent.com/4410802/44925105-aa891e00-ad4d-11e8-9e3f-10ac796777c5.png)

**How it could be:**
![image](https://user-images.githubusercontent.com/4410802/44925204-0c498800-ad4e-11e8-8f1a-35938eb783e6.png)

**Comment by honsq90** [comment]
hello! I'm happy to give this a go if that's alright?

**Comment by djahnie** [comment]
Sure @honsq90 go for it! :simple_smile:

**Comment by tiltec** [comment]
Hi @honsq90, how are you doing? Did you make progress on this? Would be great to have it.

If you don't reply in the next week, we'll assume that this task is up for grabs again.

**Comment by MacNGz** [comment]
Hi! If no one is working on this, could I pick up this issue?

**Comment by tiltec** [comment]
Hi @MacNGz, yes please! :smile:
Did you work with VueJS already?

**Comment by MacNGz** [comment]
@tiltec I've used it a little bit, but I have experience with React and self-teaching shouldn't be a problem!

**Comment by tiltec** [comment]
Would you like to have a short introduction into the relevant code parts?

**Comment by MacNGz** [comment]
@tiltec Sure, that would be helpful

**Comment by tiltec** [comment]
Ok! 

The logic for conversations and messages is in [src/messages/datastore/conversations.js](https://github.com/yunity/karrot-frontend/blob/cda1b2dee0c62fc2127855e49263c706cf8a5f13/src/messages/datastore/conversations.js). This is a [vuex](https://vuex.vuejs.org) module, you could read up on getters, mutations and actions if that sounds foreign to you.

We keep data in `state` as they come from the backend, and process the data in `getters`. For example, the message list gets added to a conversation in the `get` getter.

You might put the message grouping logic in a `getter` as well.

Messages are rendered in [src/messages/components/ChatConversation.vue](https://github.com/yunity/karrot-frontend/blob/cda1b2dee0c62fc2127855e49263c706cf8a5f13/src/messages/components/ChatConversation.vue#L13-L20). You might modify the `ConversationMessage` component to support the minimal view for grouped messages.

---

There is also another way how messages get rendered, in [`WallConversation`](https://github.com/yunity/karrot-frontend/blob/0ffb0a202f162624a7445d47c9ca22b097af638f/src/messages/components/WallConversation.vue).
- ChatConversation powers the sidebar chats
- WallConversation powers the group and place wall

I think it would be sufficient if ChatConversation supports grouped messages.

---

It might be helpful to use [Storybook](https://storybook.js.org/) for UI development, it helps you to work with the UI independently from the data logic. Use `yarn storybook` to run it and have a look at the `ChatConversation.story.js` file to customize your mock data.

**Comment by tiltec** [comment]
Hi @MacNGz, how far did you come with this already?

**Comment by teemukaaria** [comment]
Hi @tiltec , @MacNGz 

What's the status of this issue? If this hasn't yet been implemented, I would love to give it a go.

**Comment by MacNGz** [comment]
@teemukaaria @tiltec
Unfortunately I didn’t have the chance to get very far into this issue. Feel free to grab it!
