### ISSUE TITLE
Follow-up tasks: trust system and user levels

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1095]
There are some useful things that weren't resolved in https://github.com/yunity/karrot-backend/pull/570 and https://github.com/yunity/karrot-frontend/pull/1077:

- [ ] to make trust more valuable, limit amount of trust per week; should keep the user updated about how much of their quota they used
- [x] add exception for playground group: users should be editor when they join to show them all features -> #1140 
- [ ] add prompt to give trust after doing 2+ pickups together; currently there's only the list of people you did the pickup together with. It shouldn't be too obtrusive, to avoid pressuring people into giving trust
- [x] add frontend notification when user became editor; currently there's only an email and a history entry -> needs some kind of notification system ("bell")
- [ ] show date when trust was given
- [ ] ~maybe allow users to decline themselves becoming editor~ seems not needed
- [ ] Specify some criteria if the feature solves the problems successfully or whether we should consider to remove it again after some time -> write a forum post in summer 2019 if the feature solved the problem or if it caused new problems

**Comment by tiltec** [comment]
I started working on a on-site notification system ("bell"). It deserves some more discussion, especially how it's related to the history module and other notifications (e-mail, push)

**Comment by tiltec** [comment]
There's also open questions about
- expiring trust
- untrust
- anti-trust

Read more about it in this thread: https://community.foodsaving.world/t/discussion-karrot-trust-system-and-user-levels/95

**Comment by tiltec** [comment]
If the trust count should be used for further purposes, either informally by the users or by the Karrot software itself, we need to make sure that we have enough indication if the trust is reliable or not.

For example, the trust bananas in foodsharing are sometimes not helpful, as they only show the positive aspects. If there are problems with users, the trust feature is currently not helpful to indicate this.

**Comment by djahnie** [comment]
This is a meta issue from which PRs can be directly derived. We're happy about contributions! :)

Me personally I'm interested in adding a thing that prompts users to give trust and in displaying the date when trust was given. @tiltec had the idea to simply make this into two categories like 'recent' and 'old' and I find that pretty useful already. Might be tackled soonish.

**Comment by tiltec** [comment]
As mentioned in https://github.com/yunity/karrot-frontend/issues/1344#issuecomment-475213901, it was requested to

- increase the trust threshold before users get editing permissions
- let groups set the trust threshold individually
- have a time threshold before users can become editors (in addition to the trust threshold - both requirements must be met)
