### ISSUE TITLE
Email reply text is not always extracted successfully

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#1096]
We use https://github.com/mailgun/talon library to separate the content from the rest when you reply by email to a post/comment.

It has two modes and says:

> Quick and works like a charm 90% of the time. For other 10% you can use the power of machine learning algorithms

We currently just use the quick method.

It seems it fails more when the language is not English, so we could implement the machine learning part of it to improve on that. It's a lot more involved though, but could be fun! (and maybe get to even learn something about machine learning on the way).

**Comment by tiltec** [comment]
I think the machine learning code is only available for signature extraction - that's the conclusion I came to when looking at the talon source code a week ago.
The quotation extraction is always done via regular expressions, with special cases for some languages. I think we could simply add some more of theses special cases for languages that we have in karrot, i.e. Swedish.

**Comment by tiltec** [comment]
Ah, the regular expressions seem to support some Swedish already: https://github.com/mailgun/talon/blob/a7404afbcb67e66aa13ff8917df4dcbbf3534624/talon/quotations.py#L44

But still, the extraction in the Solikyl group is not reliable...

**Comment by tiltec** [comment]
There's also the option to try out other libraries, like this python one: https://github.com/zapier/email-reply-parser

(from https://stackoverflow.com/questions/7978987/get-the-actual-email-message-that-the-person-just-wrote-excluding-any-quoted-te)

**Comment by tiltec** [comment]
Discourse seems to have comprehensive support for handling incoming emails. [This](https://github.com/discourse/discourse/blob/v2.2.0.beta3/lib/email/receiver.rb) is their receiver code and they maintain [their own reply parser](https://github.com/discourse/email_reply_trimmer) that handles multiples languages.

As a first step, I added a table to the database where we store incoming emails. Previously they have been discarded after the conversation message has been created. After we gathered some emails, we can compare different parsing libraries or extend existing ones.

I looked a bit more into https://github.com/zapier/email-reply-parser, but they seem to support English only: https://github.com/zapier/email-reply-parser/blob/master/email_reply_parser/__init__.py#L42

**Comment by nicksellen** [comment]
That line you linked looked like it was just referring to headers in the meta data which would be English from the protocol.

This stuff seems to be at the boundaries of human knowledge!

**Comment by tiltec** [comment]
Ah right! But I didn't find any other languages in their project and the test cases are all in English too. I'm happy to try it out for recorded emails though :)

Talon seems the best solution for python. Or we set up a ruby microservice for email trimming :D

**Comment by tiltec** [comment]
Another option is to implement our own machine learning thing for parsing email replies. Could be a fun but challenging task :)

**Comment by tiltec** [comment]
Would be cool to solve this problem! First needs figuring out the option to go forward with (e.g. docker image with discourse email trimmer and HTTP api, or enhancing `talon`...).
