### ISSUE TITLE
Application metadata is mostly hidden on mobile

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1104]
This is how it looks on mobile:
![image](https://user-images.githubusercontent.com/4410802/46609725-17d85d80-cb09-11e8-88c6-a97016244951.png)

There's some more data visible on wider screens:
![image](https://user-images.githubusercontent.com/4410802/46609668-faa38f00-cb08-11e8-8f64-e10de1cb06b3.png)

Some ideas for improvement, mostly borrowed from the member list:
- do not hide overflow, instead have multiple lines
- make profile picture smaller on mobile
- remove chat button for accepted applications, a click on the whole item already leads to the chat
- for enhanced readability, have 100% text opacity

**Comment by djahnie** [comment]
Since I was the one making it in the first place I'd like to fix it as well! Let's just hope we'll find some space I can work in in the coming days... :sweat_smile:
