### ISSUE TITLE
Action buttons in member list are visible in sidebar

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1105]
Open any members page on mobile:
![image](https://user-images.githubusercontent.com/4410802/46610039-ddbb8b80-cb09-11e8-844a-9dc89dbea5b0.png)

Then open the sidebar ("burger" menu"):
![image](https://user-images.githubusercontent.com/4410802/46610063-e9a74d80-cb09-11e8-8424-34590c4722c1.png)

The action buttons should be hidden. They probably have a z-index attribute set.

**Comment by libertyjayne** [comment]
Hello! I'm hoping to help with this, but I'm not clear on what buttons are the action buttons that need to be hidden. Do you mean the entire sidebar needs to be hidden on mobile because I noticed that seems to be an issue? Thank you!

**Comment by tiltec** [comment]
In the case above, there are two big green buttons on the members page (first picture) that are on the second picture too. They shouldn't be visible in the second picture.

Did you notice other problems with the sidebar on mobile? I noticed https://github.com/yunity/karrot-frontend/issues/1109 recently, but other than that there are no known problems.

**Comment by libertyjayne** [comment]
I will check out today and 1109 while I’m at it. I don’t think I saw the
green buttons on the sidebar like the picture, so maybe the issue has been
resolved. Will report back. Thanks!

**Comment by libertyjayne** [comment]
I'm not seeing those green buttons in front on the settings button like the issue picture shows, so maybe it's been resolved? I've attached a screenshot. The other issue I was referring to is it seems like there should be a way to minimize the sidebar on mobile. The sidebar takes up the whole view and I can't figure out how to change that as a user. 
![github](https://user-images.githubusercontent.com/13758220/47527354-2fc51680-d857-11e8-8b0b-c84835ab84a1.jpg)

**Comment by tiltec** [comment]
@libertyjayne how is it going?

I merged a major refactoring Pull Request into master today, so make sure to get the latest changes before your branch diverges too much :)

**Comment by tiltec** [comment]
I had a look today at a similar code part (group description) and it seemed better to make them more similar. I replace the absolutely positioned action buttons with floating ones, which also fixes the z-index problem.
