### ISSUE TITLE
Messages should be marked as read when joining a conversation

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1106]
When joining a conversation, all previous messages are shown as unread. While this is true, we usually don't expect the user to catch up on all previous messages. From my perspective, it would be better to mark all messages read when joining a conversation.

**Comment by lwm** [comment]
Righto, I'll take a stab at this at some point.

**Comment by lwm** [comment]
Question time!

> When joining a conversation, all previous messages are shown as unread.

Are we referring to the Wall conversations (saw other chatting in other places, so not exactly clear to me).

> From my perspective, it would be better to mark all messages read when joining a conversation.

Does 'joining the conversation' here mean that the user is entering some comment in the thread?

**Comment by lwm** [comment]
OK, I've got https://github.com/yunity/karrot-backend/pull/594 for this :+1:
