### ISSUE TITLE
On wall, replies button is not visible if the message is taller than screen

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1107]
The message toolbar with the replies button is shown when hovering over a message. It's aligned with the start of the messages:

![image](https://user-images.githubusercontent.com/4410802/46610392-ef516300-cb0a-11e8-8051-520dda45d48c.png)

If the messages is long and the user is scrolled to the bottom - the typical use case for using the replies feature - the start of the message is usually off the screen and the replies button too.

We could solve this either 
- by moving the message toolbar to the bottom of the message or
- by showing the message toolbar either at the top of the message or on the top of the scroll view, depending on what is lower

**Comment by djahnie** [comment]
I prefer option 2. Having the message toolbar on the bottom would be quite unexpected for me.

**Comment by tiltec** [comment]
Seems not a huge problem, so closing this again.
