### ISSUE TITLE
How do users join the page & groups?

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#111]
How do people get to know about the foodsaving tool, how do they join, what happens afterwards?
### My view:

There's a facebook group "foodsharing Lummerland" (_fb-group_) with 100 active members, who pick up food at the supermarkets on Lummerland. One of them gets approached by a member of the yunity FSINT team, who tells about the amazing foodsaving tool.
Goes on `foodsaving.org` (in future), joins, creates a group here "Lummerland" (_fs-group_), gets a secret invite link and posts it into the facebook group. All the other 99 members click on the invite link, can login with "facebook Connect" (or use on of the other signup possibilities -> #104) and get automatically added to _fs-group_. Which makes them see all the open pickups at their supermarkets.

If other people join the fstool without the invite link, they can still apply for _fs-group_ "Lummerland", but then a member of the group needs to approve.

Later on, we could also have an option to send out invites via mail, but this is low priority and quite complicated to me.

**Comment by D0nPiano** [comment]
I think having a group member approve others make sense. So I'm completely for your proposal - with the only exception that i wouldn't integrate facebook Connect. I think I'd say you have to signup.

**Comment by djahnie** [comment]
Yep, approval is a good solution. Also the automatic adding to the relevant group. But where is the benefit of facebook connect other than a bit more convenience for the normal facebook user..?

(Also, really liked the nicely written Lummerland story! ;) )

**Comment by tiltec** [comment]
The upsides of using a separate (trusted) identity provider are from my POV:

- no need to verify mail address on our own
- one less password for the user to remember
- pre-fill user name fields, less typing

Facebook connect is just an example, this also goes for other providers like Google, GitHub, Slack etc.
