### ISSUE TITLE
User profiles are sometimes unexpectedly empty

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1117]
I identified one case where the user profile shows no information except for the user name.

![image](https://user-images.githubusercontent.com/4410802/47264886-4c8fe000-d51f-11e8-8f46-152cf2e6fdd8.png)

It happens when the user applied to one of your groups and is not member in any of your groups. This is the default case when somebody joins Karrot and applies for a group.

We deliver user profile data mainly via `/api/users/:id/` and `/api/users/:id/profile/` for users in your groups. For the case of applications, that's not enough - the applicant needs to see names in the application chat and the group members want to see the applicants' profile.
We have `/api/users-info/:id/`, which contains only user names. We have `/api/group-applications/:application-id/` which contains the full profile.

When opening a user profile, the frontend first tries `/api/users/:id/profile/` and if no user is found, it tries `/api/users-info/:id/`.

The users and users-info endpoint are currently symmetric, i.e. if somebody can see your information, you can also see theirs. We could make the users endpoint non-symmetric, returning profiles to group members, but not to applicant - otherwise the applicant could see all details of group members.

**Comment by gagandeepp** [comment]
I want to look into this

**Comment by gagandeepp** [comment]
What should be desired output?

**Comment by tiltec** [comment]
It's not clear to me yet, it probably needs to be figured out while working on it. 

Maybe the first step would be to describe the problem in your own words. This way I can support you best, by providing the necessary information.

**Comment by lwm** [comment]
Hi @gagandeepp, I will pick this up next if you're not still working on it.
