### ISSUE TITLE
Generalize stores and pickups

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#1127]
To implement public locations for food distribution we seemed to go with the feeling to generalize stores and pickups to be places and events. It's a bit wider than the existing issues so I'll create it's own one here.

Renaming things is quite fiddly and have to be careful, I think as a first goal I would try and make them generalized but not add any new types, so the site will carry on working as it does now.

The translations are a bit fiddly, there are ~25 strings in the frontend with the matching `/store/i`, and 3 or 4 in the backend. It might be possible to keep the frontend one as they are, but maybe reasonable to just move forward and people will have to translate new words.

Related:
* Public locations for food distribution (Food-share points, open fridges) https://github.com/yunity/karrot-frontend/issues/354
* Generalization of store pickups for other tasks https://github.com/yunity/karrot-frontend/issues/359

**Comment by nicksellen** [comment]
I like the idea, and it keeps a focus on using karrot for things you _actually do_, but it doesn't to quite sound right when it's being used for a meeting, or a public gathering, but neither are perfect for all the things. It might be that as karrot is more for internal group co-ordination stuff that the task is a much better focus than general events. Naming is _hard_. 

To me, _event_ can be more general sounding, depending on the definition used, from https://www.merriam-webster.com/dictionary/event - _a_ is very general, whereas _b-d_ are more specific.

a : something that happens : occurrence
b : a noteworthy happening
c : a social occasion or activity
d : an adverse or damaging medical occurrence a heart attack or other cardiac event 

I googled "event or task" and _activity_ was another word mentioned, maybe that works well? (but that also gets a bit confused with a list of recent activities on the site e.g. user signed up, etc... we were going to rename history to activity before #427).

... also to bear in mind, the user might only ever see this word in the url.

**Comment by brnsolikyl** [comment]
> To me, event can be more general sounding, depending on the definition used

I trust you there, since you're native speaker :)

> activity was another word mentioned, maybe that works well?

I like activity. And personally I'd rather not change History (what's the status of it btw?) if we are to choose this name.

Figuring out the right words is something that can be asked from users or tried out in usability tests, so I'll include this to my list! 

> ... also to bear in mind, the user might only ever see this word in the url.

Do you mean because of the different languages? Or because stores will be kept for foodsaving groups?

**Comment by tiltec** [comment]
I did some thinking about generalization the places/events API. The idea is to not have different schemas in one endpoint, avoiding complex validation logic with _sometimes optional_ fields (e.g. "this field is optional, but only if you specify another one")

We will have with 4 main endpoints:
- /api/places
- /api/events
- /api/event-series
- /api/feedback

I explored places and events, not so much series and feedback yet.

## Generic places API
```
GET /api/places/
    cooperations: []
    meeting_places: []

GET/POST /api/places/<type>/
GET/PATCH/DELETE /api/places/<type>/<id>/
    type: <type>
    name
    description
    latitude
    longitude
    address
    cooperation
        status
        is_subscribed
    meeting_place
        is_public
        opening_hours

GET/POST /api/places/cooperations/<id>/<exclusive-endpoint>/
```

### Example with stores, calling them "cooperations":
```
GET/POST /api/places/cooperations/
GET/PATCH /api/places/cooperations/<id>/
    type: "cooperation"
    name
    description
    latitude
    longitude
    address
    cooperation
        status
        is_subscribed

GET /api/places/cooperations/<id>/statistics/
```

## Generic events API
```
GET /api/events/
    pickups: []
    meetings: []

GET/POST /api/events/<type>/
GET/PATCH/DELETE /api/events/<type>/<id>/
    place: <place_id>
    description
    date
```

### Example with pickups:
```
GET/POST /api/events/pickups/
GET/PATCH /api/events/pickups/<id>/
POST /api/events/pickups/<id>/{join,leave}/
```

## Series and Feedback API

They probably also have different schema per type:
- series needs to know about event fields, a series contains the template for new events
- feedback might have "comment", "weight", "count", "rating", depending on the event type

## Comments
- What if <id> exists but doesn't have the right type? -> return "not found"
- can have custom endpoints and custom methods per type (e.g. store statistics endpoint, do not allow `DELETE` for stores)
- frontend can keep entries from different types in separate lists
- can reuse some serializer code (backend) and converting/enriching code (frontend), although I expect some duplication

## Unrelated to API
- should the event type be tied to a place type? (e.g. meetings can only be created for a meeting place, but not for a cooperation)
- type and extension fields should be decoupled, to allow free combination of "extension models" (OneToOne references) when implementing new types

**Comment by nicksellen** [comment]
Great, thanks for progressing this :+1: 

Me and @brnsolikyl had a bit of a chat about some of the topics around this.

My feeling would be to explore lots of the domain specific types/use cases, but then implement it one level more generic than that - e.g. conceive that there might be such a thing as a community fridge cleaning event, but to implement the event type "task" - that could be applicable to any type of place, and to lean on people using description fields for more info.

The purpose of that thinking is to not constrain the groups organisational abilities to the limit of our imaginations.

So, also to maybe generally lean on the side of making things available on the generic type (e.g. `is_subscribed` could be something that works on any place (as it's basically a favouriting mechanism - or maybe it's even the more generic sounding "star" action, like on GitHub).

It seems that there could be a whole bunch of place/event types that do not have any extension modules, so the main use of the specific types is to distinguish them in the UI for the users (seperate section/labels). That potential goes in the direction to _not_ have type in the URL (as there it could be many) - but see a point later in favour of the types in the URL.

Another thought would be about a _subtype_ - e.g. cooperations -> bakery. But that could go into an extension module field.

> feedback might have "comment", "weight", "count", "rating", depending on the event type

I think it would be reasonable to make feedback specific, e.g. PickupFeedback. Rather than trying to make everything with some commonality be implemented via a generic/base type.

> can have custom endpoints and custom methods per type (e.g. store statistics endpoint, do not allow DELETE for stores)

I was wondering quite a bit whether having the type in URL is good or bad (as given a place/event id, you cannot know the URL directly, which can be a bit annoying sometimes), but I can also imagine the case where the type benefits from a custom endpoint.

>should the event type be tied to a place type? (e.g. meetings can only be created for a meeting place, but not for a cooperation)

I would tend towards no, on the basis of leaning towards the generic rather than specific allows groups to use our feature primitives for their specifics. Why not have a meeting at a public fridge! (it might have a nice bench next to it, and be situated in one of these nice warm places where you can comfortably sit outside in the evening). Why not pickup from meeting? (maybe it's a meeting with food and needs someone to collect it).

> type and extension fields should be decoupled, to allow free combination of "extension models" (OneToOne references) when implementing new types

I like the idea, although also wonder if it makes it somewhat complicated - two concepts of "type" instead of one (type vs type and extension modules).

**Comment by tiltec** [comment]
Thanks for the quick response!

I like the motto of "one level more generic" - maybe it costs a bit of clarity when somebody starts a brand new group, but all others should be able to derive the meaning from user-provided descriptions. Maybe events should have a title, not just a description? 

> It seems that there could be a whole bunch of place/event types that do not have any extension modules, so the main use of the specific types is to distinguish them in the UI for the users (seperate section/labels). That potential goes in the direction to not have type in the URL (as there it could be many) - but see a point later in favour of the types in the URL.

I think there are some place types that are very similar to each other, maybe they have almost the same data schema and same functionality, but groups want to have them in separate categories (e.g. dropoff points and public fridges). 
I wonder if having seperate endpoints for them is ok in terms of duplication, as we could always write generators/factories.

Listing them should probably always be done via generic API (GET `/api/places/?group=<group_id>`) to keep the number of database requests low.

> ...as given a place/event id, you cannot know the URL directly, which can be a bit annoying sometimes 

We might have a way to get one object, not knowing its type, e.g. via `GET /api/places/?id=<id>`. It seems a bit clunky, but still practical.

**Comment by tiltec** [comment]
As a next step, I would write up the requirements for two other place types and their events. "Meeting place" and "Public fridge" might be useful here, with the event types "meeting" and "task".

I wonder how "public fridge" could be abstracted:
- "share point"
- "sharing place"
- "share node"
- "sharing node"
- "distribution place"
- "swap place"
- "cycle hub"
- "community center"
- "public place"
- "exchange"

**Comment by brnsolikyl** [comment]
Thanks for the input, Tilmann!


> I wonder how "public fridge" could be abstracted
My favourite abstraction of "public fridge" is "sharing node", and being public (in the sense of not being group-bounded) seems to be a good feature for different use cases.

The two place types of "meeting place" and "public fridge" are usually exactly the same in the case of Solikyl and I can think also in the case of Bike Kitchens, so while it's useful to make one type private to the group and the other public, I think it could also be a bit confusing? Maybe it won't on the UI, but I'm having a hard time imagining how it would look like.

**Comment by tiltec** [comment]
> The two place types of "meeting place" and "public fridge" are usually exactly the same in the case of Solikyl and I can think also in the case of Bike Kitchens, so while it's useful to make one type private to the group and the other public, I think it could also be a bit confusing? Maybe it won't on the UI, but I'm having a hard time imagining how it would look like.

Indeed, I think the requirements are different enough between groups that it's not easy to make it a perfect fit. 

There are some for the data model:
1. build a generic model that supports attaching all kinds of functionality
2. build custom-tailored models for each distinct use case

If we go in the direction of (1), we have two options for the UI:
1. offer one generic type where users can modify every setting independently (e.g. choose place icon, place color, place category, public yes/no)
2. hand-pick a few types and give them names that reflect the reality of foodsaving groups and similar organizations (e.g. meeting, pickup, task)

I wonder what the cost is of making the website very generic - "project management tools" such as Trello are quite successful with this approach.
@djahnie and me investigated wechange.de ([code here](https://github.com/wechange-eg/cosinnus-core)) in the last days. It's a generic project communication tool for "transition movements" and it has been around for a while. I wonder how the "generalized Karrot" vision compares to wechange...

**Comment by tiltec** [comment]
A few scribblings about the "meetings" implementation:

- they should not have feedback
- the places shouldn't be called "stores"
- there could be "group meetings"
- meetings could be subscribed to, independently of location

Questions:
- do we want meeting series? they need a "weeks_in_advance" setting, should it be per series?
- should we generalize meetings as events in the UI?

**Comment by tiltec** [comment]
I had chats about these topics with @nicksellen and @djahnie , I'll write something about it here.

I feel blocked by uncertainty. What is the functionality that we want to expose to users? How do meetings/events/tasks fit the current "places+pickups" model?

I tried to tackle that uncertainty by asking those questions:
1. how do groups use stores and pickups for other purposes?
  - what are the biggest problems with it?
  - Can we do some easy changes to reduce the pain?
2. what might groups want to do in future?
  - is there a common abstraction to those things?

I wonder if the short term relief can be made in such a way that it also fits the long term vision. For example, I tried to [rename stores to places in the UI](https://github.com/yunity/karrot-frontend/pull/1398), but it's obviously a incomplete solution. Events are still called pickups; renaming them to events might lead to confusion in foodsaving groups (how can we try it out?).

On a more technical level, there are some questions about the data model:
- implement optional features via "extension model" or nullable fields?
- does the model hierarchy (group -> place -> event) make sense? Or should the place be optional, the location be a feature of the event?

**Comment by brnsolikyl** [comment]
I'll write down my thoughts to remember for the IRL-meeting we're having tomorrow...

I favour more the option of 1. build a generic model that supports attaching all kinds of functionality; and 2. hand-pick a few types and give them names that reflect the reality of foodsaving groups and similar organizations (e.g. meeting, pickup, task).

My reasoning is that we want to avoid changes on the UI that might create confusion for existing foodsaving groups - like you mentioned, Tilmann, about renaming pickups to events (although the change from stores to places seems more harmless) - while still being able to introduce and experiment with new use cases like the Bike Kitchens. Karrot has been evolving organically in contact with its user-base by more or less personal connections and feedback, and not so much by people adopting it because they happened to find it online, so I think we have a pretty solid basic understanding of how Karrot is useful to these foodsaving groups and we're just starting to explore a new use-case by the same way. So much of this development in relation to the community of users is based on both experience _and_ guesswork. 

So **what might groups want to do in the future?** is the key question...

Taking into consideration foodsaving + Bike Kitchens and and even other similar groups that work horizontally and on a voluntary basis to save and share resources (Free Shops, Repair Cafés, etc.), the _core general features_ that they might look for are:
* Communication
* Coordination to perform tasks that are regarded as necessary in the group (pickups, meetings, simpler tasks, attending an event, keep a place open, etc.), by people freely assigning themselves to it
* Sharing things (material objects) between peers and among groups

Remember, this is based on experience _and_ guesswork. Especially the third point is more based on guesswork, because it is a non-existing feature and it's also an extrapolation of the vision of Karrot being used by many similar groups in the same geographical region to share stuff.

When we meet I can describe the specifics of how people are using stores+pickups for other purposes, or what I've seen at least.

**Comment by tiltec** [comment]
From today's meeting:

- stores can most likely be renamed to places -> https://github.com/yunity/karrot-frontend/pull/1398
- next goal is to implement meetings
- should rename pickups to something more general before, proposals were "events" and "activities"
- it seems a good trade-off right now that all events belong to a place (no group events); but maybe make it clearer that places don't have to have a location

When choosing as general name ---
- "events": specific types would be "pickups", "meetings", "tasks"...
- "activities": specific types would be "pickups" and "events"

I think we should decide on the general name next. In the meantime I can already explore the meetings type without doing a rename.
