### ISSUE TITLE
Handle sparkpost suppression list

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1134]
I noticed today that we accumulated quite some emails addresses on a "suppression list" in Sparkpost: https://app.sparkpost.com/lists/suppressions
It means that Karrot can't send emails to these addresses anymore, not even password reset ones. Sparkpost will return a bounce event with reason "554 5.7.1 recipient address was suppressed due to customer policy".

This can happen for a number of reasons, listed here: https://www.sparkpost.com/docs/user-guide/using-suppression-lists/
Most commonly people seem to trigger a "List-Unsubscribe", a spam complaint or a bounce.

We already maintain our own blacklist inside Karrot, so maybe we should remove and disable the suppression list. Unfortunately, this doesn't seem possible. The [feature to skip suppression](https://www.sparkpost.com/docs/tech-resources/skip-suppression-functionality/) is only available in the enterprise version.

My idea would be to listen to "list-unsubscribe" and "spam-complaint" events via webhook, add these addresses to our own blacklist and remove the email from the suppression list via API call to sparkpost.

**Comment by nicksellen** [comment]
Just 13 I count for spam or unsubscribe, with most of the rest of bounces. Doesn't seem so bad?

**Comment by tiltec** [comment]
I deleted two manually before, so a bit more but not overwhelming. But as it does block base functionality of karrot I'd like to figure out a solution.

**Comment by tiltec** [comment]
Just had a look, 4 more "List Unsubscribe" in the last 7 days.

**Comment by tiltec** [comment]
SparkPost has some recommendations how to handle List-Unsubscribe:
https://www.sparkpost.com/docs/tech-resources/list-unsubscribe-functionality/
https://www.sparkpost.com/docs/user-guide/setting-up-unsubscribe-links/

We tried to replace the List-Unsubscribe header with our own link, but SparkPost just ignores it.
This code could be removed at some point:
https://github.com/yunity/karrot-backend/blob/f6d334596982a511171cb8f37ebb91c43c144a64/foodsaving/utils/email_utils.py#L112-L115

**Comment by tiltec** [comment]
Reading up on this topic again because @mr-kojo didn't get an invite email from a group on Karrot. His email address bounced almost a year ago and is on the suppression list ever since.

How is the interaction between Karrots bounces handling and the Sparkpost suppression list? I think if an email address is on any of these lists, emails won't arrive (even if the email address stopped bouncing in the meantime).

Sparkposts adds addresses to the suppression list if they bounce, if the receiver clicked List-Unsubscribe or if triggered a "Spam Complaint". They never get removed.

Karrot adds emails to the bounce list if it received [one of those events](https://github.com/yunity/karrot-backend/blob/7d579e5ac37d24851b21218ba34e8c9af69ac28f/config/settings.py#L191) for 5 times within 3 months. ([source](https://github.com/yunity/karrot-backend/blob/aad44ebf48c1d84412d65a29298184a52ca539eb/foodsaving/webhooks/models.py#L11))
```
EMAIL_EVENTS_AVOID = ['bounce', 'out_of_band', 'policy_rejection']
```
After 3 months, Karrot tries sending to this email address again.

*A example*:
1. Karrot tries to send a notification to foo@bar.com
2. Sparkpost accepts the request and tries to deliver to foo@bar.com
3. Delivery fails because of "bounce"
4. Sparkpost reports back to Karrot (via webhook): "foo@bar.com bounced, mailbox full"
5. Sparkpost adds "foo@bar.com" to the suppression list
... some days pass ...
6. Karrot tries to send another notification to foo@bar.com (less than 5 failures in the last 3 months)
7. Sparkpost accepts the request, _but does not try to deliver to foo@bar.com_ because the email is on the suppression list
8. Sparkpost reports back to Karrot: "foo@bar.com bounced, suppressed due to customer policy"
After few more tries, Karrot does not try to send to this email anymore.

What I read from this: Sparkpost actually just tries to send to an address once - if it fails, it will never try again. By doing this, it essentially renders Karrot's bounces handling unnecessary.

What could we do?
Option 1: remove bounces handling from Karrot and manage Sparkpost suppression list via API (e.g. remove bounces after some months)
Option 2: remove addresses from the Sparkpost suppression list as soon as they get created, essentially disabling it

**Comment by tiltec** [comment]
Just checked - 14 addresses have been added to the list in the last 90 days, now it has 127 entries in total.

**Comment by tiltec** [comment]
Moved away from Sparkpost, but Postal has a suppression list too. I'm keeping an eye on the suppression list, which seems enough for now.
