### ISSUE TITLE
Missing data for applications of groups not loaded right now

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#1135]
This is about the message notifications. They are missing information depending on which group is selected right now.

This is what I see when in EfA:
![image](https://user-images.githubusercontent.com/17573771/48555932-ce86e500-e8e2-11e8-86cd-7d163f16d032.png)
_(Shaq has no name, no picture and no application icon)_
_(AnnaP has no name, no picture and no application icon)_

This when in Solikyl:
![image](https://user-images.githubusercontent.com/17573771/48555983-e52d3c00-e8e2-11e8-8f4c-ad18519bf4cb.png)
_(Shaq has name, picture and application icon)_
_(AnnaP has not)_

And this when in Warszawa:
![image](https://user-images.githubusercontent.com/17573771/48556106-46eda600-e8e3-11e8-8823-26d74b4ae74f.png)
_(Shaq has no name, no picture and no application icon)_
_(AnnaP does)_

Also, as a user I don't see anything happening when I click the message notification of an application for a group not loaded right now.

**Comment by tiltec** [comment]
Good find! It happens when switching between groups. Seems I broke it in #1129
