### ISSUE TITLE
One available slot disappears when joining pickup

### ISSUE THREAD

**Issue by brnsolikyl** [yunity/karrot-frontend#1137]
When signing up for a pickup that has multiple slots available, one extra slot disappear from my view after I join the pickup. For example, if there are 4 slots available and I join the pickup, I'll see my avatar plus 2 other available slots. If there are 2, after I join the pickup there won't be any more available slots, at least from my perspective.

**Comment by tiltec** [comment]
Ah yes, I've noticed this too! 
Should fix this at some point... but I'm a bit afraid to touch that code because it's quite messy and my last attempt at rewriting this component failed after trying for a day or so :(
