### ISSUE TITLE
Bug with list of pickups awaiting feedback accross groups

### ISSUE THREAD

**Issue by brnsolikyl** [yunity/karrot-frontend#1138]
The list of pickups awaiting feedback is not group-bound. All the pickups I made on two different groups are showing on the feedback page of each group.

As I write this I noticed that after changing groups back and forth the list of pickups awaiting feedback has doubled in both groups (14 now instead of 7). I guess this is related but I haven't tested more.

Edit: indeed, after changing groups again and checking the list, it has tripled

**Comment by tiltec** [comment]
Closed by https://github.com/yunity/karrot-frontend/commit/cfa1769142dff44acf0ff2e01ca8b4ac1d68fce5
