### ISSUE TITLE
Playground users should immediately have editing rights

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#1140]
Right now directly after joining users have newcomer status in the playground group just like in every other group. This should not be the case, they should have all options from the start.

**Comment by lwm** [comment]
Gonna pick this up then.

**Comment by tiltec** [comment]
Now that's in production, I noticed that members of the playground group get bell notifications each time somebody gains editing permissions. Also the user receives an email when they gain editing permissions.

I think we should definitely turn off the bell notifications "user_became_editor" for the playground group, and maybe disable the email "you became editor" in the playground group.

What do you think?

**Comment by lwm** [comment]
Yep, makes sense! I'll pick this up.

**Comment by brnsolikyl** [comment]
Please turn it off asap! :laughing: 
Playground notifications are now making bell notifications almost useless since they're all over the place.

**Comment by nicksellen** [comment]
@brnsolikyl don't forget you can leave the Playground group ;)

But agree they should be turned off of course.

**Comment by lwm** [comment]
Fix coming tomorrow, I hope! Running out of time in the last days ... still on my radar :)

**Comment by tiltec** [comment]
I can do a deploy to production right after that (so maybe Saturday evening?), together with lots of recent changes :)

**Comment by tiltec** [comment]
Didn't do it yesterday, will try again tonight. 
@lwm do you have time today? Otherwise I'm happy to fix it!

**Comment by tiltec** [comment]
Ah I just saw https://github.com/yunity/karrot-docker/issues/4#issuecomment-459959023 so I guess this needs to be resolved before you can work on Karrot again!

**Comment by tiltec** [comment]
I'll pick it up and
- disable the "user_became_editor" bell because it distracts from useful notifications
- disable the "you became editor" email because the content is not accurate, it says "You've received enough trust"

I'll leave the "you_became_editor" bell enabled.
