### ISSUE TITLE
Keep up with new eslint-vue rules

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1148]
By today's update, eslint-vue has some new rules to keep us busy (and make the codebase nicer).

I commented most of them out to not distract myself too much from #1147, so this could be fixed up:

https://github.com/yunity/karrot-frontend/blob/13f1c6bcb09ab1369b88c8cf0df4e20733ec6b64/.eslintrc.js#L44-L54

1. Comment out one exception
2. Run `yarn fix`
3. Check if it could be fixed automatically, otherwise edit files manually while having `yarn dev` running to get direct feedback
4. Repeat from (1)

**Comment by djahnie** [comment]
@taistadam started with the first rule already.

**Comment by tiltec** [comment]
Two rules have been applied, to-be-done ones can be found at the bottom of https://github.com/yunity/karrot-frontend/blob/master/.eslintrc.js
