### ISSUE TITLE
Keep order of pickup collectors

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1157]
Details: https://community.foodsaving.world/t/feature-request-keep-order-of-signing-up-to-pickups/185

Should be as simple as adding an `order_by('-created_at')` somewhere and writing a little test case about it.

**Comment by JordanLozinski** [comment]
I'm trying to take this up as my first contribution to karrot. It might take some doing because I'm not very familiar with django.
I'm currently looking in [https://github.com/yunity/karrot-backend/blob/d5673022d5c6aca6ec062fd211dfe239a860af8f/foodsaving/pickups/api.py](foodsaving/pickups/api.py)

**Comment by tiltec** [comment]
Hey @JordanLozinski, welcome!
The Karrot backend API structure is guided by [Django REST framework](https://www.django-rest-framework.org/), so the documentation on [Model Serializers](https://www.django-rest-framework.org/api-guide/serializers/#modelserializer) might be helpful to you. 
There's a `PickupDateSerializer` in Karrot that contains a field named `collector_ids`. Through a `ManyToManyField`, it references the `PickupDateCollector` model, which doesn't specify an [ordering](https://docs.djangoproject.com/en/2.1/ref/models/options/#ordering) right now.

**Comment by tiltec** [comment]
How is it going @JordanLozinski ?

**Comment by lwm** [comment]
I have some time and was gonna grab https://github.com/yunity/karrot-frontend/issues/1140 and this one since it looks a bit inactive (and I can also do with helping the small ones ...).
