### ISSUE TITLE
Account deletion can't be confirmed on iPhone 6

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1158]
I received feedback via email that there seems to be an error when confirming account deletion via frontend.

I didn't investigate yet, so the first step would be to create a new account on dev.karrot.world and delete it again. If everything works fine, than this issue could be closed again. Otherwise, the problem should get fixed.

**Comment by sarathin** [comment]
I tried two scenarios and in both the delete account worked fine.

1. Created a new account and deleted it before doing email verification
2. Created the account again and did email verified, then delete it

In both scenarios received an email to click on "Delete your account" button and selecting it deleted the account.

**Comment by tiltec** [comment]
Thanks @sarathin, that's good news.
Which browser and OS did you use?

I just noticed that the bug reporter seems to be on iPhone, maybe that's the problem.

**Comment by sarathin** [comment]
openSUSE Leap 15.0 / Firefox. Don't own an iPhone so will not be able to verify this issue.

**Comment by tiltec** [comment]
I got the confirmation that the problem occured on iPhone 6. Don't have it either, so waiting for someone that has :)

**Comment by cstefanj** [comment]
Hi! I tried this on my iPhone 6s and it worked fine. I took screenshots in case it wouldn't work, let me know if you need them.

**Comment by tiltec** [comment]
Thanks! Then it might just be a single case. Will close this one :)
