### ISSUE TITLE
Delay pickup and conversations dissapearance by ~30 minutes

### ISSUE THREAD

**Issue by lwm** [yunity/karrot-frontend#1172]
> feature request: the pick ups and the conversations disappear exactly at the pick up time, Is it possible to make it half an hour llater, so people can still use the chat if somebody is late and also read the describtion? that would be great!

Just pushing this one out from the #karrot-dev channel.

**Comment by lwm** [comment]
I'll get on this for the next time then :dancer: :dancer: :dancer:

**Comment by taistadam** [comment]
hey @lwm I'm actually investigating this one atm, forgot to document it here...

**Comment by lwm** [comment]
All good!
