### ISSUE TITLE
Install Issue: Module quasar framework

### ISSUE THREAD

**Issue by AllanOcelot** [yunity/karrot-frontend#1207]
Hi all, I wanted to install Karrot and try to do some design fixes/tweaks/improvements, however when trying to install via yarn I get the following issue:

```
yarn install v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error quasar-framework@0.17.19: The engine "yarn" is incompatible with this module. Expected version ">= 1.6.0".
error An unexpected error occurred: "Found incompatible module".
```

Googling the issue yields no results - so I'm at a bit of a loss on how to resolve this.

Looking forward to getting stuck in and helping out with this great project!

**Comment by nicksellen** [comment]
You've got yarn `v1.5.1` and quasar is telling you it wants `>= 1.6.0`, so you need to upgrade yarn!

**Comment by AllanOcelot** [comment]
Ah! Didn't see the expected version number, thanks!
