### ISSUE TITLE
Make thread reply notifications more visible

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1230]
Currently, thread replies are in the "latest messages" menu listed below conversation replies:

![screenshot_2019-01-23_16-37-23](https://user-images.githubusercontent.com/4410802/51617760-36822900-1f2d-11e9-8129-869af6a9de85.png)

This is not super obvious, as highlighted by this comment from Disa (Solikyl Gothenburg):
> I think i understand the "summary of messages- place" now, and that it 
is meant to do just what i was asking for. But its not really clear, ive 
never seen the 'replies to threads-part' before in the usability-test, 
because i dont scroll down under two months old messages to look for new 
messages(now i know i should so its no longer a problem for me, but a 
new person beginning to use karrot and looking for a summary of messages 
will probably have the same problem).

We should think about a better way of presenting it, maybe have two tabs "conversations" and "threads" or just a hint that there are more notifications below.

**Comment by djahnie** [comment]
I like the tabs idea! Since we apparently will have tabs in the issues as well it makes sense to use them in more locations.

**Comment by brnsolikyl** [comment]
Tabs could be a good solution. I noticed a clear pattern from all of the usability tests we've done so far: people are confused by all buttons and notifications on the header. I think we need to tackle all of these problems together, and maybe try a bigger redesign for the next release. I'll try to sketch something...

We can do some usability testing on dev before we launch anything very new to production.
