### ISSUE TITLE
Missing karrots

### ISSUE THREAD

**Issue by mr-kojo** [yunity/karrot-frontend#1260]
On 28/01/2019 I accepted the application of user 1780 to group 62 on the production system and immediately gave him a karrot. Consequently he gained editing permissions (threshold 1). On the next day, I visited the members page which displayed the user with 0 karrots (and a red background). I gave him a karrot again and then he was displayed with 1 karrot and a green background (just as the day before).

Who ate the karrot?

**Comment by mr-kojo** [comment]
The rabbit was hungry again.

See user 1822. Same situation as described above. Note that no other user has joined the group in the meantime. Maybe that's useful to know.

**Comment by tiltec** [comment]
A lot of trust has been given in the meantime and I didn't hear of this problem again. We should keep our eyes and hears open, but if there are no more insights in the next month, I would close this issue.

**Comment by tiltec** [comment]
Aaand I found it! It happens when leaving a group (or when getting removed due to inactivity). Then all your given trust gets deleted. Big fail :see_no_evil:
