### ISSUE TITLE
Place subscriptions & conversations - follow-up

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1297]
From the PRs that resolved https://github.com/yunity/karrot-frontend/issues/986:

* walls of archived places are hidden right now, maybe need to show them in a special mode. backend could "close" conversations of archived stores
* store wall looks very similar to group wall, how can it be less confusing?
* new users won't be subscribed to any store and don't see pickups on the wall - maybe that's fine? but it's not easy to discover...
* "star" icon in sidenav is not very nicely aligned, could replace the status dot?

**Comment by tiltec** [comment]
Frontend bug: if the place has no wall messages and the user is not subscribed yet, it doesn't show the wall at all.

**Comment by brnsolikyl** [comment]
It looks good! I'm more concerned about the navigation issues you mentioned: 

- finding store-specific pickups comes new with an extra step; and 
- it might not be clear which wall they're at...

The first point might not be a big deal, given the subscription option. On the other hand, if pickups from  unsubscribed stores are not easily discoverable, that's a major drawback for non-popular stores. This something to be tested after a while in production.

Could the second point be solved by making it possible for users to add a banner to each store?

**Comment by tiltec** [comment]
> Could the second point be solved by making it possible for users to add a banner to each store?

Possibly yes, although it would be cool to have something that doesn't require user interaction. For example, we could add shopping cart to the top of the page.

That makes me thinking if the breadcrumbs in the topbar are actually useful.. isn't their purpose to give the user orientation on which page they are on?

**Comment by tiltec** [comment]
From https://community.foodsaving.world/t/introducing-store-wall-and-store-subscriptions/241/12

- [ ] show people who starred a place
- [ ] try out "star" button in sidenav, as shortcut
- [ ] try out tab navigation in place header (to replace sidenav section)

**Comment by tiltec** [comment]
We had discussions how we can make group members more aware of place messages when they are not subscribed. Ideas I can remember:
- show a dot if there were recent messages - but it can't be marked as read
- as before, but track read status even for unsubscribed users
- as before, but allow users to disable the "dot" as well (per place or per group?)

Seems a lot of effort to me to implement this right, but could also be very useful!

**Comment by tiltec** [comment]
Talked with @brnsolikyl about improving visibility of place walls & place wall messages again. It seems worthwhile to investigate adding a fourth conversation subscription status besides "full", "some" and "unsubscribed" that shows unread counts (or just a dot if something is unread) on the sidebar and place pages. But it wouldn't show the unread status anywhere else, especially not in the "latest messages menu" in topbar. This status maybe called "normal" and we could make it the default for all people that are currently unsubscribed.

The idea is that place wall messages are important enough to make all group members aware of them. But people should have the option to unsubscribe if they get annoyed by the sidebar notifications.

Technically, it's very much like the "some" status (also called "muted" in the database), but filtering those conversations from the latest message list and just delivering the unread count.

Ideally, it should go together with #1534 to make sure the count somehow reflects reality.
