### ISSUE TITLE
No new slots have appeared in recurring pickups since Saturday (2nd March)

### ISSUE THREAD

**Issue by mzpawlowski** [yunity/karrot-frontend#1323]
Since Saturday (2.03.2019) no new slots have appeared in any of the stores with recurring pickups in Warsaw group. In majority of our stores we have slots open for two weeks ahead which means that at the time when I'm writing this (Monday, 04.03.2019), we should have slots available for Monday, 18.03.2019, but we only have them until Saturday, 16.03.2019. So it looks as if something happened on Saturday which prevented new slots from appearing in Karrot.

**Comment by tiltec** [comment]
Thanks for the report! A server upgrade on Saturday affected our task runner service. I restarted it, should be solved now.

**Comment by mzpawlowski** [comment]
Yes. It's ok now. Thank you for a quick action!
