### ISSUE TITLE
Allow adding pickups to Google Calendar to enable upcoming pickups notifications

### ISSUE THREAD

**Issue by mirekphd** [yunity/karrot-frontend#1376]
Currently Carrot users can miss upcoming pickups deadlines because there are no notifications of upcoming pickups. The notification functionality is already implemented in Google Calendar (less popular calendars can be added later), so it would be easy to link to it. An example could be  meetup.com, who let Google Calendar handle their notifications. Most people have Google account, so they are also automatically Google Calendar users.

**Comment by tiltec** [comment]
Hi @mirekphd, welcome!

I had a quick look how meetup.com does it: 
![Screenshot_2019-03-31_10-25-03](https://user-images.githubusercontent.com/4410802/55286692-61f71900-539f-11e9-99ec-edfff38fcfd7.png)

Clicking on "add to calendar" opens a popover where users can select "Google Calender". Clicking on it opens a link `https://calendar.google.com/calendar/r/eventedit?location=<text>&sprop=name:<name>&sprop=website:<link>&details=<long text>&text=<short name>&dates=<start>/<end>&sf=true`

Is this how you imagine it?

**Comment by tiltec** [comment]
By the way, Karrot has some pickup notifications already:

- an email the evening before
![Screenshot_2019-03-31_10-35-21](https://user-images.githubusercontent.com/4410802/55286800-ba7ae600-53a0-11e9-9edb-a6e494979bc1.png)

- on-site notifications 6 hours before
![Screenshot_2019-03-31_10-32-57](https://user-images.githubusercontent.com/4410802/55286803-d7171e00-53a0-11e9-8090-da579f62fc3d.png)

At some point, I also want to add more push notifications to the Karrot app.

**Comment by tiltec** [comment]
Closing this due to lack of feedback, can be reopened if requested again.
