### ISSUE TITLE
Sort emoji reactions by creation date

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1456]
Currently emoji reactions are in random order. It would be nice to append new emoji reactions. Either add `created_at` to the API or sort the array by creation date.

**Comment by jasmlau** [comment]
Me and @allibail would like to claim this issue!

**Comment by allibail** [comment]
In order to access the documentation for the api, it looks like we need to be authorized. How do we go about doing that?

**Comment by tiltec** [comment]
You mean https://dev.karrot.world/docs/? You can use `foo@foo.com` and `foofoo` to log in, or your personal account if you created one on dev.karrot.world

**Comment by nicksellen** [comment]
Seems non-essential, so we close it.
