### ISSUE TITLE
Place managers / responsible person for a place

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1504]
As we get requests for "store managers" from time to time, I'll open this to keep track of the discussion.

Andrea from Solikyl Gothenburg via email:
> Possibility as a responsible person to delete people from specific pickups/store, both recurring and specific ones.
> Possibility to block certain people from stores/pickups, both recurring and specific ones.

**Comment by brnsolikyl** [comment]
To avoid falling back on the old discussion of strict app-defined hierarchies, I suggest that we explore the conflict resolution feature for this. This looks like a typical case of governance in which people could vote whether they'd like to block a person from a certain store.

**Comment by tiltec** [comment]
spotter requested place managers here: https://community.foodsaving.world/t/imagine-a-enhanced-workflow/337

The goal is to have a simpler interface for people that are _only_ place managers and don't do pickups:

>  The only thing what I need from them is setting up the pickup in their Place. The interface is too complex for them. They are never make any other operation than setting time and perhaps the volume.
