### ISSUE TITLE
Allow to choose "did not participate" in pickup feedback

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1505]
Andrea from Solikyl Gothenburg suggested via email:
> Possibility to choose "Did not participate" in response to the pickup feedback

and 

> Possibility to choose "Did not participate" after a pickup has started/been carried out.

**Comment by tiltec** [comment]
Who is allowed to click that? The person that gives feedback? Another collector?

**Comment by nicksellen** [comment]
This could get quite complex depending on what the need really is:
- it could just be allowing people to remove themselves from activities even after they've finished
- _or_ it's something that let's one of the participations say that another person who was meant to be there didn't turn up
... _or_ something else?

We have to ensure we keep the statistics accurate too, as currently we use the fact that somebody is a participant on an activity to "know" if they did it or not.

It feels like we need to explore what is actually needed here before we can implement something.

**Comment by nicksellen** [comment]
For reference, here is the current UI, which explcitly asks people "Did everyone show up?" but you can only represent the answer in text, not data.

![dideveryoneshowup](https://user-images.githubusercontent.com/31616/99904817-59b2c680-2cc5-11eb-9590-2a81ee7c85be.png)

**Comment by dwaxweiler** [comment]
The implementation of the [proposal](https://github.com/yunity/karrot-frontend/issues/1508#issuecomment-781293655) of @dpaque in #1508 might close this for now too.
