### ISSUE TITLE
Hide "give feedback for pickup" on group wall

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1508]
Andrea from Solikyl Gothenburg suggested:
> Possibility to choose "Do not leave feedback" on the pickup feedback so it disappears from one's main Karrot page.

There's already a notification about this in the "bell notifications" menu, so to keep it simple we might as well remove the wall notification completely.

~Same goes for the applications notification when we added the "Applications" sidenav entry.~ done

**Comment by tiltec** [comment]
Related to #1535

**Comment by dwaxweiler** [comment]
In my group, we use the feedback feature a lot. We have a rule that states that at least one person needs to write some feedback for transparency and for detecting issues early on. karrot also reminds you very visually of it on its main page, which I think lets more people write feedback.

I discuss this issue as some people of our group have suggested to be able to hide this reminder. I would suggest to enable hiding of this reminder for the others as soon as one person of the pickup has written some feedback.

**Comment by nicksellen** [comment]
Just briefly for now, I think would could implement this by adding a boolean field on the `ActivityParticipant` to store this information, something like "feedback dismissed", or "no feedback", or something.

And then when we do the query to fetch the "feedback possible" activities we can filter them out, and the user would have an option to dismiss the nagging thing...

... a totally different approach would be to make that message just another way of displaying the bell notification, and those are already dismissible.

... and whilst I'm here, another totally different approach... have it so you can create an "empty" feedback that basically says, "I have no feedback", as saying you have no feedback is _kind of_ feedback in itself ;)

**Comment by tiltec** [comment]
There's already a bell notification about giving feedback I think! But it's way easier to ignore, since the user needs to open the menu first.

**Comment by nicksellen** [comment]
> There's already a bell notification about giving feedback I think! But it's way easier to ignore, since the user needs to open the menu first.

Yup! That's why I wondered if we could somehow use it, but display it sort of like it is now:

> ... a totally different approach would be to make that message just another way of displaying the bell notification, and those are already dismissible.

... just brainstorming really.

**Comment by nicksellen** [comment]
It's also a little similar to https://github.com/yunity/karrot-frontend/issues/1505, which is an idea that you can give "did not participate" as feedback.

**Comment by dwaxweiler** [comment]
Oh, no, the bot is trying to help again! :smile: Could somebody reopen this please?

I agree that the bell notification is way easier to ignore. Personally, I think it was a good design decision to display your upcoming pickups and the feedback you need to write on the first page as you see it instantly.

The question we should discuss is whether we want to give everybody that has participated in a pickup the possibility to give no feedback or if we want to give this possibility only after one person has already left feedback. What do you think, @nicksellen and @tiltec?

**Comment by nicksellen** [comment]
A related topic came up about the UX of the banner saying you can give feedback, not everybody will recognise it as clickable, so this could be improved possibly at the same time?

The main distinction is do we want to:
a) make it possible for people to totally dismiss that feedback request,and they will no longer be able to feedback for that activity (the count in the sidebar would go away)
b) just make the notification banner go away (the count in the sidebar would remain)

Depending on a or b makes a big difference about the implementation. My gut says a, whaddya think?

Here's how it looks:

![awaitingfeedback](https://user-images.githubusercontent.com/31616/99904560-7948ef80-2cc3-11eb-96d7-8355e80e3d3e.png)

**Comment by dwaxweiler** [comment]
I think it would be an improvement to make it possible to totally dismiss this banner. However, I only fear that less people would give feedback as a consequence, which would be a pity for the group's transparency. Additionally, I wonder whether it should be possible to undo a dismissal done by accident. What do others do think?

**Comment by dpaque** [comment]
Hi, we did some mob programming to tackle this issue and we came up with the following suggestion:

We keep the yellow banner as-is and we add a 'Dismiss' button in the Feedback Form. Something like this:

![Draft](https://user-images.githubusercontent.com/73907229/108353909-fb748180-71e8-11eb-978d-e5678c3aa92d.JPG)

With this approach we would keep the yellow banner as initial trigger for writing feedback and we allow the user to dismiss it in the next step of the process.

How do you feel about this approach?

**Comment by brnsolikyl** [comment]
I think it's a good compromise given what's been commented above!

**Comment by brnsolikyl** [comment]
Another thing a bit related, but not sure if also within the scope of what you want to work on @dpaque ...  Within my group I've noticed a recurring pattern of people writing their feedback on the main wall. They think the banner prompts them to write it there, right below it, and are not aware it's clickable. If you have any good idea on how to better design it we'd have another great improvement in usability regarding the feedback feature!
