### ISSUE TITLE
Bike Kitchen theme

### ISSUE THREAD

**Issue by brnsolikyl** [yunity/karrot-frontend#1509]
Related to our discussion at #1259 , how could we make a pre-defined Bike Kitchen theme? Consider the following a draft that will be updated in the following days, when I get more feedback from users... These are the elements that could be changed in my opinion:

* rename `pickups` to `activities`
* replace the food basket icon for a bike one like `fa-bicycle` or another neutral one
* replace the feedback icon for... what? `fa-check-square`, `fa-reply`, `fa-thumbs-up` `fa-book`?
* leave the feedback feature with the comment field alone, taking away the amount of food saved
* change the background image to a bike-fixing related one. Maybe the one I used at my first mockup (in my repo)?

**Comment by djahnie** [comment]
What still needs to be adapted:
- the automatically sent out emails in the backend
- possibly other things in the backend

**Comment by tiltec** [comment]
@brnsolikyl check it out here: https://dev.karrot.world/#/group/24

**Comment by brnsolikyl** [comment]
Backend: true, I had forgotten about it!

Damn, you two were mega productive this week! :smile: 
Cool to see the changes (even though the background I chose is much uglier than what I remembered)

I noticed yesterday that I could not give feedback some minutes after I did the pickup, it lead me to a page saying "all done" or something similar. Now I tried it again and it worked. Have you been working on it meanwhile? I'll try to reproduce the problem...

**Comment by tiltec** [comment]
Background is easy to change! Maybe it's good for the first release, and then somebody creates a better one hopefully ;)

> I noticed yesterday that I could not give feedback some minutes after I did the pickup, it lead me to a page saying "all done" or something similar. Now I tried it again and it worked. Have you been working on it meanwhile? I'll try to reproduce the problem...

Pickups have a default duration of 30 minutes, I think feedback can only be given afterwards.

**Comment by tiltec** [comment]
Need to spend some time with the backend to find a nice solution for emails, push notifications and error messages. Currently I don't have an elegant solution in mind.

**Comment by brnsolikyl** [comment]
Another detail: Take away "weight" from "Both comment and weight cannot be blank" when entering blank feedback.

**Comment by tiltec** [comment]
This is a backend error message, we need a different approach to handle them. Maybe it's a good opportunity to move all error messages into the frontend and address them via identifiers…? (just thinking out loud)

**Comment by tiltec** [comment]
@brnsolikyl did you get more feedback regarding non-fitting emails or error messages for the bike kitchen theme? I wonder there's still something that should be done in the next time...

**Comment by brnsolikyl** [comment]
Nothing about the e-mails but I'll investigate a bit more. I haven't asked for feedback in a while and I think nobody there would contact me spontaneously to give me one. hehe
Definitely no big issues here...

**Comment by tiltec** [comment]
Thanks, then I think it's ok to close this for now. Feel free to re-open if something comes up!
