### ISSUE TITLE
Add filters to history lists

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1520]
From https://community.foodsaving.world/t/how-to-handle-much-wanted-pickups/214/22:

To improve history usage, it's useful to filter it by type.

Additionally, we should improve rendering (e.g. use the same way of displaying pickups as in the pickup list).

**Comment by dwaxweiler** [comment]
Hello @tiltec, could you reopen this issue please? With a growing number of members, such a type filter becomes more and more useful in my opinion.
