### ISSUE TITLE
Define all common icons in src/base/icons/icons.json

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1529]
@djahnie and me introduced an "icon service" for the bike kitchen theme and used it for the "pickup" and "feedback" icons.

To make the transition complete, we should define all common icons in Karrot in `src/base/icons/icons.json` and replace all direct usages with references to the icon service (e.g. `$icons('pickup')`)

**Comment by thumbsupep** [comment]
I noticed some icons appear both with fa-fw class and without it. There are 3 solutions I can think of that are worth discussing before implementing everywhere:

make two copies of every icon that sometimes appears with `fa-fw.` ex. `place` and `place_fw`. This seems to be the direction the code is already going https://github.com/thumbsupep/karrot-frontend/blob/issue_1529/src/base/icons/icons.json#L7-L8
provide the `get` function with a second parameter that will specify whether to get the icon with `fa-fw` appended as a classname or not https://github.com/thumbsupep/karrot-frontend/blob/issue_1529/src/base/icons/index.js#L13
use template literals (it's an es6 thing) to add fa-fw inline whenever it's needed https://github.com/thumbsupep/karrot-frontend/blob/issue_1529/src/places/components/PlaceHeader.vue#L267
I'm in favor of option 2. it's backwards compatible for anywhere already using the icon method, will allow us to store potentially half as many icon names, and we're abstracting the `fa-fw` post-fix classname

My question is if it's more of a performance hit to append a string and call the turnery operator any time we get an icon. vs. just doing a lookup on an object of potentially twice the size.
I think the performance implications of both of those things are negligible, which puts me in favor of option 2.

**Comment by tiltec** [comment]
`fa-fw` tells Font Awesome to make the icon fixed width. This is usually helpful to vertically align content. More on that: https://stackoverflow.com/questions/41140132/what-is-the-purpose-of-the-fa-fw-class

Besides Font Awesome, we sometimes use Material Icons. No matter which option you choose, it should allow replacing a FA icon with a Material icon or something else.

That rules out option 3, so you could go with option 2. I'm also fine with option 1 because it has less complexity. (Reducing complexity is more important than reducing duplication)

**Comment by thumbsupep** [comment]
ah that makes sense. I'll stick with option 1. thanks!
