### ISSUE TITLE
Migrate away from Sparkpost before Sep 15 (or ask for sponsorship)

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1653]
Mailgun might be another option. Sending should be easy to switch (thanks to `anymail`). Receiving needs more adjustments.

> we will be deprecating our old free plans. On or before September 15, 2019, you will need to login to your SparkPost account to select from our current plans. Based on your sending patterns and feature usage*, we recommend the 100K Premier plan. If you do not select one of the current plans by September 15, you will automatically be migrated to our free “Test” plan, with a limit of 500 emails/month and 100 emails/day.

**Comment by tiltec** [comment]
Another option: we could keep incoming emails via Sparkpost and send emails via Mailgun. Maybe a good temporary measure if we don't get a sponsored account from Sparkpost.

**Comment by tiltec** [comment]
I'm trying out https://github.com/atech/postal despite the usual warnings of not rolling out your own email system. It isn't supported in `django-anymail` yet, so it needs even more effort. But maybe that's worth it...

**Comment by tiltec** [comment]
May also look into https://mailcow.email/

**Comment by tiltec** [comment]
We asked SparkPost for sponsorship, this is their reply:

> You recently reached out regarding non-profit pricing for SparkPost plans. At SparkPost we understand the value and impact of community-driven organizations and our team is always looking for ways to support our customers. We are happy to offer you a discount on the 50K Starter plan to help you meet your budget and keep you sending! 
>
> In order to verify your account we will need the following information: 
> 
> - A copy of your non-profit determination letter;
>     - or if you are a community service organization/open source project, a letter stating your business status, e.g. community organization, civic organization, etc. 
> - A link to your website or repo 
> 
> Once we receive this information and verify your account, we will email you a code for 90% off the 50K Starter plan which would bring your plan total to about $2 per month. All we ask is that you show SparkPost a little love by adding “Powered by SparkPost” in your email footer. That’s it!

**Comment by tiltec** [comment]
According to https://www.sparkpost.com/pricing/, the "Starter" plan doesn't include subaccounts, which we currently use to keep status webhooks separated for different deployments.

I'd also favor having no running costs.

I'll look into mailgun more, especially their status webhooks.

**Comment by tiltec** [comment]
I noticed that we send 15k emails per month, more than mailgun would send for free. So I'm back to setting up `postal` - if it works until Sunday, I'll switch to it; otherwise we might pay Sparkpost for a month or so.

**Comment by tiltec** [comment]
Sent my first test email!

![image](https://user-images.githubusercontent.com/4410802/64703174-37f86580-d4ac-11e9-814f-90c3ca10c6ff.png)

**Comment by nicksellen** [comment]
Nice! Looks useful too. All that info.

**Comment by tiltec** [comment]
I managed to switch dev.karrot.world over to Postal, using a [patched anymail version](https://github.com/tiltec/django-anymail). Both outgoing and incoming email seem to work.

Postal leaves a lot to improve. I noticed these things:
- no documented way to verify webhook message authenticity. There seems to be an [undocumented header](https://github.com/atech/postal/issues/432), which somehow uses the DKIM key
- emoji subject cause internal server error because Postal uses mysql's `utf8` instead of `utf8mb4`. There is [a Pull Request](https://github.com/atech/postal/pull/391) open since two years that provides a fix
- bounce handling relies on a special header field which seems not very solid to me. [VERP](https://en.wikipedia.org/wiki/Variable_envelope_return_path) should the way to go!
- the built-in suppression list [doesn't yet clear after 30 days](https://github.com/atech/postal/pull/867). It's also confusing that sending to a suppressed address only generates a `Held` status, not a `SoftFail` or something better

**Comment by tiltec** [comment]
Feedback loop test address: https://www.socketlabs.com/blog/bounce-and-feedback-loop-test-addresses/

Feedback loop resources: https://www.m3aawg.org/fbl-resources

**Comment by tiltec** [comment]
I opened a WIP pull request for anymail here: https://github.com/anymail/django-anymail/pull/166
