### ISSUE TITLE
Consider supporting LDAP login

### ISSUE THREAD

**Issue by decentral1se** [yunity/karrot-frontend#1670]
Hey there again ;)

I'm volunteering quite with https://yunohost.org/ now and I am thinking to make Karrot an official packaged application there. That would mean it would become much easier to setup Karrot for self-hosting.

One of the "magic" parts of Yunohost is LDAP integration across all the installed applications. This allows for a single sign on and eases the administration of the server and the end-users.

So, has anyone thought about LDAP integration for Karrot? I am unsure if it would be difficult to integrate but I would at least like to start the conversation. I assume that Yunohost LDAP users would just be logged in as Karrot site administrators or whatever "super power" account type you have.

**Comment by tiltec** [comment]
Hi @decentral1se, nice to see you around here!

I think LDAP support might be useful for Karrot, so we can support Yunohost and other Single-Sign-On systems. Although in the Yunohost case it's maybe less useful right now as Karrot has no super power accounts - all server configuration is done via files.

I consider this low priority myself, but would be interested to support others who want to give it a try.

**Comment by nicksellen** [comment]
We discussed this briefly today, and have a bit of renewed interest in supporting installation in yunohost. Personally, I'd like to try out yunohost anyway, especially now it's working on debian buster.

It's still not high priority, but at least very interesting :)
