### ISSUE TITLE
Add location-based overview page

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#1704]
Gothenburg is the perfect example of a city that has multiple sharing groups that can benefit from Karrot. To enhance synergies it would be beneficial if there was a place to see all the groups that belong into that area. (We first discussed this in the [2019-08-07 Karrot call](https://community.foodsaving.world/t/weekly-call-about-karrot-development/289/12).)

Requirements/ideas
- visible for everybody, not only logged in users
- autogenerated based on group location (e.g. 50 km radius..?)
- accessible via search function on landing page and/or direct link
- no extra marker on the world map
- no tile like all groups have
- really only shows when looked up (or should it..?) and then shows a visibly different tile for the overview page (different layout? different section? unclear still...)
- when clicked shows all group tiles of that region on the right, where the world map was before (needs different solution for mobile)
- should work with different spellings (e.g. gothenburg, göteborg, gbg - not sure how well supported this is)

**Comment by brnsolikyl** [comment]
From your description it seems like a quite hidden feature. I cannot really understand how the user would see it except when looking for it. And still a bit unclear how it would look like. But the specs are good and I'm all for it, as you know this already. hehe
 
Here's another way I imagine this feature -. Karrot's first page when logged out would no longer be the world map by default but a zoomed in map (the 50 km radius you mentioned, or maybe just the default scale in OSM for the city in question), based on the user's geolocation. The group tiles shown first are "Groups near you" and scrolling down or zooming out you'd have the rest on "Discover the world".

There should also be an easy way to access this page when logged in, although that is part of the larger issue of facilitating the change between groups.

Thinking some steps ahead, this feature would work awesome together with public places #1449 being marked on the map as well. It could easily create a more dynamic and updated version of these websites mapping the sharing economy like smartakartan.se here in Gothenburg or https://pamapam.org/ in Barcelona

**Comment by djahnie** [comment]
Ah, now that I started making a sketch of what I imagined this feature to be first, I came to realize that your idea is much better, @brnsolikyl... :sweat_smile: 
So I'll just close this issue and make a new one maybe..? And add a wireframe of how yours could look like...^^

**Comment by brnsolikyl** [comment]
Don't throw your idea in the trash bin prematurely! Can't it be saved? Maybe there's parts of it that still can be consumed? :smile: 

I think we could still work on the same issue. Anyhow I'm looking forward to see the wireframe!

**Comment by brnsolikyl** [comment]
This is now ongoing with https://github.com/yunity/karrot-frontend/pull/2212
Probably better to close it when the PR is merged
