### ISSUE TITLE
Make it easier to switch between groups

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1746]
From Bruno:

> For example, a drop-down menu on the group logo at the header to the left, showing other groups that a person belongs to, would probably make a difference.

**Comment by dwaxweiler** [comment]
Psh, bot, go away! Our local group would be happy about this. :)

**Comment by nicksellen** [comment]
@dwaxweiler haha, this is a good example of where the bot helps us to know what is useful for people still! (assuming they are reading github notifications).

This is one @brnsolikyl will be working on soon I think with my assistance :)

Btw, @dwaxweiler what is your use case for multiple groups?

**Comment by dwaxweiler** [comment]
I am happy to hear that! :+1: 

For Foodsharing Luxembourg, we have the idea of using more than one group in the medium term to have a general group for everybody and more local kind of sub groups.
