### ISSUE TITLE
Invitation emails are always in English

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1769]
...but they should be in the locale of the user who sent the invitation.

**Comment by dhuang612** [comment]
I would be interested in taking this on

**Comment by tiltec** [comment]
Hi @dhuang612, that would be great!
Did you already get karrot-backend running on your machine?

**Comment by dhuang612** [comment]
no not yet, I'll work on that today.

**Comment by dhuang612** [comment]
I didn't realize the backend would be in python..
I'm not sure I'll be able to get this updated

**Comment by Abdujabbor** [comment]
@dhuang612   can I try help to you, I am not professional but I know core knowledge of python, and a little bit about django also.

**Comment by dhuang612** [comment]
Hi @Abdujabbor 

That would be great!

**Comment by Abdujabbor** [comment]
@tiltec I have tried to solve this issue, could you please look PR: https://github.com/yunity/karrot-backend/pull/850

**Comment by foster999** [comment]
@Abdujabbor I think you might have miss-understood the request here. It looks like the translation functionality is not currently working (translating to other languages), but they would like it to work. Your PR removes the functionality, which doesn't solve the issue.

**Comment by Abdujabbor** [comment]
@foster999  yep you right, it seems that I didn't understand. I would fix and send another PR.

**Comment by tiltec** [comment]
Hi @Abdujabbor - thanks for taking a look at this! @foster999 is right, the goal is to have translations in the language of the user who sent the invitation.

**Comment by RonKbS** [comment]
Hello @Abdujabbor ,

I'm going through this as I familiarise myself with the codebase so that I'm prepared for any other issue that comes up that I can take a look at.
So far, I'm looking at the Jinja translation extension (in settings.py) and whether it's working as it should. Hope this helps.

**Comment by lenniezelk** [comment]
is this still open? If so i'd like to work on it @tiltec

**Comment by tiltec** [comment]
Hi @lenniezelk, yes this is still open! Happy to give more advice if my last comment is not sufficient!

**Comment by lenniezelk** [comment]
@tiltec @nicksellen i think this was resolved by my pr https://github.com/yunity/karrot-backend/pull/887
issue is in wrong repo

**Comment by tiltec** [comment]
Indeed! To auto-close the issue when the PR is merged, you can write "Closes https://github.com/yunity/karrot-frontend/issues/1769" in the PR description.

> issue is in wrong repo

We wanted to move towards one repo for both client and server code, so we started with having issues in one repo only already.
