### ISSUE TITLE
Make pickups with end time visible during its whole duration

### ISSUE THREAD

**Issue by brnsolikyl** [yunity/karrot-frontend#1789]
Pickups/events that are set with an end time will disappear after the default time (30 minutes?) while chat is still enabled. I suggest we make it visible during its whole duration. For example, if it is set between 1 pm and 5 pm, it should be visible from 1 to 5. Of course, joining the pickup after it has begun should be disabled.

**Why?** The practical reason is because sometime people who are not part of the pickup/event wish to coordinate with the people who joined it through the chat. In Solikyl there might be an event at place A to pick up the food and another event at place B to receive, unpack the food, clean etc. People who join A might want to coordinate with people who join B and vice-versa

**Comment by tiltec** [comment]
I think pickups are already visible for their whole duration, but only for those that joined. So the goal would be to have all ongoing pickups visible for all group members, without confusing them.

**Comment by brnsolikyl** [comment]
Right! I think the current warning message "This pickup has already started" or something like would suffice, while disabling the slots for signing up
