### ISSUE TITLE
Add picture upload to conversations

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1793]
From Disa in https://community.foodsaving.world/t/weekly-call-about-karrot-development/289/27

> Several people in Bikekitchen Gothenburg have told me they would want to be able to upload pictures to the chats in karrot, and perhaps would use it more if it was possible.

This is related to #963 - my comment from https://github.com/yunity/karrot-frontend/issues/963#issuecomment-458984048 is relevant here:

> it's already possible to reference a picture in [...] Markdown, but users would need to figure out the hosting solution by themselves (needs to be on https to fulfill our Content Security Policy).
This is closely related to having pictures in any message on Karrot, so if we decide to implement that, we might add an option to upload pictures and add them into a Markdown field with a single click. Might look up how Discourse does it.

**Comment by nicksellen** [comment]
There seems to be two approaches used:

1. chat platforms (e.g. slack, mattermost) do images as attachments that appear at the bottom of a message
2. forums (e.g. discourse) do it by having the picture inline (upload picture, then automatically insert the relevant markup to display picture)

Given karrot chat is more of a chat, I would go towards option 1.

Another consideration is for general purpose file upload. In mattermost you can attach any type of file using the same mechanism. Given we use [versatile image field](https://django-versatileimagefield.readthedocs.io/en/latest/) library already though, maybe it's easier to just handle images, and think about other types separately.

**Comment by tiltec** [comment]
You have my support for option 1, to attach one or more images to a message. I'm unsure whether we should postprocess them to reduce size (like Telegram does).

**Comment by brnsolikyl** [comment]
I just e-mailed Disa asking what the use case is exactly. I'm guessing they'd like to post pictures of bikes they picked up and saved. That would not work well on pictures on feedback #963 since they do not use the pickup/event feature for actually doing these pickups, so there is never any feedback. On the wall should work fine. I wonder if it wouldn't be even better to have pictures only on a sharing feature (as suggested [here](https://community.foodsaving.world/t/sharing-feature/281/6)) to make the wall more dedicated to general communication and organizing while having the other feature with pictures more focused on the shared and available resources. I guess we'll have to see how people make use of it.

**Comment by samuelpetroline** [comment]
Sorry to jump in into the discussion, but I was seeing the debate and noted that since this is an open source project you could benefit from the Imgur API (https://apidocs.imgur.com/?version=latest) for free. This way you could attach the image to the message and abstract the hosting and all the trouble it includes. I don't know about the Content Security Policy, though.

**Comment by brnsolikyl** [comment]
Again, from the Bike Kitchen group (this was a couple of months ago and has been on my list for a while...), and Disa was not in this conversation:

> Person A: Can't we post pictures here?
Person B: No, it's a big shortcoming and many have asked for it. I believe they said it may come sooner or later, but can take a while
Person C: Agree, really something that is missing...Who should we ask? Do we have any possibility of putting some pressure?

**Comment by nicksellen** [comment]
I started working on it!

> here

Where is here btw? I kind of assume the wall is the first place it makes most sense? But maybe also other types of conversation?

**Comment by nicksellen** [comment]
of three I think the slack-style is the most appealing to me.

## slack image upload

* multiple images
* mini thumbnails underneath message input
* you can add/remove images whilst you're composing the message
* press send and message + zero or more images are published

![slack-message-input](https://user-images.githubusercontent.com/31616/87985046-41465b80-cadb-11ea-8ee8-428f9a24118a.png)

## rocket chat image upload

* big modal for image upload
* have "file name" and "description" fields
* only 1 image

![rocketchat-imageupload](https://user-images.githubusercontent.com/31616/87985043-3f7c9800-cadb-11ea-810c-ded0faa17c88.png)

## whatsapp web image upload

* multiple images
* also a big preview field for a selected image
* can add a "caption"

![webwhatsapp-image-upload](https://user-images.githubusercontent.com/31616/87985045-40adc500-cadb-11ea-8fc6-49dfe7723e7e.png)

## zulip image upload

* markdown syntax formatted (GitHub style)
* multiple images allowed
* (small) preview button to view rendered post

![zulip-image-upload](https://user-images.githubusercontent.com/31616/87985473-f5e07d00-cadb-11ea-8a5f-6750b8819e9f.png)

**Comment by brnsolikyl** [comment]
The conversation about having a picture happened on a place's wall.

I personally prefer something with a small preview, like the one by Slack, but I'm usually on desktop, and many people use mobile, in which case a bigger preview is probably better. I'm not sure if both caption and title are necessary. I'm going to dig in the use case more.

**Comment by nicksellen** [comment]
Maybe we should move this conversation over to the community forum?

**Comment by brnsolikyl** [comment]
Definitely! I'd just throw out the question of how people would like to have images on conversations and how they would use it. Then present the options you laid out. What do you think?
