### ISSUE TITLE
Leaving a group is not possible

### ISSUE THREAD

**Issue by Schnegel** [yunity/karrot-frontend#1831]
It's not possible to leave a group for both [karrot.world](karrot.world) and [dev.karrot.world](dev.karrot.world).

After selecting `Yes` having question `Are you sure you want to leave this group?`, nothing happens.

**Swagger**
Using swagger it throws an error message for missing or incorrect CSRF token.
It's the first time I am using Swagger, hope I checked it correctly:
1. I authenticated in swagger with my test account for dev.karrot.world
2. I tried to use `api/groups/{id}/leave` with my group id (which was 52)

_Code:_ `403`
_Response body:_
```json
{
  "detail": "CSRF Failed: CSRF token missing or incorrect.",
  "error_code": "permission_denied"
}
```
_Request URL:_
`https://dev.karrot.world/api/groups/52/leave/`

**Comment by tiltec** [comment]
Thanks for the report! I think the problem is with the frontend. The CSRF error looks unrelated, at least I managed to leave the group via the API successfully just now.
