### ISSUE TITLE
Creating recurring pickup: recurrence rule disappears when changing from weekly to custom

### ISSUE THREAD

**Issue by brnsolikyl** [yunity/karrot-frontend#1833]
When creating a new (although not when editing) recurring pickup, and changing the setting from Weekly to Custom, the recurrence rule disappears and it becomes very unintuitive for the user that does not now iCalender rules.

Here's a little video:
https://filer.solikyl.se/index.php/s/ycJFQDaKXWFkfce

**Comment by tiltec** [comment]
Oh, I think it _should_ keep the original weekly rule in the custom rule field.. not sure if that never worked or stopped working.
However, there's no benefit of choosing "custom" over "weekly" if the user doesn't intend to enter a custom iCalendar rule - I consider this kind of an expert mode.

Do you know what the use case was for choosing a custom rule?

**Comment by brnsolikyl** [comment]
The case was that we had decided that a series of pickups would change from a certain date, so I wanted to use custom to set the start date.

**Comment by tiltec** [comment]
Good to know! It would also be possible to have start/end dates for the weekly setting, if that's something people frequently used.
