### ISSUE TITLE
Follow-up to "offers"

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1908]
From #1799 

- [ ] should you be allowed to edit accepted/archived offers?
- [ ] add "loading massive image into canvas" indicator?
- [ ] on offer detail page when there is no offer it just shows loader
- [x] pagination (infinite scroll, trigger load more, etc)
- [ ] multicroppa should have "cursor: pointer" on mouse hover
- [x] you get email notified about your own offer https://github.com/yunity/karrot-backend/pull/883
- [x] cannot access the conversation you were part of after the offer gets accepted by the owner https://github.com/yunity/karrot-backend/pull/886
- [x] remove concept of "accepting" offers - marking as archived is sufficient (see [forum thread](https://community.foodsaving.world/t/new-feature-available-offers/357/17))
- [ ] show generic "this offer is not available" when it cannot be found (see [forum thread](https://community.foodsaving.world/t/new-feature-available-offers/357/11)) - this is either the case of "id does not exist" or "offer is not visible to you"

**Comment by tiltec** [comment]
In the app, choosing a picture directly opens the gallery. It would be nice if it would allow to take a picture from the camera. (That's the same for all `Croppa` elements.)

**Comment by brnsolikyl** [comment]
Just tested on production and one issue I noticed is that I get an e-mail notification for an offer that I created.

**Comment by nicksellen** [comment]
Yes, I noticed this too actually when fixing https://github.com/yunity/karrot-backend/pull/878 - but decided to leave it for another fix. Will fix it :)

**Comment by nicksellen** [comment]
I encountered the issue me and @tiltec spoke of at some point - if you're in an offer conversation for somebody elses offer, then they accept/archive it, you can no longer access that conversation (but you still get the conversation notifications). Maybe we can do the permission check to also include offers that you are part of the conversation for, a bit fiddly, but maybe ok....

**Comment by brnsolikyl** [comment]
Maybe it would be nice to have the possibility of creating an offer without the need to upload a picture? Then a default image would need to be in place, maybe the gift icon.

The use case is to make it easier for people to put requests there. Also I suggested a friend to use Offers to keep an update list of things they need at the Bike Kitchen.

**Comment by tiltec** [comment]
This seems fine for now, only minor points left in here -> closing.
