### ISSUE TITLE
Add create group button

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#1940]
I think the time is right for making the group create button :)

I think it could go on the groupPreview page (https://karrot.world/#/groupPreview) on the same line as the "Which group do you want to join?". Something like this:

![createanewgroup](https://user-images.githubusercontent.com/31616/70437123-2f073800-1a8b-11ea-9e5e-5058c71b521e.png)

I think ideally the create a group form would have more context, maybe a multi-page stepper with some explanatory text to start with, and suggestion to join the community forum, etc... but also OK to leave that off for now.

**Comment by tiltec** [comment]
Done in #1942
