### ISSUE TITLE
Write a description of Karrot to the main page (or redesign it?)

### ISSUE THREAD

**Issue by brnsolikyl** [yunity/karrot-frontend#1944]
Anyone visiting karrot.world (if not logged in already) will land on a page where they can see the active groups and a world map with the groups' location. For people who have not been introduced to Karrot before this first page can be very unclear. There might be a bunch of questions: "What is Karrot about?", "how does it work?", "what are these groups?", "how is it useful for me?".

I think usability would improve if people had a clearer idea and the right expectations, and it would be more likely that people would adopt Karrot. There is, at the very least, a description missing, but probably we would need to redesign the landing page (or add more pages?). What are the ideas out there? Here are some thoughts:

* add a quick description (come up with a slogan/motto?) together with the logo
* maybe add a top-menu to reach other pages with more detailed information (About or Features, Vision, what else?).
* Question about branding: are we sticking to foodsaving or should we have a more general description, vision and target groups, about a tool to help organize people to take action in saving and sharing stuff?

More thoughts, ideas or questions are welcome! We could also discuss this at the next meeting.

**Comment by tiltec** [comment]
Should have it as site customization for karrot.world or hardcoded for all Karrot instances? There are not many instances right now that I know of (karrot.world, app.foodsharing.tw and dev.karrot.world), we could simplify the implementation and have it hardcoded. But that will also make hosting other instances harder, something I would actually like to make simpler to prevent a concentration of power.

**Comment by nicksellen** [comment]
On our weekly call we discussed this, and one simple way to move forward is to add two markdown bits of text:
1. a shortish block that can be displayed on the[group preview page](https://karrot.world/#/groupPreview) - logged out and maybe also logged in
2. a page-length thing that will be shown at `/about` (or similar)

Both should (probably) be defined per instance, therefore the content should be part of the deployment config, not the code.

**Comment by brnsolikyl** [comment]
A few suggestions for 1 (as per the above) of a brief description or motto, just below the name and logo of Karrot:
"save and share resources as self-organised groups"
"organise locally and share common goods"
"grassroots sharing and organising"
"helps your group to save and share anything where you live"
"get together with others to save and share resources"

I'm sure we'll come up with more ideas and combinations of ideas

**Comment by tiltec** [comment]
This actually seems done.
