### ISSUE TITLE
Warning before signing up to pickups on the same time

### ISSUE THREAD

**Issue by brnsolikyl** [yunity/karrot-frontend#1957]
Here's the actual case: when we changed the pickup time for two places so that they'd happen simultaneously, some people did not realized that and signed up for both. Since a person cannot be in two different places at the same time, it would be good to have a pop-up message, or a warning of some kind, about conflicting times and asking the person to confirm before joining the pickup.

I believe the rule would be simple for when to display the message when pickups have a defined start and end time, for example, in case a person is signed up to do a pickup from 15:00 to 16:00 and signs up for another pickup at 15:40 to to 16:20.

For pickups with undefined end time it would be good to consider them lasting half an hour (arbitrary definition, maybe more or less?) in order to display the message. For example, if someone has a pickup from 14:00 to 15:00 and signs up for another pickup at 13:45, the message would be displayed.

**Comment by tiltec** [comment]
Seems easily possible, we have all pickups loaded in the frontend (but something that we should actually get rid of for possible performance improvements -> #1914).
