### ISSUE TITLE
Number of replies in thread is indicated wrongly

### ISSUE THREAD

**Issue by Schnegel** [yunity/karrot-frontend#1968]
The number of replies represents the initial message + the replies.
Instead it has to indicate only the number of replies.
Also the authors profile picture is shown amongst the answering users, even if s\*he didn't reply to his\*her own post.

**Comment by tiltec** [comment]
I just checked it, the number of replies is technically fine. But there might be a UX bug. We started to group messages from same author, so it looks like it's just one message - whereas it's actually two. I wonder if/how we should solve this problem...

For the second one, have a look at #1969
