### ISSUE TITLE
Refine thread participants/subscribers

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#1969]
We currently treat thread participants and subscribers the same, whereas in reality they can differ:
- the original author is automatically a subscriber, but not a participant (also see #1968)
- after somebody left the group, they are still a participant but not a subscriber

We could do those changes:
- API: replace thread participants with `users` - those are people who actually wrote replies and keep them in order of first participation. This list could be generated on demand (i.e. not kept in database)
- Database: remove users from ThreadParticipants when they should not get notifications

**Comment by jasmlau** [comment]
@allibail and I would like to claim this issue
