### ISSUE TITLE
Have 'about Karrot' accessible without login

### ISSUE THREAD

**Issue by DougInAMug** [yunity/karrot-frontend#1983]
Without logging in, you cannot read any info about Karrot, find a link to the codebase, etc.

Slightly related to #1813

**Comment by brnsolikyl** [comment]
Hey Doug!
Agreed, we've talked about it during the Karrot weekend and I came up with a proposal here:
https://github.com/yunity/karrot-frontend/pull/1971

You're welcome to join the discussion if you have any feedback!

**Comment by tiltec** [comment]
Now we have the landing page for logged-out users and the about page for logged-in users. Maybe that's sufficient?

**Comment by nicksellen** [comment]
Yup, given this issue is about logged _out_ users, I think we addressed this.
