### ISSUE TITLE
Docker instruction setup - invalid interpolation format

### ISSUE THREAD

**Issue by ctiller15** [yunity/karrot-frontend#2006]
Actually this seems to be at least two different things.

- I have yet to work with docker. I'm pretty much flying blind. If someone with more knowledge is aware of a better source, feel free to point me in that general direction.

## Problem statement:
The instructions for the docker setup, as they are, do not seem to produce any desired results. I have run into two errors so far in the setup. For the `docker-compose` setup, I get an invalid interpolation format error, and for the `docker build` setup, I get a `UnicodeDecodeError`.

## Machine details:
Running Ubuntu 18.04 with lightdm as the display manager. I have not tested this on windows or macos.

## Repro steps(1):

1: Over in https://github.com/yunity/karrot-docker view the following instructions:
```
git clone https://github.com/yunity/karrot-docker.git
cd karrot-docker
git clone https://github.com/yunity/karrot-frontend.git
git clone https://github.com/yunity/karrot-backend.git
docker-compose up -d
```
2: Observe that upon docker-compose up -d running, you receive the following:
`ERROR: Invalid interpolation format for "environment" option in service "frontend": "${TERM:-}"`

This occurs with both ssh and https. No difference was encountered.

## Repro steps(2):
1: Clone the `karrot-backend` repo, and inside of the directory run the following:
`docker build -t backend .`

It proceeds until step 5, and then I receive the following error message:

```
Obtaining django-anymail from git+https://github.com/tiltec/django-anymail@189395d#egg=django-anymail (from -r /requirements.txt (line 7))
  Cloning https://github.com/tiltec/django-anymail (to revision 189395d) to /env/src/django-anymail
  Running command git clone -q https://github.com/tiltec/django-anymail /env/src/django-anymail
  WARNING: Did not find branch or tag '189395d', assuming revision or ref.
  Running command git checkout -q 189395d
Obtaining django-influxdb-metrics from git+https://github.com/tiltec/django-influxdb-metrics@163730a#egg=django-influxdb-metrics (from -r /requirements.txt (line 8))
  Cloning https://github.com/tiltec/django-influxdb-metrics (to revision 163730a) to /env/src/django-influxdb-metrics
  Running command git clone -q https://github.com/tiltec/django-influxdb-metrics /env/src/django-influxdb-metrics
  WARNING: Did not find branch or tag '163730a', assuming revision or ref.
  Running command git checkout -q 163730a
Obtaining django-jinja from git+https://github.com/tiltec/django-jinja@d25d07c#egg=django-jinja (from -r /requirements.txt (line 9))
  Cloning https://github.com/tiltec/django-jinja (to revision d25d07c) to /env/src/django-jinja
  Running command git clone -q https://github.com/tiltec/django-jinja /env/src/django-jinja
  WARNING: Did not find branch or tag 'd25d07c', assuming revision or ref.
  Running command git checkout -q d25d07c
Obtaining django-rest-swagger from git+https://github.com/tiltec/django-rest-swagger@d15dd9a#egg=django-rest-swagger (from -r /requirements.txt (line 10))
  Cloning https://github.com/tiltec/django-rest-swagger (to revision d15dd9a) to /env/src/django-rest-swagger
  Running command git clone -q https://github.com/tiltec/django-rest-swagger /env/src/django-rest-swagger
  WARNING: Did not find branch or tag 'd15dd9a', assuming revision or ref.
  Running command git checkout -q d15dd9a
Obtaining talon from git+https://github.com/tiltec/talon@80886cd#egg=talon (from -r /requirements.txt (line 11))
  Cloning https://github.com/tiltec/talon (to revision 80886cd) to /env/src/talon
  Running command git clone -q https://github.com/tiltec/talon /env/src/talon
  WARNING: Did not find branch or tag '80886cd', assuming revision or ref.
  Running command git checkout -q 80886cd
    ERROR: Command errored out with exit status 1:
     command: /env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/env/src/talon/setup.py'"'"'; __file__='"'"'/env/src/talon/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info
         cwd: /env/src/talon/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/env/src/talon/setup.py", line 9, in <module>
        long_description=open("README.rst").read(),
      File "/env/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 475: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
The command '/bin/sh -c rm -rf /env; virtualenv -p /usr/bin/python3 /env; bash -c 'source /env/bin/activate; pip install -r /requirements.txt'' returned a non-zero code: 1

```

## What I expect
I expect the setup instructions to not error. It seems like there is either some issue on my machine, or some strange edge-case unaccounted for.

**Comment by nicksellen** [comment]
Hey! Thanks for reporting the issue. Not so many people are using the docker setup so I'm not surprised if there are issues there.

For the first issue though, the interpolation error, I have a feeling this may be because you are running an older version of docker compose.

There are installation instructions at https://docs.docker.com/compose/install/ for how to install the lastest one. I suspect the one in your package manager is too old. 

If you try that first and see how it goes. I'm not sure about the second error, it doesn't seem related to the docker-compose version.

**Comment by ctiller15** [comment]
Huzzah! That seems to at least get me past that step.

For those who may be wondering, what solved it was directly from those linked instructions. (With some modification for my exact circumstances):
In linux:
`sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose`

`sudo chmod +x /usr/local/bin/docker-compose`

`sudo rm -rf /usr/bin/docker-compose`

`sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose`

`docker-compose --version`

And that's it!

I'll go ahead and create a PR updating the `karrot-docker` instructions with a link to the docker compose installation instructions. I naively just installed it with `sudo apt-get install docker-compose` which didn't seem to do the trick.

Thanks for the assist!

**Comment by ctiller15** [comment]
Pull request created: https://github.com/yunity/karrot-docker/pull/5
