### ISSUE TITLE
Run karrot on python3.6 with a maria/mysql db?

### ISSUE THREAD

**Issue by inktrap** [yunity/karrot-frontend#2012]
Hi everyone!

The requirements for karrot are python3.7 and postgresql. I want to run carrot on my favorite hoster uberspace, however they only have python3.6 and mariadb/mysql at the moment. Since Django has an ORM and the differences from 3.6 to 3.7 are not that huge, … i wondered how much work it would be to make it work.

Opinions about this?

**Comment by tiltec** [comment]
We use some Postgres-only features, I think. For example, date range fields might not be supported by Django for MySQL. But I didn't try it out.

**Comment by tiltec** [comment]
Python 3.6. might be fine, but we directly migrated from 3.5 to 3.7 because that's what latest Debian stable supports.

**Comment by inktrap** [comment]
There are some [https://docs.djangoproject.com/en/dev/ref/contrib/postgres/fields/](Postgres-only fields):

 - ArrayField
 - CIText fields
 - HStoreField
 - JSONField
 - IntegerRangeField
 - BigIntegerRangeField
 - DecimalRangeField
 - DateTimeRangeField
 - DateRangeField

**Comment by inktrap** [comment]
Soooo … I guess I have to find a different hoster or I'll ask them when Postgres will be available. I don't think it is realistic to work around this …

**Comment by nicksellen** [comment]
Another option would be a docker-based setup if that's available to you.

Also, what is your use-case for hosting it if I may ask? I'd love to support other people hosting karrot instances, and I can imagine you may run into some road blocks along the way.

(I recognise your name from fsdev, so I think you're already in the yunity slack, so can also ask questions there if you want #karrot-dev)

**Comment by inktrap** [comment]
Hi Nick!

I'll join #karrot-dev and explain my use case there.

I'll leave this open because it would be a good thing to document my setup-journey on shared hosting, so perhaps a setup-howto could be part of the karrot-docs in the (near?) future.

**Comment by inktrap** [comment]
Also I am going to leave this here: <https://docs.python.org/3/whatsnew/3.7.html#porting-to-python-3-7>

**Comment by inktrap** [comment]
Karrot runs on python3.6 and I installed postgresql.
