### ISSUE TITLE
Make notifications for conflict resolutions enabled by default

### ISSUE THREAD

**Issue by brnsolikyl** [yunity/karrot-frontend#2043]
Feedback from Warsaw group (also Solikyl at another occasion) that there should be e-mail and push notifications when people start new conflict resolution processes.

See: https://community.foodsaving.world/t/conflict-resolution-with-possibility-to-remove-user-from-group/201/18?u=bruno

The suggestion is to make them opt-out instead of opt-in.

**Comment by nicksellen** [comment]
There is one setting the user can set for each group they are in:

![issuenotifications](https://user-images.githubusercontent.com/31616/81397261-3d837980-9127-11ea-89b0-b01814e76c52.png)

If this is enabled, when a new issue is created, for those users with it enabled it will:
1. send them an email telling them about the new issue
2. subscribe them to notifications for the issue chat

There is no push notification for 1, but 2 uses the normal notification mechanism for chats/conversations which includes push.

For now, I will just focus on defaulting that checkbox to enabled. And maybe we should enabled it for all existing users too?
