### ISSUE TITLE
Create offers without a picture

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#2067]
(extracted from https://github.com/yunity/karrot-frontend/issues/1908)

@brnsolikyl said:

> Maybe it would be nice to have the possibility of creating an offer without the need to upload a picture? Then a default image would need to be in place, maybe the gift icon.
>
> The use case is to make it easier for people to put requests there. Also I suggested a friend to use Offers to keep an update list of things they need at the Bike Kitchen

**Comment by brnsolikyl** [comment]
Got the following comment in my group:

> Please remove the requirement of a picture for putting up offers! I've been sitting one hour to send a picture to the computer I'm using. [...] A picture is definitely not relevant if you write a description

**Comment by nicksellen** [comment]
Yup! Sounds good. Might be able to get it in quite soon....
