### ISSUE TITLE
Translate date-fns and Quasar into Luxembourgish and include them

### ISSUE THREAD

**Issue by dwaxweiler** [yunity/karrot-frontend#2156]
When I switch the language to Luxembourgish, the German locale is used for date formatting in the following pages:
- Wall
- Feedback
- Members
- History
- Issues
- Place: pickups, wall, feedback, history

The Luxembourgish locale is used on the following pages:
- Pickups
- Applications
- Place: manage pickups

Both lists are non-exhaustive; For instance, I have not checked the offer feature.

I assume that a third-party library is used for date formatting, but I have not checked which one.

**Comment by nicksellen** [comment]
Indeed! We use German there, as the library is not translated into Luxembourgish.
- [here is](https://github.com/yunity/karrot-frontend/blob/dcdc61872135ccab58fcf8089a9c3a1395657e3e/src/locales/index.js#L89) the bit in our code where we make it use German
- the date library we use is called [**date-fns**](https://date-fns.org/) (list of languages is on the front page) and it has a [nice guide](https://date-fns.org/v2.15.0/docs/I18n-Contribution-Guide) for adding another language

Also, our UI library (Quasar) also has a language selection, and they also don't have Lëtzebuergesch so we use German there too (they have [these languages](https://github.com/quasarframework/quasar/tree/dev/ui/lang) available)... but probably what you're seeing is from date-fns.

We could collaborate to get Lëtzebuergesch added to date-fns if you're up for it?

**Comment by dwaxweiler** [comment]
Thanks for pointing me to the wiring and the libraries used! German as an alternative has been a wise choice as both languages are quite close. This is also the reason why it looks correct on some pages.

Sure, I am up for translating both libraries. I will look into this later today.

**Comment by dwaxweiler** [comment]
I have created a PR for the date-fns library: https://github.com/date-fns/date-fns/pull/1900

**Comment by nicksellen** [comment]
Amazing! Good job :+1: 

I had a look at [another recent language addition](https://github.com/date-fns/date-fns/pull/1832) to see how long it might take until it gets merged - that one was 9 days until merged to master. I guess it'll then need to have a new release from that too. Let's see how it goes.

**Comment by dwaxweiler** [comment]
Thanks! I will let you know about its progress and will translate Quasar in the next days too. I suggest to leave this issue open until we have included the updated versions of both libraries.

**Comment by dwaxweiler** [comment]
@nicksellen Your guess of 9 days was correct! My PR on date-fns has been merged yesterday, accompanied with a new instant release. I have created another PR here just now to change the config.

**Comment by nicksellen** [comment]
Nice! I'll do a production deployment shortly to get it live...

**Comment by dwaxweiler** [comment]
> Nice! I'll do a production deployment shortly to get it live...

To https://dev.karrot.world/ ?

**Comment by nicksellen** [comment]
Deployment to https://dev.karrot.world happens automatically after it's merged to master, production deployment is to https://karrot.world and has a confirmation button to press, which I pressed :) ... so it should all be live and active on both sites now.

**Comment by dwaxweiler** [comment]
Yeah, it is looking good! Thank you to both of you @tiltec and @nicksellen for reviewing and deploying this so fast!
