### ISSUE TITLE
Typed text disappear when reloading

### ISSUE THREAD

**Issue by nastybyte** [yunity/karrot-frontend#2192]
When i start typing a message to someone or on a wall on my phone (lineageos16.0 with microg, no gsf) and the page is reloaded (happens ie when accidentally swiping down, or if the screen turns off due to inactivity) the typed text disappears. Same thing happens if i press reload in a browser window on the computer but that's much less likely to happen by accident.

**Comment by tiltec** [comment]
Hi @nastybyte, thanks for reporting this! I also got hit by this multiple times, so definitely can confirm. Hopefully it can be fixed soon!

**Comment by nicksellen** [comment]
Possibly related to https://github.com/yunity/karrot-frontend/pull/1891
