### ISSUE TITLE
Service worker caching / update / etc

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#2209]
I don't think we have our service worker / caching / deployment setup optimally yet.

We have a lot more service worker behaviour now, which precaches all the webpack resources in the service worker.

But there are quite a lot of complexities around service worker caching an updating:
- service workers update automatically in general (see https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#updates)
- we use the `skipWaiting()` and `clientsClaim()` to _immediately_ switch pages to using the latest version, but this comes with caveats that fit our use case, and I think we encounter (see https://developers.google.com/web/tools/workbox/modules/workbox-core#skip_waiting_and_clients_claim)

It also has a tip to periodically check for updates in the background if the automatic methods are unlikely to be called (see https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#manual_updates).

## What I think can happen now

After deployment:
- user visits karrot.world
- they have index.html and all the resources in the cache, but for the old version
- it starts to load the old version
- the browser checks for updated service worker and finds one
- the service worker loads and because of `skipWaiting()` and `clientsClaim()` it immediately kicks out the old service worker and the old cache
- the browser now has a mix of old and new resources and we are doomed to fail at some point, it makes no sense to have this mix of resources

The cautious approach, would be to remove `skipWaiting()` and `clientsClaim()` and this means the old site will stay active until all tabs are closed, on the next load the new service worker with it's new precached selection of files will be active. 

https://developers.google.com/web/tools/workbox/modules/workbox-core#skip_waiting_and_clients_claim and the linked question https://stackoverflow.com/a/51716150 explain a bit more.

However, we also have our own update logic to fit into the picture. This checks if the commit hash at https://karrot.world/about.json matches the one that was compiled into the code at build time. It shows a banner and when the user clicks it we do `window.location.reload()`. Currently though I _think_ this might be problematic, as the service worker might not have been reloaded at that point (no triggers for the automatic update), the reload will trigger the automatic update, but because of the first issue, the resultant site will probably be a mix of cached old site, and updated service worker site, and then break. Another refresh should fix it.

My initial idea was to just remove index.html from the service worker cache, so at least whenever you visit the page it should fetch all the latest resources, the service worker would then update in the background too, but nothing should reference the old parts of the app that are briefly active (in the gap between `/` load and the new service worker becoming active), as all the resources are referenced from the index.html page, which is fresh. Maybe this is worth trying for now...

But, perhaps we should just heed the warnings ([here](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#skip_the_waiting_phase) and the one I linked above), and not do `skipWaiting()/clientsClaim()` and rely on the base behaviour to always wait for the _next_ load for things to become active.

We could also do the periodic manual background updates (see https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#manual_updates), so long opened pages would get the updates in the background (but would still not be active until close/reopen of all the tabs). I _think_ it would behave such that if there were two tabs, you'd see the blue banner, press reload, but having one of the tabs still open would keep the old service worker alive, so it would keep showing the blue banner.... confusing!

Another update "recipe" is given here (https://developers.google.com/web/tools/workbox/guides/advanced-recipes#offer_a_page_reload_for_users) to detect if the next service worker is waiting in line. Maybe that's a nice option.

... and a totally different direction, if we just kept the old webpack assets around (e.g. doing rsync without `--delete` for deployment), then even though the same would occur, and the service worker cache would get emptied out, the next requests for those old js files could still be fetched from the server... and/or handle the asset fetching error somewhere and reload the page...

Sorry it's a bit long stream of thoughts!

**Comment by larzon83** [comment]
+1 for offering a notification to the user saying update available. Click >>refresh<<

**Comment by nicksellen** [comment]
We actually have the UI banner bit already, I described it a bit above there:

> However, we also have our own update logic to fit into the picture. This checks if the commit hash at https://karrot.world/about.json matches the one that was compiled into the code at build time. It shows a banner and when the user clicks it we do window.location.reload().

I guess the question here is how to make the behaviour around the existing banner to behave correctly in all cases. Although I _think_/hope the worst of it (pressing reload doesn't actually get the latest version because of the service worker cache) was resolved with the PR listed above (https://github.com/yunity/karrot-frontend/pull/2210).

... but there could be some improvements, at the moment the banner only shows when you visit the page afresh, not if the update happens in the backend.

Additionally, I'm not even convinced we should cache all the assets with the service worker as we do. It basically downloads ALL the assets for the site when you first visit, which kind of defeats some of the point of all this webpack splitting anyway...

More rambling there!

**Comment by larzon83** [comment]
> Another update "recipe" is given here (https://developers.google.com/web/tools/workbox/guides/advanced-recipes#offer_a_page_reload_for_users) to detect if the next service worker is waiting in line. Maybe that's a nice option

My gut feeling is to build around this serviceworker-option and not use a custom banner. But I'm not deep into the project and don't know how the custom banner works atm. If I have time I'll look into it. But I don't know if it will be helpful :)

**Comment by nicksellen** [comment]
> My gut feeling is to build around this serviceworker-option and not use a custom banner. But I'm not deep into the project and don't know how the custom banner works atm. If I have time I'll look into it. But I don't know if it will be helpful :)

From a quick flick through the article, we would still need to implement our own banner (it calls `createUIPrompt` which is defined by the user/application).

I think this is a better approach than what we have at the moment though, as it's building on top of the browsers underlying mechanism to update the service worker cache.

If you feel like implementing the steps described in that article, I would be happy! Needs thinking how it works on the mobile app too (our cordova one, which is needs to be disabled for, as updates are via play store, and our PWA, which maybe updates automatically?? I don't really know - I doubt many people have installed via that method though)
