### ISSUE TITLE
Request to add "since the beginning" to statistics time period

### ISSUE THREAD

**Issue by dwaxweiler** [yunity/karrot-frontend#2218]
Would it be possible to add the time period "since the beginning" to the selection menu on the statistics page please?
![Screenshot_2020-10-29 Karrot](https://user-images.githubusercontent.com/12501775/97555838-eaed9080-19d8-11eb-84d5-cbe792f83dcc.png)
In our group, we use the total number of kg of food rescued as an indicator. While we know it is just based on guesses, it tells a nice story of the progress. :)

**Comment by nicksellen** [comment]
We left it out with the principle of "redemption" or similar, so if it's being used to find out who the people are that do too many pickups and to judge them, then this has a time limit, and after 6 months this data about them is no longer able to be viewed.

For your case though, I can see that the total weight across all users in aggregate would be useful, is that what you're asking for? If so, isn't that info also available on the feedback page for a place?

But I am not opposed to adding more views int he statistics if we can somehow preserve the "redemption" value (which, by the way, also applies to the stats for people leaving activities, if that activity was later fulfilled anyway, we don't count that as left, e.g. somebody replaces them).

**Comment by dwaxweiler** [comment]
I understand why you have left it out. You are right; We would only use the total weight of all places of the whole group. Indeed, you find it on the place feedback page, but this has to be manually summed per place to get the total. I can think of two options:
1. Adding the time option "Since the beginning": If this is selected, no user can be selected.
2. A new paragraph with a simple graph with the time on the x axis and with the total weight on the y axis.

**Comment by nicksellen** [comment]
I like both options! 1. is simpler for now, as it doesn't require much new visual change, but I like the idea of showing graphs, helps to tell a story....

They could both be implemented in the frontend entirely at the moment (the restrictions are currently only present in the frontend...), are you interested to try and implement? :)

**Comment by nicksellen** [comment]
@dwaxweiler I implemented it! Maybe you can check how it looks to you over at https://github.com/yunity/karrot-frontend/pull/2230

**Comment by dwaxweiler** [comment]
Thanks, @nicksellen! I have kept the e-mail unanswered as I have been thinking about giving it a try; I want to learn Vue.js, so such a small feature might be a good first practical step.

**Comment by nicksellen** [comment]
Ah, I was too fast! Happy to help you make your next small feature change :)
