### ISSUE TITLE
Remove disabled pickups on applied filters on pickups page

### ISSUE THREAD

**Issue by dwaxweiler** [yunity/karrot-frontend#2271]
I suggest to remove disabled pickups when applying the filters "With free slots" and "Only empty" on the pickups page as I imagine the user is more interested in finding pickups they can actually join.

**Comment by pogopaule** [comment]
@dwaxweiler Is this what you have in mind? 
![disable](https://user-images.githubusercontent.com/576949/103487257-594d3580-4e04-11eb-84ab-2cdbcb04d7b7.gif)

**Comment by dwaxweiler** [comment]
@pogopaule Yes, this looks good!
