### ISSUE TITLE
Improve initial map location when adding a new place

### ISSUE THREAD

**Issue by wetneb** [yunity/karrot-frontend#2288]
When I add new place to a Karrot group, the initial location of the map seems to be always the same (somewhere north of Darmstadt). I need to zoom out, find the region where the group operates and zoom into it to find the exact location of the place I want to add.

It would be nice if the map view could be initialized to a location that makes sense for the group. For instance:
- the coordinates I picked up when creating the group itself, with some default zoom level. Probably quite easy to implement, but might not be optimal since it might not match the range of current places of the group so well in some cases;
- the coordinates I put down in my user profile - but that's quite hidden, I assume many people haven't set any location there;
- fit the map view to the bounding box of all existing places in that group? Probably a bit harder to implement, but could give some nice results. It looks like you are already doing it for the map of the group in the top left corner so hopefully that logic can be reused…
- let the group participants define the initial map view for the new places? Probably overkill and annoying to implement.

**Comment by larzon83** [comment]
@wetneb https://github.com/yunity/karrot-frontend/pull/2293 implements your first idea. What do you think?

**Comment by wetneb** [comment]
Thank you both, that's wonderful!
