### ISSUE TITLE
Redirect to review page of place

### ISSUE THREAD

**Issue by dwaxweiler** [yunity/karrot-frontend#2311]
**Steps to reproduce**
1. Submit a feedback.

**What happens**
You are redirected to the page with all the feedback entries.

**What should happen**
You are redirected to the page with the feedback entries of the corresponding place. This would make it easier to spot your submitted review. Alternatively or additionally, it could be scrolled to or highlighted for a moment to further improve its visibility.

**Comment by esharb** [comment]
Hi, I'm a first-time contributor and would love to work on this issue! Do let me know if it's possible. Thank you!

**Comment by tiltec** [comment]
I had a look at this yesterday evening and made this PR: https://github.com/yunity/karrot-frontend/pull/2417

**Comment by tiltec** [comment]
@esharb - sorry for not coming back to you earlier! In case you're still around, maybe you're interested in https://github.com/yunity/karrot-frontend/issues/2318?
