### ISSUE TITLE
ics export of activities

### ISSUE THREAD

**Issue by amengsk** [yunity/karrot-frontend#2320]
when I sign up for a pickup, I want to import the event in my calendar.
the ics format (aka ical) is a well known format for this.
activities should have some export button to generate a ics file.
let me know if you want a pull request for that.

**Comment by nicksellen** [comment]
Thanks for the work so far, looks close to being ready :superhero: - out of interest are you part of the group in Warsaw? https://karrot.world/#/groupPreview/39
