### ISSUE TITLE
Dates in activity series are not created anymore

### ISSUE THREAD

**Issue by dwaxweiler** [yunity/karrot-frontend#2323]
Since last update 9.2.0, no new dates are added for recurring activities.

Tom has raised this issue in a [forum post](https://community.foodsaving.world/t/issue-new-pickups-are-not-created-in-karrot/463/7) first. Additionally, some people in my group Foodsharing Luxembourg have noticed it in the second half of last week.

**Current manual work-around:** Change weeks to create activities in advance to a smaller value, save, change it back to the original value and save; The missing activities are created.

**Comment by brnsolikyl** [comment]
Yep, got a similar complaint from one group.

**Comment by nicksellen** [comment]
Hopefully just fixed it, see https://community.foodsaving.world/t/issue-new-pickups-are-not-created-in-karrot/463/10 :)

**Comment by dwaxweiler** [comment]
Yes, it works again. Thanks for your quick reaction @nicksellen!
