### ISSUE TITLE
Weight Feedback for Distributions and Events

### ISSUE THREAD

**Issue by pogopaule** [yunity/karrot-frontend#2326]
Sylvia from EfA asked if it is possible to also add the weight feedback option to the activity types distribution and event.

**Comment by brnsolikyl** [comment]
Yes, it's already available on production!
On the page to edit activity types
![image](https://user-images.githubusercontent.com/25367304/113578057-85a26900-9622-11eb-882d-473d10e5be16.png)
Toggle "ask for weight"

**Comment by pogopaule** [comment]
Perfect, thanks! I'll tell her.
