### ISSUE TITLE
ics subscriptions

### ISSUE THREAD

**Issue by amengsk** [yunity/karrot-frontend#2334]
followup to #2320

as a user i want to sync my calendar app with karrot. for instance:
- subscribe to the calendar of all activities i joined
- subscribe to the calendar of all activities happening in a place
- subscribe to the calandar of all activities happening in a group
- maybe other things?

the current ics export is not enough for this - i dont want to have to import every single activity manually.

i see 2 ways:
- expose ics endpoints which do ics rendering of the lists. we talked about it in the ics pr https://github.com/yunity/karrot-backend/pull/1125#discussion_r606646864. its simple to do but maybe a bit limited: when clients sync with the calendar they download the whole thing (can be heavy).
- expose caldav endpoints instead. that makes sync more efficient (with filtering). and maybe there could even be some write support (change the activity description from the caldav client, or join the activity…). but the caldav protocol looks like a big mess and probably doesnt fit very naturally in drf. there is https://github.com/kyokenn/djradicale which exposes a caldav server from any django models but not sure its maintained. if we implement it ourselves, we probably aim for only the features that are actually used by clients (but thats sketchy guesswork)

for auth, in both cases we need to use some standard http auth. most clients probably support http digest or http basic auth.
- digest auth is secure even if used over http, but difficult to implement without changing the way user passwords are stored (so messing up with the user model and forcing people to reset their password)
- basic auth is arguably okay as long as https is used, and simple to implement in drf
but thats only if we expect people to use their normal karrot password to access the ics feeds, i could also imagine generating a special password (~api token) for that (to avoid it being leaked by the ics client).

if you ask me i'd probably go for ics export, http basic auth and no special password. probably efficient, user friendly and secure enough. as a workaround for bandwidth issues we could hide events older than some threshold in the ics export.

**Comment by amengsk** [comment]
ok friends i had a go at this, it seems doable but i am unsure about a few things

first here is a sketch of what the ui could be like:
![image](https://user-images.githubusercontent.com/81293599/115293993-50386800-a158-11eb-97f9-30d0dc07d8e6.png)

in any activity list you could want to download it as an ics file, or copy the url of that ics file to subscribe to it from some client. i think its nice to have two different buttons for that: one that just links to the ics (for one-off download), another one that displays the url (and helps you copy it in your clipboard) so you can easily add it to your client. then in your client you are prompted for your user/pass (http basic auth). maybe the download option is actually overkill / confusing and we should only keep the subscription?

the activity lists can be filtered client-side but i am not sure whether this filtering should be respected by the ics export/subscription. it could make sense for the activity type (i just want to subscribe to all pickups and nothing else), but not really convinced about the participant status. but if we keep the download option then it could be confusing to have a difference between what is shown in the ui and what is included in the export. i think its not really a problem for the subscription.

also i am not sure what is the best practice to pass the url of the ics endpoint (with the relevant server-side filters) to the vue component (ActivityList). at the moment only the activities themselves are passed and the calls to the backend are done far away in the state management layer. i can just pass all required props down the components and reconstruct the url in activitylist but maybe you guys know a better way?

**Comment by nicksellen** [comment]
This just got to deployed to production, and it's great! Just tried it out.

Using ICSx5 on Android it added my activities to my calendar, here shown using etar (including the attendees!):

![Screenshot_20211108-170841.png](https://user-images.githubusercontent.com/31616/140787237-35762af9-d821-4850-ae39-c0d337b3a88a.png)

One thing I did notice is that the calendar title got set to the URL path, I guess because it's not set in the code:

![Screenshot_20211108-171002.png](https://user-images.githubusercontent.com/31616/140787345-64a46fb8-0028-4c66-862d-65743d0422f4.png)

So, thanks @amengsk :+1
