### ISSUE TITLE
Feedback weight slider limits

### ISSUE THREAD

**Issue by brnsolikyl** [yunity/karrot-frontend#2338]
Currently the slider limit is on 70 kg as the screenshot shows:
![image](https://user-images.githubusercontent.com/25367304/114223033-a09d1200-996f-11eb-9219-cf3f3e25d170.png)

**Problem**

I heard this first-hand from a conversation between two users. One wanted to enter a higher value than 70 kg by using the slider but thought it was not possible and believed it was a hard limit. The other explained then that a higher value could be entered at the weight field next to it.

**Any solutions?**

Maybe a small hint could pop up when you slide to the limit indicating somehow that the value can be entered manually? Any ideas?

**Comment by larzon83** [comment]
Simplest solution: bump the max value. Maybe 150?

**Comment by brnsolikyl** [comment]
Believe it or not in some cases it might still not be enough :smile: 
But sure it will make it less likely to happen

**Comment by larzon83** [comment]
Oh wow. Is it line one of 1000 cases or one of 10ish? 😄 
If it's the latter, then we should think of a better solution like the hint you mentioned.
Maybe instead of a hint (describing that you can edit the input directly) a button appears labeled "add even more". After clicking that, we set the max value to eg 150. If the user scrolls to the end of that too, it goes to 500.
Just an idea.

**Comment by brnsolikyl** [comment]
> Oh wow. Is it line one of 1000 cases or one of 10ish? smile

In my group it can be easily 10% of the cases or even more than that, but I'm pretty sure it's much less globally. I wonder if we could check this at grafana.karrot.world...

> Maybe instead of a hint (describing that you can edit the input directly) a button appears labeled "add even more". After clicking that, we set the max value to eg 150. If the user scrolls to the end of that too, it goes to 500.

That would work too. But then we'd probably need to add cars and trucks on the little drawings to be representative of the weight :laughing:

**Comment by larzon83** [comment]
Freiburg Group is taking this

**Comment by larzon83** [comment]
PR is here: https://github.com/yunity/karrot-frontend/pull/2348
Tell us what you think :)
