### ISSUE TITLE
Revoke Trust

### ISSUE THREAD

**Issue by pogopaule** [yunity/karrot-frontend#2341]
A user from EfA asked to add the possibility to revoke trust that has been given.
According to the user trust is sometimes given too hasty. In that case it can't be revoked.

**Comment by brnsolikyl** [comment]
Yes, this has been discussed before. Actually there's a [looong thread on the community forum](https://community.foodsaving.world/t/discussion-karrot-trust-system-and-user-levels/95), with some good feedback after the trust feature was implemented.

No need to read it all but skimming through it I could identify a few ideas:
- possibility to revoke trust
- trust expires automatically after some time, or it expires after some time of inactivity
- increase the threshold for gaining editing permissions (too low for some groups). Maybe make it a group setting
- minimum time of being part of a group to get editing rights, regardless of trust

I think revoking trust is the simplest and most straight-forward suggestion

There's also another discussion related to developing further the trust levels: https://community.foodsaving.world/t/applicant-trial-pickup-proposal/575/ . We thought this could be an interesting area for the Freiburg group to work on if that's interesting for you ;)

**Comment by pogopaule** [comment]
I will start to give this a shot.
My idea is to simply add an inverse operation to giving trust.

**Comment by pogopaule** [comment]
@nicksellen or @brnsolikyl If a user has received enough trust he/she [gets more privileges](https://github.com/yunity/karrot-backend/blob/master/karrot/groups/receivers.py#L69). Should revoking trust also do the inverse here and revoke privileges if trust drops below the threshold?

**Comment by brnsolikyl** [comment]
> Should revoking trust also do the inverse here and revoke privileges if trust drops below the threshold?

In my opinion, yes, definitely!
