### ISSUE TITLE
refactored landingpage: reduce bundlesize for generated images

### ISSUE THREAD

**Issue by larzon83** [yunity/karrot-frontend#2370]
See comment here: https://github.com/yunity/karrot-frontend/pull/2340#discussion_r641460389

**Comment by nicksellen** [comment]
Aha, I found it's possible to use webpacks [`oneOf`](https://webpack.js.org/configuration/module/#ruleoneof) and  [`resourceQuery`](https://webpack.js.org/configuration/module/#ruleresourcequery) to help us.

It means in the require we can put extra param `?disableinline`, then use a `resourceQuery` to match that to the `file-loader`, and let everything else use the existing loader.

This way there is no need to write a flaky regexp to include/exclude stuff in `pages/images` (I did start down that route), and it reuses the existing loader config.

```js
const imageRule = cfg.module.rules.find(rule => rule.use.find(use => use.loader === 'url-loader' && use.options.name.startsWith('img/')))
if (imageRule) {
  const urlLoader = imageRule.use.find(use => use.loader === 'url-loader')
  const useOriginal = imageRule.use
  delete imageRule.use
  imageRule.oneOf = [
    {
      resourceQuery: /disableinline/,
      use: [
        {
          loader: 'file-loader',
          options: urlLoader.options,
        },
      ],
    },
    {
      use: useOriginal,
    },
  ]
}
```

Then when requiring stuff it can be:

```js
require(`@/base/pages/images/${dirName}/${fileName}-${width}${ext}?disableinline`)
```

Whaddya think?

**Comment by nicksellen** [comment]
I got confused for a moment, as I saw locally it loading too many images (large and small), which it wasn't doing on dev.karrot.world:

![devmode](https://user-images.githubusercontent.com/31616/121346990-a20e9a80-c91e-11eb-8a44-77c859417e8b.png)

... but seems an side effect of running in dev mode, in a local production build, with everything else the same, it seems good:

![prodmode](https://user-images.githubusercontent.com/31616/121347130-bb174b80-c91e-11eb-972e-01f4b3814f80.png)

**Comment by larzon83** [comment]
> Whaddya think?

Brilliant! 😄 

I was on the same path with the regex to only target landingpage images.

BTW: I found how to overwrite a rule. One has to use `chainWebpack ` instead of `extendWebpack`

```js
chainWebpack (chain) {
  chain.module.rule('images')
    .test(/\.(png|jpe?g|gif|svg|webp|avif)(\?.*)?$/)
    .use('url-loader')
    .loader('url-loader')
    .options({
      esModule: false,
      limit: -1,
      name: 'img/[name].[ext]',
    })
},
```

One thing about your solution. When `file-loader` is used, it gets the same options as `url-loader`. `esModule` and `name` are the same but there is no option for `limit`. `file-loader` will ignore this. But maybe it's cleaner like this?

```js
const imageRule = cfg.module.rules.find(rule => rule.use.find(use => use.loader === 'url-loader' && use.options.name.startsWith('img/')))
if (imageRule) {
  const useOriginal = imageRule.use
  const useWithDisable = imageRule.use
  useWithDisable.find(use => use.loader === 'url-loader').options.limit = -1
  delete imageRule.use
  imageRule.oneOf = [
    {
      resourceQuery: /disableinline/,
      use: useWithDisable,
    },
    {
      use: useOriginal,
    },
  ]
}
```

**Comment by larzon83** [comment]
> I got confused for a moment, as I saw locally it loading too many images (large and small), which it wasn't doing on dev.karrot.world:
> ... but seems an side effect of running in dev mode, in a local production build, with everything else the same, it seems good:

I saw that too. But only happens when you have "Disable Cache" enabled in devTools.

**Comment by nicksellen** [comment]
I did have an earlier version that removed the excess limit option, but as it didn't complain with the extra option, it seemed simpler code to leave it in.

In your version I think you've set the limit to -1 for both loaders, as it was only a shallow copy, so the options object is shared. I think.

**Comment by nicksellen** [comment]
I also if it's possible to use the webpack chain method with this approach too?

**Comment by larzon83** [comment]
> I did have an earlier version that removed the excess limit option, but as it didn't complain with the extra option, it seemed simpler code to leave it in.
> 
> In your version I think you've set the limit to -1 for both loaders, as it was only a shallow copy, so the options object is shared. I think.

Oh. Yep, you're right. Then we leave it like this.

> I also wonder if it's possible to use the webpack chain method with this approach too?

Out of curiosity or do you see a benefit in it? :)

**Comment by nicksellen** [comment]
> Out of curiosity or do you see a benefit in it? :)

It seemed the loader has a _name_ in your chain example: "images" that allows you to override it like that, instead of by filtering on the type name and options, so potentially more robust.

... and then just the thought if it's _designed_ for being able to override loaders and options, then perhaps it has a nice API for it.

But no particular benefit if those things aren't really true/easy, and a good measure of curiosity. It has it's own complexity too, having to understand it's API, as opposed to just navigating through basic js data structures.

**Comment by larzon83** [comment]
> > Out of curiosity or do you see a benefit in it? :)
> 
> It seemed the loader has a _name_ in your chain example: "images" that allows you to override it like that, instead of by filtering on the type name and options, so potentially more robust.

Ah, ok. I'll have a look later.

**Comment by larzon83** [comment]
@nicksellen got it working with chaining.
Both are readable even without knowing of the chain API.
I think I would go the chain way, as it doesn't needs filtering on type names etc.. Makes it more robust as you said.
What do you think?

```js
chainWebpack (chain) {
  const imagesRule = chain.module.rule('images')
  const imagesRuleOptions = imagesRule.uses.entries()['url-loader'].store.get('options')

  // clear all existing loaders.
  // if you don't do this, the loader below will be appended to
  // existing loaders of the rule.
  imagesRule.uses.clear()

  imagesRule
    .oneOf('disableinline')
      .resourceQuery(/disableinline/)
      .use('url-loader')
        .loader('url-loader')
        .options({ ...imagesRuleOptions, limit: -1 })
        .end()
      .end()
    .oneOf('inline') // aka default from quasar
      .use('url-loader')
        .loader('url-loader')
        .options(imagesRuleOptions)
},
```
