### ISSUE TITLE
Group not loading by default anymore

### ISSUE THREAD

**Issue by dwaxweiler** [yunity/karrot-frontend#2378]
**Steps to reproduce**
1. Make sure you are already logged in.
2. Leave the Karrot website or app. In the latter case, make sure to close the app in the background.
3. Visit Karrot via the website or via the app

**What happens**
The welcome page of Karrot is shown.

**What should happen**
The wall page of your group is shown. This has been the behaviour before version 9.3.0. I am not sure though what happened when you are member of multiple groups; Was the group shown you visited for the last time?

In our group, many people are confused by this change.

**Comment by nicksellen** [comment]
Indeed! It's actually already fixed in master, so just needs a new deployment to put it live. I think we can gather a couple of other changes and deploy in about a week. 

Thanks!

**Comment by nicksellen** [comment]
(this was the fix https://github.com/yunity/karrot-frontend/pull/2373)

**Comment by dwaxweiler** [comment]
@nicksellen Thanks for the quick reply! I should have checked the changelog first. :sweat_smile:
