### ISSUE TITLE
Some activities are not displayed

### ISSUE THREAD

**Issue by dwaxweiler** [yunity/karrot-frontend#2384]
The following issue has been observed in the Foodsharing Luxembourg group: The number of displayed upcoming one-time activities is cut at some point in the future. Example:
 
![Manage activities page](https://user-images.githubusercontent.com/12501775/121944813-60815380-cd53-11eb-8aa7-e992216aa769.png)

The Activities and Manage Activities pages do not list the event created for the 2nd of August.

![Place history](https://user-images.githubusercontent.com/12501775/121944711-3e87d100-cd53-11eb-9fec-c1ae92bbafbf.png)

It has been reported by a few members after the last update.

**Comment by tiltec** [comment]
There's a limit of 400 upcoming pickups in the code, could it be that you're just over this number? (We could just increase it until we properly implemented pagination for activities).

https://github.com/yunity/karrot-backend/blob/36818f990781c1e775e560fa43c9d616fcbd5dec/karrot/activities/api.py#L181-L187

But this didn't change with the last update...

**Comment by dwaxweiler** [comment]
@tiltec This is possible as we have many pickup cooperations now; This limit is a limit on all activities, or is not it? On the activity page, there is usually only a smaller selection displayed.

**Comment by tiltec** [comment]
I temporarily increased the activities limit from 400 to 800 for karrot.world, can you check if all are visible now? Then I would make it permanent.

**Comment by dwaxweiler** [comment]
> I temporarily increased the activities limit from 400 to 800 for karrot.world, can you check if all are visible now? Then I would make it permanent.

Yes, they are visible now. Thanks! :+1:

**Comment by nicksellen** [comment]
So many activities! Great! I guess we should add an issue for it... there, done --> https://github.com/yunity/karrot-frontend/issues/2388
