### ISSUE TITLE
Improve bundling of icon picker

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#2385]
We are including the entire icon picker with all the icon sets in our main bundle :/ This massively increases the size, beyond what is actually needed.

Two problems:
1. all icons sets bundled but we only use `fontawesome-v5`
2. they're all bundled into the main app bundle, instead of one that loads of demand (it's a very infrequently used page)

Fixes for either or both are very welcome!

![iconpickerbundle](https://user-images.githubusercontent.com/31616/122039315-7718c080-cdce-11eb-9c51-f250d1252643.png)

https://dev.karrot.world/bundlesize.html

**Comment by larzon83** [comment]
I'll have a look...
