### ISSUE TITLE
Update Readme.md and Github's about 

### ISSUE THREAD

**Issue by brnsolikyl** [yunity/karrot-frontend#2397]
After updating the landing page and the meta-description, it seems like the only thing left (is it really?) to be consistent is to update the repository's about description and Readme.md

**Comment by nicksellen** [comment]
Ah, you didn't see I already opened a PR for the readme? https://github.com/yunity/karrot-frontend/pull/2395

... And I updated the repo description this morning too, or did I miss somewhere?

**Comment by brnsolikyl** [comment]
Wow, I had my tab opened here and did not refresh it! Cool, then I'll close this issue
