### ISSUE TITLE
ics export doesn't work on mobile app

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#2400]
It tries to load the URL as a local file, which doesn't exist.

When in Cordova needs to be a full URL including domain. 

![Screenshot_20210626-154647](https://user-images.githubusercontent.com/31616/123516799-d6f84c80-d695-11eb-9836-50ffa8880d6d.png)

**Comment by amengsk** [comment]
thanks for reporting! i can take care of it
