### ISSUE TITLE
Missing Secure Only

### ISSUE THREAD

**Issue by jayant766** [yunity/karrot-frontend#2435]
Session cookie was issued by the application and does not have the secure flag set.

![Screenshot (188)](https://user-images.githubusercontent.com/73739820/130286298-00cfcfd2-7a4a-4beb-a6f1-8a492397446c.png)

**Comment by tiltec** [comment]
Thanks! Seems we need to set `SESSION_COOKIE_SAMESITE = True`: https://docs.djangoproject.com/en/3.2/ref/settings/#std:setting-SESSION_COOKIE_SECURE

**Comment by jayant766** [comment]
Yes its necessary to fix it. If I want to fix it how can I do it?
Could you please help me in fixing it.

**Comment by tiltec** [comment]
Sounds good! I think it should be enough to add `SESSION_COOKIE_SAMESITE = True` to `settings.py`, then we can merge it and check if works on dev.karrot.world.

**Comment by jayant766** [comment]
Thanks for the help. But I can't able to find settings.py. Its would be good if tell me the exact location of the file where I have to correct the code.

**Comment by tiltec** [comment]
Ah sure, it's in the backend repository! 

https://github.com/yunity/karrot-backend/blob/master/config/settings.py#L357

Adding it after the line `SESSION_COOKIE_HTTPONLY = True` seems to be good.

**Comment by jayant766** [comment]
Thanks for the help. 

I created one pull request for this issue.

**Comment by tiltec** [comment]
Thanks! I just noticed a mistake in my replies above: instead of `SESSION_COOKIE_SAMESITE`, we need `SESSION_COOKIE_SECURE`… can you change this in the PR?

**Comment by jayant766** [comment]
Oh! Okay I change it.

**Comment by tiltec** [comment]
Cool :) I merged the PR https://github.com/yunity/karrot-backend/pull/1185, can you check https://dev.karrot.world to see if it's solved?

**Comment by jayant766** [comment]
Yes, Its working.
