### ISSUE TITLE
Add HTML mail templates

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#256]
Our backend templates are text only, and SparkPost adds ugly tracking links. Would be nice to have beautiful (translatabe) HTML templates instead.

Although this is a backend task, I will track it here.

**Comment by nicksellen** [comment]
HTML that works well in mail clients is a pain compared to browser-compatible HTML, so I would recommend to use a email-specific HTML template library, e.g.:
- http://zurb.com/playground/responsive-email-templates (or is http://foundation.zurb.com/emails.html their latest thing?)
- https://www.sendwithus.com/resources/templates/oxygen (I used this before)
- https://litmus.com/community/templates (did not use, looks reasonable)
- https://htmlemail.io/ (looks reasonable too, maybe is the same as litmus stuff)

**Comment by nicksellen** [comment]
HTML templates are now enabled (via mjml). Only one is implemented yet, so more to come...
