### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#257]
Different notification mails could be useful:

- to all members of a store team when a pick-up gets created
- to all members of a store team when a pick-up approaches and needs more foodsavers (time..?)
- to the member who signed up when a pick-up approaches (e.g. 1 day in advance)
- to all members of a group when a new store gets created

Also, should there be the possibility to turn off the notifications by category? Or would that just thwart the effect of the notifications, that the whole team can be sure of the other's being informed of changes?

**Comment by tiltec** [comment]
Definitely a thing that will come. But I think the tool is usable without mail notifications, so I would wait until we have at least one group using the tool regularly.

**Comment by Sliverriver** [comment]
For Detail of notifications have a look at #363  . Also for options of x hours before pickups.

**Comment by nicco11a** [comment]
Added the concept of ntroductory pickups into the wishlist of #363.

**Comment by tiltec** [comment]
We should make the notification preferences more clear.

Users of the foodsaving tool currently get a mail
- when they create an account
- when they change their mail address
- when they want to reset their password

Following mail notifications could be implemented right now. Users should get an email
- when they have an pickup upcoming (joined the pickup and it is scheduled in x hours)
- when there is a pickup upcoming in x hours in the group that no one / not enough people joined so far

We could also compile a daily summary from the history items for each group and mail it to interested members.

@djahnie mentioned "store teams" in the first post of the issue, but store teams are not implemented in the foodsaving tool.

Later on, we can think about more notifications, e.g. when we get communication features #520 

We should also think about other notification channels than e-mail. Maybe should open a new issue about this.

**Comment by brnsolikyl** [comment]
Question: would the new pickup notifications be sent by default? IMO it's better if the user is able to opt-in or out of receiving different notifications, while some can be set as on by default.

The notification as a reminder ("you have a pickup in a x hours") is a good idea, and also the one about  pickups that nobody has joined, reminding people to join. The latter is probably better if left to be configured by the user when creating a single pickup or series of pickups. In cases where not enough people have joined, I believe notifications would be a nag: here in Gbg, for example, we do a fine job with two people, but we usually have three slots just to make it easier in case someone else wants to join.

Notifications by stores is not a current issue for our group but will definitely be in the future, when we hopefully scale the movement, by having more cooperating stores. A foodsaver in one side of the town would not be pleased to receive notifications about stores on the other side of town, so my suggestion is a "subscribe" button at the store page to activate notifications for that particular store

**Comment by nicksellen** [comment]
I would suggest to widen this topic to notifications in general, not just mail ones.

Mobile push notifications at some point are almost essential imo to get sufficient adoption.

**Comment by nicksellen** [comment]
This could do with some progressing :)

**Comment by nicksellen** [comment]
Types to consider:
- push notifications
- email notifications
- telegram notifications
- slack notifications
- facebook notifications
- websocket notifications
- signal notifications

**Comment by nicksellen** [comment]
Also should consider how to show "notifications" (and other alert-y type things) on the webpage itself. There are quite a few different sources of notification-like information, some of it can be derived from existing state, some of them are probably notification objects themselves.

**Comment by tiltec** [comment]
Note that there's a half-broken slack notification backend: https://github.com/yunity/karrot-backend/issues/405

I think it could make sense to first think about notification stuff more before working on the backend more.

**Comment by nicksellen** [comment]
We talked about this on the karrot user call, about the need to have useful pickup notifications. It has the potential to get complex, and annoying if there are too many emails. 

I had an idea that we could send an email in the evening (say, 8pm) which informs people:
- any pickups for the next day that they registered to do
- any empty slots still available

The advantage of this is it is simple to implement (as it only has to collect information for one point in time), and not too annoying (as it's only one email), instead of potentially multiple for multiple pickup slots.

 Content would be something like:

> Hey Peter, this is your pickup summary for tomorrow!
>
> You are signed up to pickup at:
>   4pm at foo store
>   6:30pm at bar store
> 
> There is 1 pickup with no-one signed up yet:
>   8pm at baz store
>
> There are 2 pickups with empty slots:
>   9pm at boz store

Would that be useful @brnsolikyl / @nicco11a ? (not sure which other users groups we have on here) What about @tiltec and @djahnie?

Things I would leave out for now are:
- being subscribed to particular stores
- notifications about any changes since the email was sent
- last minute notifications (e.g. "in 1h there is a pickup with no-one to collect it!")
- cancelled pickups (e.g. store has no food)

**Comment by tiltec** [comment]
Sounds good! We could get the UTC time of local 8pm from the group timezone.

**Comment by nicksellen** [comment]
This is implemented and deployed now.

**Comment by tiltec** [comment]
I'll close this issue, we have our basic notification infrastructure in place. We will gradually add more email and push notifications if a user request arises, and fine tune them in order to not annoy people too much.
