### ISSUE TITLE
Use 'today' and 'tomorrow' instead of dates

### ISSUE THREAD

**Issue by alangecker** [yunity/karrot-frontend#311]

**Comment by Sliverriver** [comment]
is this meant for the pickup overview ?

**Comment by tiltec** [comment]
I think yes. Or other locations where you want to have easy-to-read dates (e.g. history)

**Comment by anne27** [comment]
Hey, so in "History", dates are currently printed as 
**Monday, March 6, 2017**
Should they be printed as
**Today**
**Yesterday**
or
**Today, March 6, 2017**
**Yesterday, March 5, 2017**

**Comment by tiltec** [comment]
I would prefer 
**Today**
**Yesterday**
and then a tooltip (using md-tooltip) showing the full date. Does it seem good to you?

There's a nice library called moment.js that we already use for date formatting. It can also print the human-readable relative date in many languages: https://momentjs.com/docs/#/displaying/fromnow/

Maybe it makes sense to introduce this directive: https://github.com/urish/angular-moment
But it's not really active (last commit Dec 2016), so I would actually prefer using a moment.js-only solution.

**Comment by D0nPiano** [comment]
I'm for the second version ("today, March 6") just because it's more precise and might prevent timezone confusions

**Comment by anne27** [comment]
Yes, I guess time zones might be a problem. Team Starbucks creating a pull request to add "Today" and "Tomorrow" for ease of readability. :)

**Comment by nicksellen** [comment]
I would use https://date-fns.org/ for this now :)

**Comment by nicksellen** [comment]
Places where it could be implemented:
- wall
- history
