### ISSUE TITLE
Investigate issues in Safari browser

### ISSUE THREAD

**Issue by jparklev** [yunity/karrot-frontend#332]
On clicking the leave group button, the page seems to freeze.

**Comment by tiltec** [comment]
Which browser are you on?

**Comment by itsmalk** [comment]
Safari. I just tried with chrome and it worked fine.

**Comment by tiltec** [comment]
Okay. thanks for the feedback. I don't have a Mac around, so I can't really test it. But I would be happy if we can resolve this issue. 
How is the overall page speed on Safari for the foodsaving tool?

**Comment by itsmalk** [comment]
Maybe just a hair slower than on chrome — but overall, pretty quick and responsive.

**Comment by tiltec** [comment]
Feedback from Bruno:

![group page](https://cloud.githubusercontent.com/assets/4410802/25070526/fed25daa-2298-11e7-9e5d-b68a6299bad6.png)

@ShababShahriar since you are on Mac, can you verify?

**Comment by ShababShahriar** [comment]
This is what I see:
![screen shot 2017-04-16 at 10 40 54 pm](https://cloud.githubusercontent.com/assets/15160771/25072647/f8dfb5de-22f5-11e7-9660-a1296a9f3418.png)

**Comment by tiltec** [comment]
Thanks! Looks almost good, just the tabs are mangled…

**Comment by tiltec** [comment]
If we want to investigate this further, we need a Mac or a Browserstack account.
