### ISSUE TITLE
Translation capabilities for user-defined fields

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#344]
Kristijan had the idea to give the users the ability to provide fields (title, description, etc) in multiple languages. 

I'd be up to look more into it when there is enough user need (e.g. when ~5 groups have expressed that they would need this feature).

> In the interface - maybe something like left and right pane - left the source  language - on the right the target language to translate to. And dropdown box for the languages?

I think instead of implementing our own translation service, we could integrate one of the existing ones (weblate/pootle...)

**Comment by nicksellen** [comment]
There is no interest/discussion about this for some time now. Re-open if interested again!
