### ISSUE TITLE
Optional admin roles for groups

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#356]
Foodsaving groups have requested to have admin roles. It should be optional and per group, per default all users are equal.

If the admin feature is enabled, a non-admin user should not be able to do the following things:

- edit the group
- create/edit/delete stores
- create/edit/delete pickup dates and series

The usual actions a non-admin user can do:

- join/leave group
- join/leave pickup date
- give feedback (when implemented)

How to become admin:
- by creating a group
- being appointed by another admin
- being voted in an election?
- having done many pickups?
- (more ideas?)

There's also a higher-level discussion about this topic: https://github.com/yunity/foodsaving-frontend/issues/89

**Comment by djahnie** [comment]
This was the initial idea, more detailed feature discussion is happening in #550 now.

**Comment by tiltec** [comment]
This discusses the wider topic of additional roles and is still relevant for the near future.

#550 discusses the minimal admin implementation needed for #324

**Comment by djahnie** [comment]
Feedback from Valencia:

"im not sure what organization could be, but i think about something similar to a federal system
the users could vote which one could be the admin for example, like one of the link you share me says
said it* _[this one and #260 were linked - addition from djahnie]_
but i think that the process of proposing and voting roles must be in person, in a real meeting with the volunteers
and after that, the distribution of the roles, in the karrot platform.
i think that way could save a lot of work of development and at the same time, bring freedom to every foodsharing group
i don't know if that is what is already working..."

**Comment by tiltec** [comment]
At our last hackweek, we discussed quite a bit about admin roles and hierarchies. @djembejohn wrote a comprehensive report that is available as Slack post: https://slack-files.com/T0B6WCFM5-F9DV755NV-7f110e0e0e

While I don't have notes of our meetings, my personal summary is:

- hierarchical roles seem hard to implement partially, it almost always requires an admin roles with full rights
- bootstrapping admin roles is an immense problem, but also getting rid of them, so they need to well thought-out
- many existing foodsaving groups are hierarchical and they are used to hierarchical roles, so if we implement something else, we need to give them reasons why it is better than admin roles

I came to like the concept of "approval". I think of it as light-weight voting system that we could require for some sensitive actions or roles. It could be similar to #853, but with shorter time spans, less required participation and only three options ("approve", "don't approve", "ignore").

The biggest concerns I have with it is increased "friction" when enabled for actions: these sensitive actions take much longer to complete and spark discussions, so people might be hesitant to do them at all. But if we enable it for roles ("Please approve that John becomes our agreement manager") and the roles have actions associated that don't need approval (or just among members with the same role), then it could be fine again.

**Comment by djahnie** [comment]
Having admin roles optional seems very difficult because of the bootstrapping problem of how to start. Should the first user be the initial admin and decide if admin roles are enabled? Could we have a vote (if we had a voting system) about if a group wants to have admin roles or not?

This needs more thought and time. It's really tricky and abstract and far away from an implementation, so we close for now.

When we have clearer ideas and people up for working on this we will open (a) new issue(s).
