### ISSUE TITLE
Generalization of store pickups for other tasks

### ISSUE THREAD

**Issue by Sliverriver** [yunity/karrot-frontend#359]
The management of schedules for store pickups has some basic core features that make it universall to plan other tasks.If the store management is broken down into core features it can be described as : 

"A voluntary team that is engaged in self management to fullfill regular or onetime tasks".

At the moment it represents one task only 
"Pickup" "food".

This can be generalized into 
"verb" "item" 

So far this easy to manage and unique store feature has been used to organise other tasks as well.  People are used to the self organization of the store pickups and this can be transferred to other parts of things that need to be done. 

Examples : 
1) Management of a cleaning crew for "fair-Teiler" 
For every "fair-Teiler" there is usually a cleaning crew.
The shelfs are generally cleaned every day.
To have an overview if it has been cleaned already or if someone has to go there many cities use 
the store pickup management to have a cleaning schedule management.
Specific information is shared on the wall. 
Specific instructions are used at the description.

Task : Clean the shelves every day at 5pm.

generalization : 
"clean" "shelves".

examples : 
Town -> Mainz
Store "Neustadt Fairteiler"
https://foodsharing.de/?page=fsbetrieb&id=12806
<img width="1030" alt="fair-teiler-cleaning-plan" src="https://cloud.githubusercontent.com/assets/2359021/23406193/0df188a6-fdbe-11e6-8e87-c8f115dde44c.png">

2) Management of organising a weekly Brunch (get-together)
Every week a brunch is held.
To organise the brunch a team is needed , so it is not alwayse one person organising it. 
The tasks can be split into multiple smaller parts so that it can be done as a group effort. 
The Description is used for specific information of the organization of the brunch.
The goal is to have it easier for new people, who want to contribute, to pick a task. (similar to a store pickup) As the brunch is 3 hours it is considered easier if the person who opens the store doesn't have to be there all the time and can give the key to somebody else who will then close the store.  The wall is also used for generall information - who brings food etc. 

The main tasks are : 
 - Pickup the key on friday between 5 and 7
 - Open the door on saturday morning at 10:30 am
 - close the door on saturday at 2pm. 
 
This translates into a "schedule"  

Friday 5pm
Saturday 10:30 (first shift)
Saturday 12:30 (second shift)
Saturday 14:30 (closing shift)

"pickup" "key"
"open" "door"
"close" "door"
 

Going into detail there are more tasks that could be done , but it proved to be inpractical to have too many of it. (Create facebook event,create foodsharing event,  clean the room, deliver food(this task doesn't represent the philosophy of the brunch and was abandaned )

town : Mainz
store name : "Foodsharing-brunch"
store : https://foodsharing.de/?page=fsbetrieb&id=4418&sub=forum

3) Organising of street food festival booth.

The same principle that is used for 1 and 2 can be the basis for organising a public relation event. 

e.g.: there should be at least 2 people at the stall and the whole time the stand should be covered. A shift may cover 2 hours. 
As well more people are needed to built up the stall (up to 4) and to dismantle the stall (up to 4 people)
At the end of the event it is usually possible to pickup foods from other stalls. so more people would be needed to support. Also it would be usefull to know who can bring some special items 
"really large food containers".  To remind every one of it and to 

example schedule 
10 am 4 people "built booth"
12 am 2 people "occupy booth"
2 pm 2 people "occupy booth"
4 pm 2 people "occupy booth"
6 pm 2 people "occupy booth"
8 pm 4 people "dismantle booth"
9 pm 10 people "pickup food"
9pm 10 People "bring" "really large food containers".

**Comment by nicksellen** [comment]
It's a nice idea, but topic has been inactive for some time. Can re-open if needed :)
