### ISSUE TITLE
notification options in stores

### ISSUE THREAD

**Issue by Sliverriver** [yunity/karrot-frontend#363]
As a user i want to have full controll about notifications and the way of notification that are used to notify me.

**Notifications for Group chats**

Notification options : Mail, App
<img width="119" alt="bildschirmfoto 2017-03-01 um 16 48 04" src="https://cloud.githubusercontent.com/assets/2359021/23467622/dca5558e-fe9e-11e6-98c9-a81a06ab7764.png">

**Notification for Wall comments**
<img width="119" alt="bildschirmfoto 2017-03-01 um 16 48 04" src="https://cloud.githubusercontent.com/assets/2359021/23467622/dca5558e-fe9e-11e6-98c9-a81a06ab7764.png">

**Notifactions for free pickup slots:**

For a store i want to be able to set a custom notifications if there are any slots for pickup available.

Generalization : I want to receive an <option of notification> <number of hours> hours before pickup if there are still <number of slots>  slots available. 

I want to have it transparent and visible who is informed at what point. So a team can built a emergency responce team 

Layout idea : 
An idea could be a matrix  display, with small pictures of the users who selected that option
If clicking on a profile picture: showing profile. 
Mouseover profile picture : Show Name. 

<img width="724" alt="bildschirmfoto 2017-03-01 um 16 46 19" src="https://cloud.githubusercontent.com/assets/2359021/23467556/a953682e-fe9e-11e6-9a95-be97612592fe.png">

Notication options : Message, E-mail, App, SMS
Option Ideas : For each pickup ? 
Maybe i can just be reached as emergency notification for a pickup on wednesday and friday.

**Comment by tiltec** [comment]
As far as I can see, that means having notifications at all. Also we need to work out first plans how chat should be integrated and what we need a wall for.

**Comment by Sliverriver** [comment]
As an example for the wall. 
It is used for general information. Sometimes the information can relate to a pickup but sometimes it is also just an advice for everyone to notice. It is more visible on the wall then in a chat.
People write if there is someone coming along for an introduction pickup, so that people know if there is someone showing up even if he is not verified in the pickup window. 
The history of who joined the team is shown there as well ( i don't know where it will be shown in the new tool ?) 

The information are shared on the "wall" feature and not only on the chat, because it is visible on the page without having to switch to the communicatinos page. Maybe with a different layout / solution the chat could be implemented on the site itself ? or more of a facebook conversation stile ? 

<img width="529" alt="bildschirmfoto 2017-03-01 um 20 58 51" src="https://cloud.githubusercontent.com/assets/2359021/23478647/426c3aae-fec2-11e6-9a72-2bb0bcc6967f.png">

<img width="525" alt="bildschirmfoto 2017-03-01 um 20 58 37" src="https://cloud.githubusercontent.com/assets/2359021/23478679/58f0f9d6-fec2-11e6-9f9e-444daac33e67.png">


To summize, sometimes you have information directly link to a past pickup , sometimes to a future pickup  and sometimes it is just general information as advice / caution / information for the team.

**Comment by Sliverriver** [comment]
From my point of view the e-mail notification should be feasable as a first notification model. But yeah i don't know how much thought already have been done regarding this topic.

**Comment by djahnie** [comment]
As I see it the info relating to past pick-ups will be entered directly in the feedback form and thus be visible in the history. I agree that it should be easily accessible. Did anybody already put thought into where to display it in the frontend?
All the general information should be added directly to the store description on top, as this is the solution that gives the best overview, I'd say.
So the thing that's missing is only the introductory pick-ups. Maybe those could be handled directly in the pick-ups themselves? Like, adding a button in the pick-up details, where people can state that a newbie will come along. That info could then be shown as a simple line of text in the pick-up dates as well.

Oh and everything we had concerning email notifications so far is in #257 @Sliverriver.

**Comment by Sliverriver** [comment]
I think if you have feedback to a pickup - that it could be also for future as past pickups. so maybe it is more like a comment to a pickup. e.g: i want to say that for this pickup it will be a lot and people should bring cars or certain type of containers. 

i think this point covers in more detail your points 
-to all members of a store team when a pick-up approaches and needs more foodsavers (time..?)
-to the member who signed up when a pick-up approaches (e.g. 1 day in advance)
mentioned in #257

**Comment by nicco11a** [comment]
We are a foodshare called Solidarity Fridge or for short Solikyl (add .se for the site) in Gothenburrg (Göteborg) / Sweden that need the concept of having introductory pickups with one instructor and at least 2 students and customize messages accordingly. For example, when 2 students joins that are not listed as experienced, one of the teachers will be notified so they can join. Once one of the teachers joins the students will be notified and e-mail's etc. will be shared so they can arrange a meeting place together or the students will not be notified of a available pickup before a teacher have joined one such pickup. Preferably both options should be covered.

For details of why we want this particular setup, see the discussion here:
https://github.com/yunity/foodsaving-backend/issues/273#issuecomment-284401538

**Comment by nicksellen** [comment]
Closed in favour of #257
