### ISSUE TITLE
Tech: Write a camelCase <-> snake_case converter

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#367]
The backend convention is snake_case, while the frontend uses camelCase.
This introduces linter errors. Right now, we disable the linter at these locations.

Best would be to convert the names at early stage in the frontend (services that call $http)

**Comment by b-lawrence** [comment]
Hi, 

I'm new to the project. Big fan of Angular and I think I can make a few contributions to this.

From the top of my head, I'm looking at how an AngularJS utility `$filter` would play out here. This would allow for a lot of flexibility; for instance, you could inject the filter into a `service` or `factory` and use it programmatically in there  like `$filter('2camelCase')('snake_cased_string')`, or you could take it all the way down to the template and use it like `{{ snake_case_value | camelCaseFilter }}`. :)

Cheers!

**Comment by tiltec** [comment]
Hi @b-lawrence , great to have you here! Solving this issue would make our code much nicer for sure!

A bit more background: these snake_cased fields come from the backend, travel through the $http-based services (e.g. [PickupDate](https://github.com/yunity/foodsaving-frontend/blob/master/client/app/services/pickupDate/pickupDate.service.js) ) and then end up in the [controllers](https://github.com/yunity/foodsaving-frontend/blob/5d4966ad7d03b98ddb958d9a8fb563dd7c2c1a7f/client/app/components/group/_pickupEditCreate/pickupEditCreate.controller.js#L39) and [templates](https://github.com/yunity/foodsaving-frontend/blob/4bb4ed82924266315d091328a6e2d92664b1b479/client/app/components/group/_pickupList/pickupListItem/pickupListItem.html#L29).

Example of incoming data:

```json
  {
    "max_collectors": 2,
    "collector_ids": []
  }
```

I can think of some ways to handle this problem:
1. change the names of affected fields in the $http-based services (e.g. rename field `max_collectors` to `maxCollectors`) during receive and send
1. change the names in the backend serializer, so that no snake_cased name will ever reach the frontend
1. build some kind of wrapper/getter/setter around those objects - makes it harder to pass around though

Your suggestion with filters is good for strings (as in messages etc). But I'm not sure if this is a solution for accessing object properties?

**Comment by b-lawrence** [comment]
Yeah, you're right! Thanks for providing more context. This is definitely a serializer/deserializer operation and in my opinion, should happen in the data service before hitting the controller.

**Comment by b-lawrence** [comment]
I'm mostly inclined with **2**. 😄

**Comment by tiltec** [comment]
Yes, I also quite like it. Much easier than rewriting the fields in the data services.

**Comment by b-lawrence** [comment]
Yup. Can I take this up?

**Comment by tiltec** [comment]
Sure :) Did you manage to set up the backend? Ah, and maybe you could [join our slack](slackin.yunity.org) for more chatting ;)

**Comment by b-lawrence** [comment]
Thanks! Setting up now :)

**Comment by tiltec** [comment]
Oh.. another very simple option: we could just change the respective linter rule in the frontend.

Then we could leave away the "eslint-disable-line" statements or the workarounds with double quotes around the property. 

The backend change would make the serializers slightly more complex: need to reference the model fields explicitly in underscore cases.

**Comment by b-lawrence** [comment]
Yeah, I agree that the complexity of the respective serializers will grow. However, if you change the `camelCase` linter rule to something else that doesn't enforce `camelCase` anymore, then we'd be open to having both `camelCase`d & `snake_case`d props used in the code, which doesn't guarantee consistency.

**Comment by nicksellen** [comment]
I would consider just writing a function that will convert all keys you pass into it recursively either to/from camelCase.

Can wrap/intercept $http calls to do it automatically and in one place without touching anything else.

Rationale for doing it in frontend: there is no _correct_ case for an API, consumers that use ruby/python like snake_case, java(/script) people would prefer camelCase. Keeping backend snake_case is more pythonic.

Alternatively, if going for backend option did you check to see if https://github.com/vbabiy/djangorestframework-camel-case would do the job? (just did a quick search)

**Comment by b-lawrence** [comment]
> Rationale for doing it in frontend: there is no correct case for an API, consumers that use ruby/python like snake_case, java(/script) people would prefer camelCase. Keeping backend snake_case is more pythonic.

True @nicksellen

I like the idea of HTTP interceptors though.

**Comment by tiltec** [comment]
The app @nicksellen linked would do the job in the backend. It also gives an insight how we would solve this problem in the frontend, by recursively going through the data structures and exchanging all identifiers: https://github.com/vbabiy/djangorestframework-camel-case/blob/master/djangorestframework_camel_case/util.py

If you choose the interceptor way, you have to make sure to only modify responses to our backend. We also have requests to Nominatim.

**Comment by b-lawrence** [comment]
Looking at these two options, doing all the work on the Backend seems pretty straightforward and simple using the lib @nicksellen linked. However, considering where this operation really matters (the frontend), I'm starting to think that having some kinda utility service with the sole responsibility of preparing data for use, might seem like a good way to go (Keeping frontend-related operations within the frontend's scope).

**Comment by tiltec** [comment]
I tried out the camelCase package. Does its job... but: 

```sh
$manage.py test
#...
FAILED (failures=28, errors=11)
```

One common error is: `Unsupported media type "multipart/form-data" in request`. Don't really know where it comes from, it seems that I would need to set JSON manually on each request (and the autodetection fails after including the package). I could just remove the camelCase converter for testing.
