### ISSUE TITLE
History filtering/date-browsing

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#382]
The history API returns the latest 50 results per default: https://github.com/yunity/foodsaving-backend/pull/260

We should give the user the opportunity to browse through the history and filter by action type (`typus`).
Use swagger ( https://foodsaving.world/docs/#!/history/history_list ) to see the filtering options and the API results.

Update: we now can filter by user and store.

To do:
- attach history to store view (only showing store-related events)
- enable browsing by date (e.g. load history events before a point in time)

**Comment by Sliverriver** [comment]
does this also include filter by date ?

**Comment by tiltec** [comment]
Yes, that's what I mean with browsing. Maybe a date picker to jump to a certain point in time.
The backend could be changed to offer date filters, that could make it easier.

**Comment by Sliverriver** [comment]
i am a bit lost where to comment for this request - if it's a new issue or improvement for this one. The history looks really nice on the frontend. I worry that it can get quite cluttered where it is now. has there been discussion if the history could be attached to a store ? Like the same tab just on a store level to switch to ?

**Comment by tiltec** [comment]
Yes, that would also be possible. Note to implementers: history is a stateless component, you can just feed it any list of history items.

**Comment by tiltec** [comment]
To do: jump to a point in time.

**Comment by tiltec** [comment]
The new history lost all options for filtering currently, should we add it again? Which ones are the most useful?

![image](https://user-images.githubusercontent.com/4410802/32144349-cdc6bfd0-bcb7-11e7-91dc-cea7842b6511.png)

(Will move it back to Discussion)

**Comment by tiltec** [comment]
It would be nice to have/cool, but there wasn't a _real_ need for it so far. You can visit group/store/user history right now, which is fairly powerful already.

**Comment by tiltec** [comment]
Can be reopened if requested.
