### ISSUE TITLE
Rename "history" to "activity"

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#427]
We have an audit log called "history" (currently displayed for groups). @nicksellen had the idea to rename it to "activity", and I support this proposal.

Upside: more fitting name
Downside: would need some refactoring, including backend API

What do you think?

A quick solution could be to change only frontend strings, but that could cause confusion.

**Comment by nicksellen** [comment]
I think change is good, could leave it waiting here until somebody wants to do the work...

**Comment by varu038** [comment]
Hello @nicksellen, @tiltec ,

I am new to the process of contributing to open source community although I have been doing coding for quite some time. I would like to start contributing with this bug. I have read through the CONTRIBUTE.md. Is it okay if I start with this bug ..? Can you please explain further ..?

**Comment by tiltec** [comment]
Hi @varu038, great to have you here! First of all, sorry for the late reply - I have patchy internet access due to travels.
I think this is a nice PR to start with, happy if you do so! 

Do you have a tool to help you with the refactoring?
We will need to deploy frontend & backend at the same time, so there should a PR in each repo.

An area where some attention is needed are the translation strings (frontend locale-en.json). When we change the IDs, we need to take care to update all translated files as well and push them to transifex. Otherwise transifex will lose the translations ;)

Oh another thing: did you join our Slack already? slackin.yunity.org
It's our main communication tool, find us in the channel #foodsaving-tool

**Comment by varu038** [comment]
Hello @tiltec ,
What kind of tool are you talking about for refactoring ..?

I have joined the Slack.

**Comment by varu038** [comment]
grep history ./client/app/locales/locale-en.json -in 
52:    "HISTORY": "History",

171:  "HISTORY": {

@tiltec 
Are talking about renaming these to activity ..?

**Comment by tiltec** [comment]
For example a good editor that can help with the renaming. But it can also be done with extensive search/replace.

I use PyCharm for the backend Python code and Atom for the frontend.

**Comment by tiltec** [comment]
Yes, that's the messages (to sync with transifex). I guess you have seen that it's only the tip of the iceberg, most of the changes are in the code. Goal is a complete rename to "activity", so that future contributors won't be confused.

**Comment by varu038** [comment]
Hello @tiltec ,

I am trying to update the translation files but its not allowing me.
How do I do it ..?

tx push -s
Pushing translations for resource foodsaving-tool.frontend:
Pushing source file (client/app/locales/locale-en.json)
Exception: Only maintainers are allowed to update the source file.

tx pull -a
Pulling translations for resource foodsaving-tool.frontend (source: client/app/locales/locale-en.json)
 -> ru: client/app/locales/locale-ru.json
Skipping 'fr' translation (file: client/app/locales/locale-fr.json).
Skipping 'eo' translation (file: client/app/locales/locale-eo.json).
Skipping 'de' translation (file: client/app/locales/locale-de.json).
Skipping 'it' translation (file: client/app/locales/locale-it.json).
Skipping 'es' translation (file: client/app/locales/locale-es.json).
Skipping 'sv' translation (file: client/app/locales/locale-sv.json).
Done.

git diff
diff --git a/client/app/locales/locale-en.json b/client/app/locales/locale-en.json
index cd6b650..32db70e 100644
--- a/client/app/locales/locale-en.json
+++ b/client/app/locales/locale-en.json
@@ -49,7 +49,7 @@
     "PICKUPS": "Pickups",
     "MEMBERS": "Members",
     "STORES": "Stores",
-    "HISTORY": "History",
+    "ACTIVITY": "Activity",
     "DESCRIPTION": "Description",
     "ADDRESS": "Address",
     "TIMEZONE": "Time zone of group"
@@ -168,7 +168,7 @@
     "QUOTE": "quote",
     "HELP": "What is Markdown?"
   },
-  "HISTORY": {
+  "ACTIVITY": {
     "GROUP_CREATE": "created this group",
     "GROUP_MODIFY": "changed the settings of this group",
     "GROUP_JOIN": "joined this group",

**Comment by varu038** [comment]
as of now, I am just looking at client/app. Once done I will look at the backend. I think it would be a good idea to also rename the files. what do you think ..?

**Comment by tiltec** [comment]
Cool :) Yes, everything - as if it was never named "history".

**Comment by nicksellen** [comment]
@varu038 I added code formatting blocks to your post, otherwise you can't actually read the diff :)

**Comment by varu038** [comment]
@tiltec might be a silly question since this is my first push on git. On git push I am getting following error : 
fatal: The current branch newBranchForIssue#427 has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin newBranchForIssue#427

When I try the above git push with upstream I am getting following error : 
remote: Permission to yunity/foodsaving-frontend.git denied to varu038.
fatal: unable to access 'https://github.com/yunity/foodsaving-frontend.git/': The requested URL returned error: 403
Am I missing something ..?
Tried googling but none of the solutions worked for me.

**Comment by nicksellen** [comment]
Ah yeah, you create a fork in your account. There is a reasonable guide here https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by varu038** [comment]
Hi @tiltec , @nicksellen I have forked and cloned the backend. I am trying to activate the virtualenv with "source ./env/bin/activate" but I dont see this file in the project. How do I run this ..?

**Comment by tiltec** [comment]
Did you create the virtualenv, e.g. with `virtualenv -p python3 env`?

**Comment by HungryAdi** [comment]
Hey! Is this Issue still open? I'd like to work on it.

**Comment by tiltec** [comment]
Yes, it is! There is work to be done in the frontend, as well as the backend. Are you familiar with Python, Django and perhaps even the Django REST Framework?

**Comment by HungryAdi** [comment]
I am relatively new developer, as such I have experience with Python, some experience with Django, but none with the REST framework.

**Comment by tiltec** [comment]
@nicksellen: would you be interested to support @HungryAdi here?

I would be happy to receive a Pull Request, but don't have enough capacities for providing guidance.

**Comment by theresaslee** [comment]
I'm happy to help out too. I could submit the changes for the frontend and @HungryAdi could fix the backend if that is ok with everyone.

**Comment by nicksellen** [comment]
@HungryAdi / @theresaslee - if you're both up for that then go for it, it would be best to schedule it to be completed at around the same time as it will touch quite a few files and keeping up to date with changes in master can be painful if you leave it for too long.

you can follow the guide I linked to above for how to manage the pull request workflow - https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by vinibiso** [comment]
Hello! @theresaslee just so I know, are you and @HungryAdi already on it? I see your task as far as the front-end it seems. If not I can help with the back-end.

**Comment by theresaslee** [comment]
@HungryAdi - are you still interested in altering the backend?

**Comment by nicksellen** [comment]
@vinibiso / @theresaslee - if you are up for making the backend changes, I suggest you should proceed! You can create an issue in the backend and assign it to yourself so it's clear :)

Ping me if you want any guidance!

**Comment by theresaslee** [comment]
@vinibiso seemed interested in it, so he can do it.

If he doesn't respond within 3 days, then I can work on it.

**Comment by HungryAdi** [comment]
Hello, sorry for my absence. As far as the back-end goes, I think it might be beyond by capabilities at the moment, so if @vinibiso  wants to work on it, he should.

**Comment by vinibiso** [comment]
Hey! alright! I'm gonna get to it then. It's gonna take me a little while cause I have a project on the way right now, but I should be done with it by the end of the week.

**Comment by tiltec** [comment]
I'm closing this because it seems much more effort than it's worth. The back-end PR was missing a migration test and the frontend PR got out of date because we rewrote the whole frontend with another framework.
