### ISSUE TITLE
Access to users' detail

### ISSUE THREAD

**Issue by mrkvon** [yunity/karrot-frontend#428]
Hello,
i just signed up for foodsaving.world and before i verified my email, i got access to emails of other members of a random open group i joined.

Sharing emails semi-publicly without warning and ability to opt out, that shouldn't be.

I understand you're still in development. :)

**Comment by nicksellen** [comment]
Yes, I agree, it's unexpected to get that access to users email addresses so easily. Any resistance for moving this level of access @tiltec / @D0nPiano ?

**Comment by tiltec** [comment]
Should be moved, what's your proposal? We can make the mail address completely private.

**Comment by nicksellen** [comment]
Given there are no admins at the moment, that seems the only viable option. Are you also interested in contributing @mrkvon ;)

**Comment by mrkvon** [comment]
@nicksellen 
Thank you for the proposal/invitation. These days i'm mostly occupied by https://github.com/ditup/ditapi (& ./ditapp-ng) (https://ditup.org) (seems quite close to the yunity philosophy btw.). Therefore i'm reluctant to start other stuff. But generally and in near(?) future this project is something i'd be interested in contributing to. Probably when the _ditup_ gets to a first stable release and production.

Do you guys have a place with a vision, blueprint, plans for this particular project/website?

Also sorry for the late reply.

**Comment by tiltec** [comment]
> Do you guys have a place with a vision, blueprint, plans for this particular project/website?

Not really, nowadays all the knowledge is in GitHub issues (look out for the "production-question" tag). We have outdated overarching specifications and mockups [in our wiki](https://yunity.atlassian.net/wiki/display/FSINT/Specification), but they were hard to implement without skilled full-time devs. Our current strategy is much more agile, whatever that means...

**Comment by tiltec** [comment]
I think it's ok to show the email address to other group members. We could add a info/warning dialog before a user joins a group?

**Comment by Sliverriver** [comment]
It could be made optional for the user which information he wants to share at which place. E.G.: 

I want to share my e-mail with
- no one
- only people in . the group
etc. 

this could be come with a warning "by selecting the option blablub you are aware that possible <number of people> could see this information" 
or something like that - just brainstorming. 
or just a normal "i am aware that with this option people in my group can see my e-mail address". 
and "yes i am aware and agree " or "no i changed my mind" for options.

**Comment by nicksellen** [comment]
A few points from our current discussion:
- include a warning that your email address will be shared with the other members of the group
- if/once we have private user messaging, could perhaps not have emails group-visible by default
- might be useful if they are available via the API (for some special group role perhaps?)

**Comment by nicksellen** [comment]
#675 will implement a warning, we close the issue for now, until we are ready to implement more

**Comment by nicksellen** [comment]
> if/once we have private user messaging, could perhaps not have emails group-visible by default

We could revisit this now @tiltec :)

**Comment by tiltec** [comment]
Yeah, seems fine. I remember that they used the emails in Gothenburg, so could ask Bruno if they still need these information via API.

**Comment by tiltec** [comment]
This discussion could be forwarded into https://community.foodsaving.world

**Comment by tiltec** [comment]
See https://community.foodsaving.world/t/remove-email-address-from-profile-page-resistance/215

**Comment by tiltec** [comment]
Closing this based on the feedback from https://community.foodsaving.world/t/remove-email-address-from-profile-page-resistance/215
