### ISSUE TITLE
Branding/theming and/or CMS integration

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#431]
I was chatting with Clements from Nantes yesterday about which features are missing from the foodsaving tool and the main issue was about branding/theming it to fit with their organisation. At the moment it feels like you are becoming part of foodsaving.world and not nantes foodsharing.

An immediate practical issue was nowhere to put an introductory video to explain to the group how it works (although maybe this is fixed with markdown descriptions?), but I don't think that alone would be sufficient as far as I understand.

He wondered if having it available as a wordpress plugin would be possible and give our clear API structure this actually seemed like quite a viable option to me. Users could then use it via foodsaving.world or through a local groups wordpress site seamlessly. Two potential issues with this are mobile app support and push notifications - doesn't really solve these two aspects.

I thought that this might be an issue for other groups too (wanting to brand it to look like their own project) and there seems multiple approaches for this:

- wordpress/drupal/etc plugins, local groups either run their own cms instance or we help them run one
- simple theming options within the group settings (colours, logo, landing page...)
- serve custom domains from one app instance (e.g. foodsharingnantes.com would be served by the main instance but only show content for that group i.e. a domain maps to a group - could have a frontend deployment each or share that too somehow)
- support/suggest people to run their own instance and add options to customize/theme it (so in this case the france federation would have their own instance)

Personally I quite like the idea of a wordpress/drupal plugin and manage their own wordpress/drupal instance (or support that bit). It has two advantages:
- the wordpress plugin is a standalone bit of software dev (and the basics can probably be copied from a related open source wordpress plugin)
- it outsources a lot of features to the cms, groups can have full control over look/feel, and add calendars, galleries, whatever they want...

However, it's not without it's difficulties: managing users between plugin/app, UI is actually the most fiddly bit and means starting fresh....

And finally, it actually ties quite closely to a topic in foodsharing.de (see "Websites for foodsharing regions" section [1]) and discussions inside #foodsharing-dev slack where some cities/regions want to embed calendars about related events, and other cms-like features.

Kind of a big topic, but worth opening I think!

[1] https://yunity.atlassian.net/wiki/display/FSDE/2017-03-23+Meeting+notes

**Comment by nicksellen** [comment]
And to throw in another idea whilst I'm at it - the other approach to embedding content in other webpages is the javascript-based approach taken by disqus [1] and muut [2] which requires no backend code. Not sure how user account integration works with wordpress/etc though.

[1] https://nicksellen.disqus.com/admin/universalcode/
[2] https://muut.com/docs/embed/

**Comment by nicksellen** [comment]
This could be advanced now, with some basic options just to get the ball rolling. Could have a configuration file for _site name_, and maybe a logo....

**Comment by tiltec** [comment]
Closing this in favour of #676
