### ISSUE TITLE
groupInfo: offer a "join group" button for people who are not logged in

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#463]
Rationale: users are usually interested in joining their local group directly instead of the foodsaving.world website.

The UX would be:

- user lands on the groupInfo page (either from search engine or incoming URL)
- user clicks "join group" button (e.g. located in the top-right corner or on the bottom)
- redirects to login page, but user can also create a new account
- should join the group after login and go to the group page

If the group is protected by a password, then the joinGroup dialog should ask for the password after login.

**Comment by D0nPiano** [comment]
Almost solved with #565 

## To Dos
- [x] user lands on the groupInfo page (either from search engine or incoming URL)
- [x] user clicks "join group" button (e.g. located in the top-right corner or on the bottom)
- [x] redirects to login page, but user can also create a new account
- [ ] should join the group after login and go to the group page

**Comment by nicksellen** [comment]
@tiltec says this is solved now, what do you think @D0nPiano?

**Comment by nicksellen** [comment]
@tiltec tells me it is done :)
