### ISSUE TITLE
Use nominatim viewbox to improve store location search

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#467]
When setting a store location, the search bar returns locations in the whole world. Usually the store locations are in the same region as the group. Our geocoding service, Nominatim, has the optional `viewbox` [parameter](https://wiki.openstreetmap.org/wiki/Nominatim#Parameters) to prefer results in a given area.

1. Extend the [geocoding service](https://github.com/yunity/foodsaving-frontend/blob/master/client/app/services/geocoding/geocoding.service.js) with an optional viewbox
2. Determine an appropriate viewbox in the [storeEditCreateForm](https://github.com/yunity/foodsaving-frontend/blob/bd9bb33e417a15d982f4a7ae0a0d99cca6709aab/client/app/components/group/store/_storeEditCreateForm/storeEditCreateForm.controller.js) from the group location (Caution: the group location is optional!)

**Comment by ajay2507** [comment]
Is this open?. Can I make this change?.

**Comment by tiltec** [comment]
Sure @ajay2507 :)
I haven't worked with viewboxing before, but I think we should make it rather large instead of too small.

**Comment by ajay2507** [comment]
@tiltec I think so we have to pass latitude and longitude parameters as viewbox parameter to our Our geocoding service.
Currently its showing like the below, Can you explain how it should be?
<img width="857" alt="img" src="https://cloud.githubusercontent.com/assets/21375014/26563103/0a3c51fe-449b-11e7-8767-0f42e3c97a73.png">

**Comment by tiltec** [comment]
It will affect the locations search bar results while creating/editing a store. If you're looking for a street "Broadway 5", then it should show results close to the group location instead of more remote results.

Maybe we should try if viewboxing works as expected, i.e. has the desired effect?

**Comment by tiltec** [comment]
It could make sense to viewbox by country, that could be a bit simpler than finding the proper viewbox size manually.

**Comment by tiltec** [comment]
Doesn't seem very important and seems to be too complex for a starter task, so I'll close it to focus our issue tracker a bit more.
