### ISSUE TITLE
Remove shebang(#!) from the URL

### ISSUE THREAD

**Issue by SiddharthaSarma** [yunity/karrot-frontend#515]
I think there is no need of #! in the URL.
Please let me know if you did it purposely.

**Comment by SiddharthaSarma** [comment]
If you want to remove it, please let me I'll work on it.

**Comment by tiltec** [comment]
Yes, that would be a nice cosmetic change. Will old URLs continue to work?

**Comment by SiddharthaSarma** [comment]
I hope they will work.

**Comment by nicksellen** [comment]
It requires backend changes too. if you visit `/stores/1` the browser will pass that request to the backend first which needs to serve up the default index page (as if you had visited `/`). After that angular routing takes over.

The reason we didn't do it initially is you need to somehow get the backend to understand which are valid frontend URLs. One way is prefix all API endpoints with `/api`, serve all static content if available, otherwise serve index page.

Personally, I don't think this is worth the time. Nobody cares about the URL except developers, and this is still an early stage product. It is not the biggest value-for-time change.

**Comment by SiddharthaSarma** [comment]
Okay

**Comment by D0nPiano** [comment]
Frontend wise, I'd just be changing app.js, line 48:
`$locationProvider.html5Mode(false).hashPrefix("!");`
to:
`$locationProvider.html5Mode(true);`

I think it also matters for googles (and others) webcrawler. I read that the shebang prefix tells google it's an ajax generated page, and the crawler will try to access the page with another url. For example, if the crawler finds `href="/#!/groups" ` it will crawl `?escaped_fragment=group`. Also, currently we do not even have hrefs on our links (only the javascript way) - so I think our site is not really crawlable. But html5mode magically adds them automatically (pretty cool. Just tried it locally :) )
Therefore, it would also make sense for indexing our page on search engines. See [googles description for ajax crawling](https://developers.google.com/webmasters/ajax-crawling/docs/specification#bidirectional-between--url-to-_escaped_fragment_-url)

I don't know if, frontend wise, html5mode has any disadvantages though. Also, I don't know how much work it'd be backend wise.

**Comment by SiddharthaSarma** [comment]
Yes @D0nPiano,  frontend wise we won't have any disadvantages and it is a single line change at the frontend but since @nicksellen says that it requires backend changes also, maybe we can do it at later point of time.
I raised this issue because everyone wants to make their site with Pretty URL's because they do they appear friendlier to the visitors but they also offer immense benefit from the SEO (Search Engine Optimization) perspective - something that cannot be ignored if you wish your pages to rank high in Google search.

**Comment by tiltec** [comment]
Our nginx config is

```
server {

    server_name foodsaving.world;

    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    ssl_certificate /var/www/foodsaving-world/cert/fullchain.pem;
    ssl_certificate_key /var/www/foodsaving-world/cert/key.pem;

    root /home/deploy/foodsaving-frontend/release;

    location / {
        try_files $uri /index.html;
    }

    location ~ ^\/(api(\-auth)?|docs)\/ {
        include uwsgi_params;
        uwsgi_pass fstool-production;

        uwsgi_param Host $host;
        uwsgi_param X-Real-IP $remote_addr;
        uwsgi_param X-Forwarded-For $proxy_add_x_forwarded_for;
        uwsgi_param X-Forwarded-Proto $http_x_forwarded_proto;
    }

    location /static/ {
        root /home/deploy/foodsaving-backend/;
    }
}
```

as documented here: https://github.com/yunity/foodsaving-backend/blob/master/deploy.md

How does it need to be changed?

Generally, SEO is not that important to us at the current stage. We get plenty of interested visitors. What the app needs is more devs who stay active and communicate with the users (e.g. via our Slack channel).

**Comment by nicksellen** [comment]
@tiltec that would work ok in production (although responding to all requests with index.html is perhaps a bit much e.g. https://foodsaving.world/foo/bar/yay.png), but during development you would get a 404 without backend changes.

The default-to-index behaviour can be done in django by adding a route at the bottom:
```python
url(r'^.*$', index),
```
(from https://stackoverflow.com/a/28994099)

**Comment by nicksellen** [comment]
> Generally, SEO is not that important to us at the current stage. We get plenty of interested visitors. What the app needs is more devs who stay active and communicate with the users (e.g. via our Slack channel).

I agree.

SEO could be useful for landing pages at some point (e.g. people searching for "food saving in rotterdam"), but the main purpose of this software at the moment is the logged in functionality which would never be available to google.

It's also not quite as simple as just removing the shebang. The last understanding I had was that it wouldn't wait for asyncronously loaded content to appear. https://goralewicz.com/blog/javascript-seo-experiment/ is recent experiment with this if you're interested. I did not read the outcomes.

**Comment by D0nPiano** [comment]
Definitely agree on the point that most of our pages are only available to logged-in users anyways. I think removing the shebang only makes sense in the long run when we have other public pages.

As far as I understtod, the SEO experiment you linked actually seemed to work in most parts, see: https://www.google.de/webhp#q=site:jsseo.expert - the content is cached correctly for angular1 and searchable. Even though, interestingly, angular2 didn't work as well. It even waited a little longer for content to appear like the one on this ember.js site: http://jsseo.expert/ember/
