### ISSUE TITLE
Integration of communication features (chat, forum, ...)

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#520]
We agree that a chat and/or a forum are crucial for building up a community. Although the first versions of the foodsaving tool were directed at _already existing_ communities that have e.g. a facebook group, a Slack chat or the likes, we have been getting requests to integrate more communication features into the foodsaving tool itself.

I think it's feasible to set up a forum (e.g. [discourse](https://en.wikipedia.org/wiki/Discourse_(software))) and a chat (e.g. [Matrix](https://en.wikipedia.org/wiki/Matrix_(communication_protocol))/[Riot](http://riot.im/)) and integrate it with the foodsaving tool by providing single sign on.

What features are necessary to fulfil the user's needs?

**Comment by D0nPiano** [comment]
I think they should be:
- open source
- well documented
- provide a good api to build a custom frontend for most features.

Discourse seems like a very good choice for a forum, but I didn't read myself into Matrix or Riot yet.

**Comment by tiltec** [comment]
I gave the Matrix client-server API a read a few days ago; here are my findings:

- it covers all the important parts and is quite easy to understand
- all the chat activity happens inside rooms, also personal messages (direct chat)
- there's a Javascript client SDK available
- many auth mechanisms supported in the protocol, but the only available server (synapse) just supports username/password. I think this could be a big problem for seamless integration
- it's not possible to add custom message types, e.g. if we would want to add some special messages for events
- federation with other servers should work without a problem, but they recommend using a central trusted _identity server_ (for resolving e-mail addresses to usernames etc). I don't consider federation a benefit
- Riot, the main standalone client for matrix is quite bulky and feels less fast than Slack

Mikato told me about https://conversejs.org/ - "An XMPP chat client which can be integrated into any website.". Would be worth a review.

I would also like to review the Discourse API.

**Comment by brnsolikyl** [comment]
I don't know about the technical feasibility and difficulty of this, but please consider integrating/merging with [Loomio](https://github.com/loomio/loomio)! I think it has all the requirements pointed out by @D0nPiano and from our point of view in Gothenburg (we have been looking for a better tool for communication than the forum we use) it would work great when scaling up, that is, when creating many local groups that save food and that are able to deal with their respective cooperating stores (Loomio's decision-making tools are a great plus there).

**Comment by nicksellen** [comment]
My proposal contains a suggestion after playing a bit with django channels and discussing with @tiltec but I would also address a few of the points here.

## ...integrate it with the foodsaving tool by providing single sign on

Discourse can be configured to authenticate users via a custom URL [1] which is nice of it, but there is no official way to get different groups access to different parts of the forum. Some workaround options are discussed [1][2]. I think deep integration with the foodsaving tool would be tricky.

I am also concerned about the extra burden of a manage a Discourse forum (which is not trivial to deploy) to be able to run the foodsaving tool.

One approach could be to just let groups setup their own Discourse installation if they want it, and have SSO endpoints that only permit access to a specific group. I suspect most groups would not be able to set up a Discourse server though and it would limit adoption. I don't think we have the resources to manage lots of seperate Discourse installations either.

## Matrix integration

From the research @tiltec did, it sounds like it would be tricky:
- _I think this could be a big problem for seamless integration_ (re: auth mechanism in available server)
- _it's not possible to add custom message types_
- _the main standalone client for matrix is quite bulky and feels less fast than Slack_

## Converse JS

The JS client looks reasonable, but the links to the Django implementations for the server look less promising:
- https://pypi.python.org/pypi/django-conversejs last version uploaded on 2014-11-04 and "Write tests" as a TODO
- https://github.com/fpytloun/django-xmpp says _This application is in early development stage. Every help or feedback is appreciated._ and the last commit is 9 months ago

Also, I think it implements many features we are not so interested in, and perhaps does not implement some we would want.

[1] https://meta.discourse.org/t/official-single-sign-on-for-discourse/13045
[2] https://meta.discourse.org/t/official-single-sign-on-for-discourse/13045

**Comment by tiltec** [comment]
I had a look at Loomio again, but I have no idea how we can integrate it or merge with them. They don't seem to have a stable and documented API and don't provide a plugin interface.

**Comment by brnsolikyl** [comment]
This is what I found on their [API](https://github.com/loomio/loomio/tree/master/docs/en/using_the_loomio_api) and [plugin](https://github.com/loomio/loomio/tree/master/docs/en/plugins), but apparently they did not come a long way there on the latter... But wouldn't it suffice to have a joint login only, once you deploy them at the same machine? I mean, what sort of communication / interaction between the two would we need? Loomio would be useful only as forum and decision-making, however, since it has no chat

**Comment by nicksellen** [comment]
Wall is implemented, so it at least minimally implements something related to this topic :)
