### ISSUE TITLE
Rethink group navigation for small screens

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#563]
Not enough space on those small screens! Maybe a new sidenav on the left for all group states (info, invite, edit, leave, description, stores, members, pickups)?

![screen shot 2017-07-21 at 20 12 48](https://user-images.githubusercontent.com/4410802/28477853-35178c42-6e56-11e7-8b18-4445daedd79f.png)

**Comment by D0nPiano** [comment]
Just tried out a couple of things on paper, and also just created the `newLayout` branch.

The icons on the md-titlebar could be merged in one md-menu.
Also I moved the sidenav to the left and moved the store-list in the same sidenav. Therefore, stores is removed on the tabs alltogether.

## New Layout
![1](https://user-images.githubusercontent.com/16825880/28494273-8c919994-6f29-11e7-9a82-2e8ef0a5e1fe.png)

## New Sidenav
![2](https://user-images.githubusercontent.com/16825880/28494274-8cbfb860-6f29-11e7-8135-22ab9fed92c5.png)

## ...when you click on the three dots:
![3](https://user-images.githubusercontent.com/16825880/28494275-8cc107a6-6f29-11e7-92ab-d287be50328f.png)


...thoughts, wishes, comments? :slightly_smiling_face:

**Comment by tiltec** [comment]
I like it very much!
Eventually I would like to remove the tabs on mobile (cause they don't fit horizontally).. what do you think about it?

**Comment by D0nPiano** [comment]
:slightly_smiling_face:  Yeah, removing them eventually makes sense. Although I think it's already alot better now that it's only 4 ones. @tiltec What do you think of moving the history tab to the ...-options menu on mobile? Then all 3 remaining options (pickups, description, members) would usually fit on a mobile screen I think.
