### ISSUE TITLE
Breadcrumbs continue to break and upstream isn't maintained

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#571]
Currently at least broken on the group page and on the history page (there are parts missing from the breadcrumb)
Last update on Nov 2016: https://github.com/ncuillery/angular-breadcrumb

I would advocate to get rid of angular-breadcrumb and build our own thing based on what we need (e.g. lot's of dynamic or translatable breadcrumbs).

**Comment by D0nPiano** [comment]
Sounds reasonable, and I think it would also give us more freedom after all. 👍

**Comment by tiltec** [comment]
I had a look at this angular2+ component and I like its architecture:
https://github.com/nonplus/angular-ui-router-title

I could implement something similar for us. Let me check the requirements:

- title should have a static part (foodsaving)
- title breadcrumb can be a static translatable string
- title breadcrumb can be dynamic, derived from values in services and controllers
- some states should not have a title breadcrumb (i.e. abstract ones)

Should states be able to override the whole title breadcrumb chain? Maybe it's not necessary.

**Comment by tiltec** [comment]
Not needed anymore, we have our own solution for VueJS
