### ISSUE TITLE
Notifications via website

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#577]
We currently have a pretty empty notifications page, only showing if users didn't verify their email address yet.

What else makes sense to show there?

- if the user can give feedback to a pick-up date #159 
- the user signed up to do a pick-up in <1 day?

Notifications can be marked as "read" when the user sees them, without making them disappear.
They should also "expire" when they are no longer relevant to the user, maybe just delete them then.

**Comment by D0nPiano** [comment]
Should also notify
- if there's a pickup in less than 24h noone signed up for

...and I'd like to put the "resend email verification button" on an extra (settings-)page, because it seems more intuitive to find there.

**Comment by tiltec** [comment]
> if there's a pickup in less than 24h noone signed up for

This one could be replaced with a different message after the pickup has been missed.

> ...and I'd like to put the "resend email verification button" on an extra (settings-)page, because it seems more intuitive to find there.

Great! :)

**Comment by nicksellen** [comment]
Rolled this topic into https://github.com/yunity/karrot-frontend/issues/257
