### ISSUE TITLE
Add conversations

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#583]
The backend conversations is getting close to being useful - https://github.com/yunity/foodsaving-backend/pull/333

I'd like to proceed by working out what will be useful for the frontend service to do, so I can create the correct API endpoints and websocket contract.

The only thing that will have a conversation right now is the groups.

Here is my idea for how it would be used (inside a controller for example):

```js
// message storage in your controller
vm.messages = [];

// the idea here is the service handles all the logic of:
// 1. fetching initial messages (via API)
// 2. receiving new messages (via websocket)
// 3. putting them in the array you pass to it
// it then returns an object you can do further things with
let conversation = conversationService.subscribe(24, vm.messages);

// write a new message into the conversation...
conversation.sendMessage({
  content: 'Yay, a nice message from me!'
});

// go back in time to get older messages, then add them into the array
conversation.fetchPrevious(20);

// it's then important to unsubscribe or they will start piling up
// there is an angular way to call methods when the controller is removed iirc
conversation.unsubscribe();
```

The more annoying bit right now is how to get the conversation id, as I [implemented in the backend](https://github.com/yunity/foodsaving-backend/pull/333) now as a GenericForeignKey on the conversation, so the group doesn't know the conversation id without looking it up.

There is a separate endpoint `/api/groups/{id}/conversation/` for retrieving the conversation info, and no endpoints for listing conversations.

For now I would propose the frontend websocket would receive messages for all the conversations you are in, but would only do anything if something had subscribed to a conversation using the frontend service.

The alternative would be to add/remove conversation subscriptions on the server, but it is more complicated and seems of no benefit right now.

Questions:
1. can this actually work on a technical level? (I think it should...)
2. do you like the API style? (slightly funky managing your array for you...)
3. any input on my assumptions for the frontend UI?

**Comment by tiltec** [comment]
Frontend assumptions seem valid to me. The conversations service would need to call `$apply` when the array changes to trigger a digest cycle.

UI: If we have the group conversation directly in the group page, would it be better to have the most recent message first (similar to "History")? Otherwise I would create a separated chat UI with a more common chat interface (oldest to newest, input at bottom).

> There is a separate endpoint `/api/groups/{id}/conversation/` for retrieving the conversation info, and no endpoints for listing conversations.

Seems fine, although it could be added as a SerializerMethodField. Will look into the backend after this.

**Comment by nicksellen** [comment]
See https://github.com/yunity/foodsaving-frontend/issues/539#issuecomment-315353393 for an idea for the UI from @Sliverriver (although we wouldn't have threads/comments initially)

**Comment by tiltec** [comment]
The wall-like chat (reverse chronological) is used by Trello, for example:

![image](https://user-images.githubusercontent.com/4410802/29029753-01db2948-7b89-11e7-9880-d88c1d15b595.png)

I found it quite confusing because people tend to react to each other and it's strange to read those from bottom to top.

Facebook has a mix: the wall is (largely) reverse chronological, but the comments are chronological (usual chat & forum reply style). That seems to be fitting, because the wall posts usually are not reactions to each other.

I would prefer a chronological style with the older messages on the top and the more recent ones at the bottom. That's what I would expect from a conversation (in contrast to a wall)

**Comment by nicksellen** [comment]
If it's too confusing without comments/threads then we could always postpone until they exist...? But I think it would be better to find a solution with just simple messages for now.

**Comment by D0nPiano** [comment]
I think the seperated chat UI will be usefull sometime in the future, and it would also be nice to be able to access the messages anywhere (like the messages at the bottom right of foodsharing.de or on facebook), so I'm also in favor of a seperate chronological chat for now.

**Comment by nicksellen** [comment]
Ok here is some working code! If you get backend branch `conversations` and frontend branch `add-conversations` then just run everything as normal it should work :)

I added 3 services inside the new `conversations` module:
* `Socket` handles the websocket connection, exposes a simple "subscription to everything" API
* `Message` handles things on the `/api/messages/` endpoint, just create and list
* `Conversation` does the clever stuff, you pass it conversation id and it returns you an object with everything you might want to do on the conversation

Then, I added the logic for showing it to `groupDetail` controller. If I keep the pull request to just the service I would remove this before suggesting a merge.

I did not write frontend tests yet. I slightly changed the service API from my proposal above, actually even simpler now.

A few points:
* just gets ALL the messages initially
* doesn't ensure messages aren't received twice (edge case from getting initial messages from API and web socket messages)
* no tests...
* cannot fetch old messages
* users are just referenced by id, not sure if there is a more general mechanism to get user info from ids (seeing as it's the same as the group members, maybe there is something for that, did not look yet)
* I would also add optimistic sending at some point, add the messages to the array immediately, but mark as "sending", then update when the server sends it to us, probably would do that in a later PR

![conversations](https://user-images.githubusercontent.com/31616/29032109-9503787c-7b90-11e7-98b0-dd19938685b2.png)

(Don't know why colours changed for my screenshot. Odd.)

**Comment by nicksellen** [comment]
I would be very happy to leave all the UI decisions to other people to...

My preference for the workflow would be to merge into master as soon as I have written decent tests (and removed the dev-ui), it would not work on the live backend of course, but it would also not be loaded by anything. Then work can be done on the UI, which I think is more involved and I would rather not delay this if possible.

**Comment by nicksellen** [comment]
Ah, just to remind myself: I also need to add the heartbeat/keepalive timer to the socket connection...

**Comment by nicksellen** [comment]
> Seems fine, although it could be added as a SerializerMethodField. Will look into the backend after this.

@tiltec I think it might be not such a bad thing to keep it seperate, there may be other ways to interact with the conversation in the future - muting it, some types will be leavable/joinable, adding members to it, etc...

The idea is to keep all those things nested inside the resource the conversation is about - as that is the only place that will know the correct permissions - the conversation itself being pretty generic and not caring about that stuff.

Message sending is fine from the other one I think as as long as you are in the conversation you can write a message, but perhaps even that would need to have special resource permissions/controls at some point - special messages, embedding certain things, etc..

Will not worry about that for now though. Just sharing some thought processes.

**Comment by nicksellen** [comment]
PR https://github.com/yunity/foodsaving-frontend/pull/584

**Comment by nicksellen** [comment]
Backend master has conversation backend in now, and frontend master has conversation service.

The only remaining piece is doing some UI now (and fixing some crap in the backend/service if needed) - this PR implements a basic UI for people to improve on https://github.com/yunity/foodsaving-frontend/pull/595

**Comment by tiltec** [comment]
We have the wall in groups, so I consider this as done ✨
