### ISSUE TITLE
Create a project info page

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#601]
I envision this as presentation about the projects foodsaving tool and foodsaving worldwide.

Content:

- what is foodsaving tool?
- what is foodsaving.world?
- how to start a foodsaving group (social and technical aspects)
- some links to the foodsaving worldwide wiki
- sponsors of foodsaving tool (development) and foodsaving.world (central deployment)

A static page or a minimal CMS like Grav should be sufficient. I like a Grav a bit more then Jekyll, though both are nice. I didn't try out other static page generators.

**Comment by djahnie** [comment]
Sounds great!
I like that it will give more info straight from the start and that we can recycle some bits from our 'start your own initiative' guide...^^ Grav sounds good to me, too (mostly because I already know it a bit... 😅).
I guess this will be multilanguage as well, right?

**Comment by nicksellen** [comment]
I would go for grav, has been working out nicely for yunity.org and foodsaving.today I think. And translation is supported through crowdin nicely too, they seem happy to let us add more projects into it as we need.

So, if people like grav, pick a theme from https://getgrav.org/downloads/themes (preferably one that has been updated/modified _vaguely_ recently) and I am happy to do the setup.

**Comment by tiltec** [comment]
I got the idea to move blog.foodsaving.world into the project page too, what do you think?

**Comment by djahnie** [comment]
Why not just take Helium or Hydrogen? They look nice and are the most recently changed ones... ;)
I don't really get the implications of them being gantry5 default themes though...

**Comment by nicksellen** [comment]
http://gantry.org/ seems to be a framework that helps people write themes, no implication for us really, except maybe lots of people will have sites with that theme?

...but once someone makes everything poo brown colour it will be unique again

**Comment by nicksellen** [comment]
Helium demo: http://www.demo-gantry5.en-toutes-lettres.fr/en/helium
Hydrogen demo: http://cnwebdesign.altervista.org/hydrogen-home

> The main difference between the themes is that Helium is a real, fully styled theme, where Hydrogen has just minimum styling to make it a good starting point for your own theme. If you want to do all your styling yourself, start with Hydrogen, otherwise Helium is a better choice.
https://github.com/gantry/gantry5/issues/1894#issuecomment-284330314

I think I prefer the simpler looking hydrogen personally

**Comment by tiltec** [comment]
👍 for Hydrogen, mostly because of the missing fly-in effects

About the color choice, I'd be happy with minimal colors as usual, but maybe we need a bigger discussion about foodsaving tool colors anyways?

**Comment by nicksellen** [comment]
https://github.com/yunity/foodsaving.world - just an initial grav install for now...

**Comment by nicksellen** [comment]
This is what the site thats currently in the repo looks like now :)

![fs2](https://user-images.githubusercontent.com/31616/29751617-cf82a240-8b47-11e7-9bfb-c220890db380.png)

**Comment by nicksellen** [comment]
Created! https://fsww-dev.foodsaving.world/

- [ ] favicon missing
- [ ] janina is blurry
- [ ] home page is default template content
- [ ] blog has no content
- [ ] don't know what should be on the blog anyway
- [ ] the fsww team is bigger than the fstool team, add more people?
- [ ] it says foo in the footer
- [ ] more practical pictures? (people doing foodsaving rather than dreamy pic)
- [ ] setup auto deployment from master

**Comment by stefan-fstaiwan** [comment]
Project info page sounds great!
My suggestion is to make the conception and terminology very clear, like what is foodsaving.world, what is foodsaving tool (karrot) and if necessary, what is the connection to yunity. The idea that karrot is a tool/software that needs to somehow be implemented locally. How to do that and how to start a foodsaving group (social and technical aspects). Links to the wiki and the sponsors.
For the g0v grant they basically provide a logo with a link to their website. Tilmann already put it on https://foodsharing.tw/ and I think it would be good to have it on the info page as well. There a few different formates of the logo to choose from on the bottom of the site https://grants.g0v.tw/power/ .

**Comment by djahnie** [comment]
Thinking about blogs...
So far we have the news from foodsaving groups on foodsaving.today and the karrot devblog directly on foodsaving.world. I think it would be nice to integrate the two blogs on the new static info page somehow (and be it just as a link to foodsaving.today for example), while still keeping them seperate. The karrot blog is more about the technical side, and the today blog is about the social side. So maybe it would make sense to have the today blog accessible prominently vie foodsaving.world and have the karrot blog linked in the app itself (which is basically how it is right now, isn't it..?)... 🤔

**Comment by tiltec** [comment]
The landing page inside the app (https://foodsaving.world/#!/landingPage) should be replaced by the project info page, to keep all static content outside of karrot code.
This would mean that we either link the karrot devblog from foodsaving.world or move its whole content over to a blog inside foodsaving.world. I would prefer the latter.
Foodsaving.today could be integrated into foodsaving.world as well, perhaps as "News from foodsaving groups". But I also can understand that it makes sense for foodsaving.today to stay separate, to keep it decoupled from foodsaving.world.

**Comment by tiltec** [comment]
This task should be tracked in the other repo, https://github.com/yunity/foodsaving.world
