### ISSUE TITLE
Map shows  Darmstadt when no markers

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#602]
In group 20 there is no store location specified. The map thus doesn't zoom into any location, even though a group location is added.

It would be better if the map zoomed into the group location, if no store location data was provided.
No marker should be displayed at the group location.

**Comment by Sliverriver** [comment]
isn't that more like a feature ? Because it is behaving like it should - since there is no store location there is no place to zoom in ?

**Comment by Sliverriver** [comment]
I agree with your proposal :-D - 
If store.location = not found 
then
 use group.location. 
i just wouldn't say it's a bug ;-) but i won't bug you with it.
