### ISSUE TITLE
History Filter more Types

### ISSUE THREAD

**Issue by Sliverriver** [yunity/karrot-frontend#604]
Hello everyone,

the history feature looks really nice and it helps to keep actions transparent and making everybody aware of their actions and the actions of the group as well as planning.

I would like to request a bit more differentiation on the "Types".

selecting "pickup related" now shows in combination with "users"
- pickups that have been missed. 
- signing up
- stepping back
- changing the settings of the pickups
- doing a pickup 

i would expect if a user is selected that the information "pickups missed" shouldn't be shown.

It still a little bit confusing. 

My user request : What selection would i need to do to just see - who did a pickup?

**Comment by Sliverriver** [comment]
some other thing i noticed - the filter display on history looks different  / has a different layout then in pickups. should it be either ? since it is the same feature "filter" results ? 
<img width="351" alt="bildschirmfoto 2017-08-31 um 23 51 51" src="https://user-images.githubusercontent.com/2359021/29946914-7a9ba2aa-8ea7-11e7-8d6f-5f55b9ca910a.png">
<img width="260" alt="bildschirmfoto 2017-08-31 um 23 51 44" src="https://user-images.githubusercontent.com/2359021/29946918-7e0f93f6-8ea7-11e7-8dc4-4a43f409b6be.png">

**Comment by tiltec** [comment]
I agree, the history UI (possibly soon named "Activity" #427 ?) didn't get much review so far. I would like to be interested in a general UI rework to make the filters look less office-suite-like (covering all potential cases) and focused on actual use cases.

Maybe we can still offer an advanced UI after checking a box or so.

**Comment by Sliverriver** [comment]
maybe this also relates to #382

**Comment by nicksellen** [comment]
Closed in favour of #382
