### ISSUE TITLE
Legal entity for karrot.world

### ISSUE THREAD

**Issue by Sliverriver** [yunity/karrot-frontend#606]
I think it was mentionend somewhere in slack and just want to make an issue for it so that discussions can happen here. 

Should there be a legal entity for running the website ?
How would that entity look like?
what would the responsibility be of it ?
which country should it be registered ? 

some examples : 
1) A user posts a swastika or other fascist stuff on the website / (or "karrot" (=The fs tool), and another users informs the authorities to sue them. (In germany it is forbidden to share / Post nazi-symbols). 
so the german "verfassungsschutz(Intelligence service) /police" would start an investigation and ask the site for information about that user (e-mail, IP(if stored),etc.) 

How should the site owner / legal entity behave ? What would we want/expect ? 

2) maybe some users decide that the foodsaving tool is perfect to run their drug ring on foodsaving.world. 
How should be the behaviour if the site owner is informed by 
a) another user 
b) approached by authorities who would like an undercover operation (i don't even know if i am exaggerating)

3) A user is unhappy with a group and demands from the siteowner that he intervenes with whatever user is unhappy with. (This would increase with more hierarchichal features on the tool)

4) copyright content is illegally shared through links in the forums. 
("Oh you haven't seen this movie/heard the music - here you can download it")

5) should the "owner" members of the legal entity "Owning" the site be transparent , making them more vulnerable for claims, or even people who would try to push/ influence for certain page changes. 

6) are there insurances for running a website ? i am serious about this question. 

just some sorts to get the discussion started.

The more the "site owner" who is running the foodsaving tool karrott is involved in appointing groups or creating them the more he will be involved in whatever happens there.

**Comment by tiltec** [comment]
Related thoughts:

This would be the main reason to encourage users to set up their own foodsaving tool instance. Maybe we can simplify it with docker and provide docker hosting services for interested groups?

The foodsaving tool instance on foodsaving.world would just be a demo and would get purged every few months.

**Comment by Sliverriver** [comment]
doesn't solve the issue that you would need one for foodsaving.world.

**Comment by tiltec** [comment]
Ideally, we would legally split operations between "developing the foodsaving tool" and "hosting an instance on app.foodsaving.world". I think the _developer organization_ wouldn't need a legal entity, and the _hosting organization_ one would need to get more and more professional with legal structures and everything.
As a developer, I would be more productive to not bother with the latter topics.

**Comment by lwm** [comment]
On this topic, I was also reading (for anyone else poking around):
* https://community.foodsaving.world/t/funding-concept-for-karrot/136
* https://community.foodsaving.world/t/a-karrot-co-op/124
