### ISSUE TITLE
Allow to reset pickups settings to series default if they have been changed

### ISSUE THREAD

**Issue by Sliverriver** [yunity/karrot-frontend#611]
**UPDATE**: current proposal is https://github.com/yunity/karrot-frontend/issues/611#issuecomment-327414400

---

I am not sure if the behaviour is correct and would a second oppinion about it : 

If i have a recurring pickup it is usually set for a day of the week . 
In this example it is thursday : 
<img width="392" alt="01 - recurring pickup" src="https://user-images.githubusercontent.com/2359021/30059341-0450d750-923f-11e7-98e4-4b78e7612923.png">

and it is shown in the overview
<img width="515" alt="02 - overview" src="https://user-images.githubusercontent.com/2359021/30059356-13693ade-923f-11e7-8064-fe8ae95f4fd3.png">

however - i can now manually change one entry - example to wednesday 

<img width="547" alt="03 - wednesday overwiew" src="https://user-images.githubusercontent.com/2359021/30059383-36fbe79e-923f-11e7-88f9-4ebea30e6cdb.png">

in the recurring overview it shows now the 6th - which is a wesdnesday. 
<img width="346" alt="04 - new recurring" src="https://user-images.githubusercontent.com/2359021/30059395-4ae4ad40-923f-11e7-8d22-061fa7dc2d73.png">

it sort of "breaks" the recurring idea. 

if i change the day to friday - all other dates change - except for the manually overwritten one. 

<img width="346" alt="05 - change to friday" src="https://user-images.githubusercontent.com/2359021/30059458-7ded0a70-923f-11e7-8026-aeb82fccb883.png">

--- 
is that the correct behaviour we want ? 

even if i change the single entry back to the defined day for the "recurring set" it doesn't move with the set, if the set is changed. 

---

maybe somehow make it visible that this entry has been manually changed ?
remove the manual change somehow so it is part of the set again ?

---

what do you think ?

**Comment by tiltec** [comment]
Yes, I made it behave like this. Maybe there are better solutions though.

Rationale is: if the user changes a pick-up, he has a reason for this. Don't let those changes be overwritten by a series change.

What is your expected behaviour?

- highlight that the date field is not overwritten by the series anymore, as you mentioned
- offer a button in the pick-up edit window "reset to series default"
- offer a button in the series edit window "overwrite changes in individual pick-ups"

Note, the _is-edited_ state is stored per field and not per pick-up. Thus above changes would need to be multiplied for the fields "date", "max collectors" and "additional information".
FYI, this is stored here: https://github.com/yunity/foodsaving-backend/blob/729efb028db30c5badd2f369c050046f475f9090/foodsaving/stores/models.py#L193

**Comment by Sliverriver** [comment]
from my point of view having the possibilty to "reset" it to be part of the series again should do it. in the recurring listing of the date. 
that would be the functionality that i was missing when i was playing around.

**Comment by tiltec** [comment]
So this one would be your preference? 

- offer a button in the pick-up edit window "reset to series default"

**Comment by Sliverriver** [comment]
yes. 

are there any other oppinions about this ?

**Comment by nicksellen** [comment]
I think it's most important to just to ensure the user understands what will happen, there will be many things user want it to do, and in the longer term we could implement more questions/options, but for now just being clear on what it does now would be useful (I am never quite sure myself).

**Comment by tiltec** [comment]
@brnsolikyl reported

> This is a possible bug, that I tried in different groups in dev and production. When I change the additional information field with a new text in a series of pickups and save it, the pickups that have already someone signed up to do not change. This is how you can test:
> 
> - Create a series of pickups, add a text to additional information for the whole series
> - Join one of more pickups
> - Go back and edit the series of pickups and change the text in additional information, then save
> - Every pickup should be updated with the new text, except for those where a user joined

> Updating the individual pickup worked for me.

**Comment by tiltec** [comment]
I'll merge this into #611
