### ISSUE TITLE
Join backend and frontend repositories together

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#613]
Our code is currently spread out in three repositories. I had the idea some time ago to join them together, it came up again with the addition of end-to-end tests. End-to-end tests are a lot easier to manage if all the tested code is in one repo, e.g. when the common API changes.

Other advantages are: one common issue location, a lot more commits in the repo 📈 

Requirements for actually doing this:
- frontend and backend development should be possible independently, e.g. no frontend dev should be forced to setup the backup
- deployment should still work nicely
- no resistance from devs

**Comment by nicksellen** [comment]
4 repos, the docker one too.

**Comment by tiltec** [comment]
Things to think about:

- only run frontend tests in circleci when a frontend change was detected, vice versa for backend
- do tools like pyup.io and greenkeeper get along with requirement files in subdirectories?
- transifex config needs adapting

**Comment by tiltec** [comment]
In order to preserve as many links as possible, I would push the united repo into the on that is `karrot-frontend` now and rename it to `karrot` Github will take care of the redirect.

`karrot-frontend` also has the most stars :)

All remaining issue in `karrot-backend` will either be closed or transferred to the combined repo, with a `backend` tag.

**Comment by mr-kojo** [comment]
Some advantages of the current solution (separated repos):

- It's easier for new developers to get started. For instance, a new frontend developer isn't confronted with backend code, issues and documentation.
- It's easier to keep track of changes made by other developers that work on the same code base. For example, if I pull the backend repository, I'll directly see what has changed have been made since my last pull.

I personally prefer the current solution although I don't have much resistance against the combined repo solution. I've never had to configure integration tests so far so I can't tell how much of a benefit the combined repo solution would be in this regard. So if you think it's worth the effort, go ahead :)

**Comment by tiltec** [comment]
> It's easier for new developers to get started. For instance, a new frontend developer isn't confronted with backend code, issues and documentation.

That's quite important to me, but I think having separate repos makes it actually harder to dive into the project because information is split out into different repos, milestones and issues. For example, the roadmap and release milestone only exists in the frontend repo.

Your dev workflow should stay the same when you are working backend only - just start your IDE in the `server` directory and you won't be bothered by all the frontend files. git command also work when you are in the `server` directory.

Documentation is actually another interesting topic. Since the frontend rewrite in September 2017, we started collecting docs in the frontend repo and deployed at https://docs.karrot.world/
This is also intended for back-end documentation, I already added the backend introduction there. It's quite nice to have a central location to describe guidelines and concepts for the whole karrot project.

Regarding confrontation with issues: I think that's strong argument to consolidate and close issues, in fact I would aim for less then 40 issues for front- and backend combined.

The more I think about it, the more I like the idea of joined repos ;)
- allows atomic changes to both at the same time
- it saves us from having to assign version numbers to front- and backend for running end-to-end tests consistently
- by integrating docker into the repo, it's easier for other groups to self-host

**Comment by nicksellen** [comment]
I am happy to follow/support your enthusiasm for combined repo. It's always a tough call though and each project has unique considerations.

**Comment by tiltec** [comment]
I'm motivated to tackle this in the next days/weeks, as the number of open pull requests is quite low in the moment.

**Comment by tiltec** [comment]
Further reason to merge repositories: translation strings could be reused if we manage to use PO files in the frontend.

**Comment by tiltec** [comment]
I'm not motivated to push this and there's also not soo many benefits, so leaving this aside for now.
