### ISSUE TITLE
Do the best thing with webpack dynamic import commons chunk stuff

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#617]
At the moment if two pages use the same massive library, each page chunk will have a copy of the library. This might not be bad, as it still makes the main page load fast, but I think there is a way it will do some cleverer logic in the future.

The discussion about it is https://github.com/webpack/webpack/issues/4392 and a WIP PR is https://github.com/webpack/webpack/pull/4255. Just will follow them and see how it goes.

**Comment by nicksellen** [comment]
I think the current behaviour is ok now I added an async commons chunk thing and we removed a few bloated deps.

**Comment by wbern** [comment]
@nicksellen could you elaborate for the rest of us struggling with this?

**Comment by tiltec** [comment]
@wbern 
This might be the relevant bit: https://github.com/yunity/karrot-frontend/blob/281420ebece873bdef37bfdffbd00a63d98fa332/build/webpack.prod.conf.js#L87

It joins some commonly used async imports into one file (`0.<hash>.js`): https://karrot-dev.foodsaving.world/bundlesize.html

**Comment by nicksellen** [comment]
Yes, indeed. The plugin I added (in addition to existing vendor and manifest CommonsChunkPlugin's) was:

```js
new webpack.optimize.CommonsChunkPlugin({
    children: true,
    async: true,
    minChunks: 3,
}),
```

With: http://nicksellen.co.uk/upld/bundlesize-with-async.html
Without: http://nicksellen.co.uk/upld/bundlesize.html

I don't know what it will do when https://github.com/webpack/webpack/pull/4255/files is merged, but I am happy with current behaviour now.

Need to write some actual application code instead of just webpack configs ;)
