### ISSUE TITLE
[Megalist] Steps before quasar branch is production-ready

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#619]
## Design/UI related

- [x] implement forgot your password UI
- [x] make the wall look sexy
- [x] implement the verify your email address view (the one that the verification email sends you to)
- [x] implement the page to send out group invitations
- [x] on the desktop group detail menu thing, implement the corresponding pages for the buttons:
    - [x] edit group
    - [x] invite users
    - [x] show public group info
    - [x] leave group (with a confirmation dialog or something)
- [x] make pickups page have all the features
    - [x] join/leave
    - [x] display users
    - [x] display full/empty
    - [x] display store (if on group page)
- [x] implement store create
- [x] implement check/manage pickups UI/UX
    (have a bit of a rethink about how the existing thing works, and decide after that)
- [x] make the group/store descriptions not be as big as a book if they put a book in the field
- [x] settings page
    - [x] edit details (name, description, etc...)
    - [x] make sexier, 
    - [x] resend email verification button/dialog/whatever
    - [x] Change password
- [x] mobile view
    - [x] hide all the buttons when you are not logged in (splash screen thing)
    - [x] store page have white background (make it clearer that you can click things, maybe it's too small, well, basically rejig the a bit to make it nice)
    - [x] mobile pages makes the footer hide sometimes if it makes the address bar hide (not reproducable for Lars)
    - [x] add logout on sidenav
- [x] mobile footer buttons do not become active when on the page
- [x] A Store list Background
- [x] Fix margins in mobile wall
- [x] Make Footer color nicer
- [x] Link Hover-color should not be primary
- [x] Manage Pickups button 
- [x] Pickups: remove buttons
- *Pickups "slots" ui*:
    - [x] when there are >1 available slots, it looks like I can freely choose which one to go in, could have only the next available slot look available, the rest greyed out
    - [x] ordering, when I join a pickup and somebody else is there, I end up first! I guess these things aren't explicitly ordered, maybe they are somehow always reversed ordered so doing .reverse() would JustWork
      (...potentially we need to add an explicit join model in the backend so we can order by signup date explicitly)
- [x] bug: https://karrot-dev.foodsaving.world/#/group/1/store/2/pickups
    1. load that page
    2. select a different store on the left
    3. press "pickups" on the bottom menu
    4. changes the store back to my original one
- [x] Empty Pickups Message: Use correct singular / plural version
- [x] Profile pictures are not always shown on pickuplist
- [x] Add groupPicker somewhere
- [x] users should be hidden on groupMap usually (or bounds should be calculated without users)
- [x] when on store page, highlight store (opacity, move?, zoom? on the map
- [x] Add right meta info to pages (which ones?)
- [x] check breadcrumbs
- [x] add all UI components to storybook (some are missing, e.g. user page)
- [x] display a loading thing after sign up (when it loads group data)
- [x] make language selection available in logged out views (group gallery, group info, login, signup)
- [x] put a carrot on the login page?
- [x] add in our beta/ liability warning... like on existing one (maybe just on signup)
- [x] fix: login form shakes on initial load
- [x] add a join pickup confirmation step (maybe a nice friendly message, perhaps show the other users, try to make them be nice responsbile foodsaving citizens), and when leaving ("are you sure the other people can reaaaaaaaaaaaaly do this withou you")

## Store & Logic - Related

- [x] make sign up process basically work
- [x] make sign up page only available when logged out
- [x] implement forgot your password logic
- [x] implement the verify your email address view (the one that the verification email sends you to)
- [x] implement invitation stuff in frontend (ask tilmann for more details)
    - [x] implement the page to send out group invitations
    - [x] accept invitation via link from email (has to do a bit of logic, look at angular frontend for info)
- [x] implement history pages (group/store)
- [x] ... and also write new wallpost message
- [x] group description page should have private description, not public
    - [x] select group needs to make sure to use the get group info from the api and store it seperatrelye from the list of public group info
- [x] add lots of tests
- [x] make some of the naming/conventions more consistent
    - [x] have actions not pass options in object, just pass in value (but keep mutations as objects)
    - [x] index all stores by id, and have id list (make helper for it)
    - [x] make sure all components can work in storybook and work in tests
- [x] try and find a way to make the no router-link erros
    - [x] in storybook could probably just define a global one on Vue
    - [x] the jest stuff SHOULD make it possible to stub it, but couldn't find out how
- [x] error handling
    - [x] http error handling (toasts?)
    - [x] redirecting and sutff
- [x] loading stuff
    - [x] show API loading
    - [x] general request loading stuff?
- [x] fix the websocket updates, not sure what happened there...
- [x] make topbar search autohide? (click elsewhere, press esc), add keyboard shortcut to open search
- [x] implement pickup feedback page
- [x] find a place to start putting site/branding customization options, first field "site name", default to foodsaving worldwide
- [x] currentUser is not set after login (reproduce: 1. logout 2. refresh page 3. login 4. see pickuplist in store with pickups you are part of)
- [x] make group map "reset bounds" (overview button work) or remove it if you can't be bothered
- [x] Fix route on profile page
- [x] add sentry/raven error reporting (Just before production?)
- [x] make e2e tests (testcafe) work with mocks backend or real backend
- [x] check for problems: user doesn't have currentGroup set and visits a non-group page (e.g. user page)
- [x] upgrade postcss-loader to > 2.0.0 (currently breaks yarn dev, PostCSS config not found)
- [x] upgrade vue to > 2.4.0 (breaks quasar, awaiting PR merge https://github.com/vuejs/vue/pull/6322 )
- [x] upgrade vue-loader to > 13 (break yarn dev, Failed to mount component)
- [x] groupInfo / group join: handle wrong group password, also when the user has to sign up in between
- [x] redirect to current group after login (not groups gallery)

## Question / Waiting

- [x] when logged out make header go away, or just remove the buttons that don't make sense (Should there be a toppar anyways, or just a splash screen?)
- [x] keep track of the issue on vuex-conenct that prevents us using slots (then move the OPEN SIDENAV button back to its rightful home)
- [x] consider general approach for form/dialogs/steppers/etc (maybe with vuelidate?)
- [x] try and unify between desktop and mobile the active "action menu" for the current item (either group or store) - they will be different components, but the same logical structure
    - [x] ... and similarly the "site action" menus (the top right on desktop, and sidenav on mobile)

**Comment by nicksellen** [comment]
>  the jest stuff SHOULD make it possible to stub it, but couldn't find out how
I created a global component that you can register globally... good enough I think

**Comment by nicksellen** [comment]
>  the jest stuff SHOULD make it possible to stub it, but couldn't find out how

... and even better I use `createLocalVue` now from the vue test utils

**Comment by nicksellen** [comment]
https://github.com/vuejs/vue/pull/6322 was merged 6 days ago now :) ... but does not seem to be part of a release yet https://github.com/vuejs/vue/releases

**Comment by tharun323** [comment]
@tiltec, @nicksellen , @D0nPiano , @NerdyProjects , @jeromechrist    I am the new enthusiast  , i would love to contribute to the project ! I m new to the open source field , will anyone please help me where to start ! btw i knew I am good at web development !

**Comment by nicksellen** [comment]
Seems https://github.com/vuejs/vue/pull/6322 should be fixed in latest version now so can upgrade hopefully...

**Comment by nicksellen** [comment]
Ah, you did it already. Oh, and ticked it. Brain/eye combo not working.

**Comment by nicksellen** [comment]
Finished! (sort of). In this case "ticked" means either a) it is done, or b) I have created a seperate issue for it. So, very soon we will switch quasar branch to master branch and resume a pull request workflow.
