### ISSUE TITLE
Frontend rewrite migration and project info page launch

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#624]
As there will be quite a few changes coming up in the next months, I'd like to outline them in here. First of all, we have the frontend rewrite (based on #593) that is coming along well and I suppose that once #619 is done we can ask existing users for feedback and then deploy to production afterwards. About the same time, we want to publish a new project info page #601 to foodsaving.world.

I can think of the following tasks/metatasks right now:

- [x] work on karrot rewrite tasks towards usable state #619 
- [x] decide on karrot instance URL (app.foodsaving.world was proposed already): https://pad.disroot.org/p/foodsaving-world-karrot-instance-domain
- [x] deploy production backend with channels enabled
- [x] ask existing karrot users for feedback about new frontend beta, announce everywhere (existing foodsaving.world page, blog, slack)
- [x] place g0v sponsor logo on a public page (talk with @stefan-fstaiwan)
- [x] check state of [project info page](https://github.com/yunity/foodsaving.world) and gather tasks to be done before launch -> https://pad.disroot.org/p/foodsaving-world-infopage

**Comment by djahnie** [comment]
Did we decide on where to put the karrot-devblog yet?

**Comment by tiltec** [comment]
There's a new proposal to put the karrot instance on foodsaving.today

>     Pro: The app is being used for daily foodsaving business today. This instance is part of a worldwide movement that includes other foodsaving hubs around the world.
>
>    Con: Confusing for those that got used to the blog being at foodsaving.today and the karrot instance at foodsaving.world
>
>    Leaves open the question, where does the karrot development blog best fit in? foodsaving.world/en/karrot/blog is a possibility place for that, while foodsaving.world/en/blog could be the blog that is now still on fs.today

**Comment by tiltec** [comment]
Domain is karrot.world per https://ukuvota.world/#/app/33062755-7968-b8af-a375-22456bbd0622/results
