### ISSUE TITLE
add store status

### ISSUE THREAD

**Issue by alangecker** [yunity/karrot-frontend#628]
- [green] in cooperation
- [yellow] in negotiation
- [red] don't want to cooperate
- [none/grey?] archived

## Steps
- [x] implement in the backend
- [x] add dropdown to form
- [x] colorize markers in the map
- [x] add colored points for each store to the store list

**Comment by tiltec** [comment]
What do you think about solving the "delete store" use case also via status? Current solution is not good (and not exposed in angular frontend), as the history component doesn't show any details about deleted stores and undo is not possible.

So my proposal is to add an "archived" status. These stores can be ignored in search and listings etc

**Comment by tiltec** [comment]
@alangecker are you motivated to finalize #681 in the next days? Otherwise I'd move this issue to Release 5.
