### ISSUE TITLE
Improve wall UI

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#635]
(aka _make the wall look sexy_)

See https://github.com/yunity/karrot-frontend/pull/630 and https://github.com/yunity/karrot-frontend/pull/634.

**Comment by nicksellen** [comment]
A few bits of feedback on the current (list) look:
- name is more prominent than message
- looks like a list.... (rather than wall messages) (meaning maybe they should be seperated?)
- each message has a hover highlight, but doesn't have any functionality
- the wall input is a bit detached from the messages (narrower, has shadow), could be made part of list?
- ctrl+enter to submit broke

**Comment by tiltec** [comment]
I removed the hover highlight in https://github.com/yunity/karrot-frontend/commit/08d33ca0bc752f055ace4f13e58871e99c04faa2
