### ISSUE TITLE
Sometimes hover colour makes text/buttons disappear

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#637]
Have a look at the logged out header, then hover over the LOGIN button... it will mostly disappear...

![screenshot-2017-10-27 all groups karrot](https://user-images.githubusercontent.com/31616/32104978-14927cca-bb27-11e7-8ba8-da4852e7b27d.png)

**Comment by tiltec** [comment]
I fixed it by applying `class="text-white"` to router-links on primary background. Seems a bit hackish to me, maybe there's a better general solution?
