### ISSUE TITLE
Make e2e tests work with real or mock backend

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#642]

**Comment by tiltec** [comment]
Had a discussion with @nicksellen yesterday. There are two difficulties regarding the e2e setup:

1. how to serve the frontend to the test client
2. how to handle API requests

The simplest solution for (1) seems to be to run a Express server with the built files (output of `yarn build`).

For (2), an approach with low initial overhead is to respond to API requests in the Express server. Later on, the API requests should get proxied to a real backend, running inside docker-compose or so.
