### ISSUE TITLE
Handle group join password when logged out (or remove)

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#644]
At the moment when you are logged out you can join a group with a password, you get redirected through the signup flow, but if you got the password wrong this isn't really handled well.

This is quite complicated state stuff to keep around, and is fragile without tests, so one option would be to remove this possibility. Alternatively to implement it so it works :)

**Comment by tiltec** [comment]
I think the best option is to go back to the groupInfo page and show an error in the password form.
