### ISSUE TITLE
Add group/store context menu on mobile

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#645]
There is a menu on desktop:

![desktop](https://user-images.githubusercontent.com/31616/32105744-c8e51dde-bb29-11e7-9085-ae6f8bf672e5.png)

But these things are not available on the mobile view right now, there were two ideas to add this:
- 3 dots in the header which opens a menu
- extra tabs (they will scroll), alongside Wall, Description, History, ...

![mobile](https://user-images.githubusercontent.com/31616/32105873-56376b38-bb2a-11e7-801d-15f7d2528848.png)

**Comment by tiltec** [comment]
This seems high priority to me as it makes the mobile page pretty limited.

I think I would like the extra tabs solution, but maybe it looks horrible ;)

**Comment by tiltec** [comment]
I'm going for a minimal solution to make the page more usable on mobile.
