### ISSUE TITLE
Add conversation to stores

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#649]
Need to add to backend and frontend. Should be able to reuse most code.

**Comment by brnsolikyl** [comment]
That will be very useful for us! 

A bit off-topic: I wonder if there's any issue open where you discuss the idea of users being able to bookmark stores, so that in the future the pickups of those stores could be displayed first and also notifications for new messages on store walls. That's surely a low priority for now but could be significant in case groups grow in size and add many stores with regular pickups.

**Comment by NakitaOza** [comment]
Could you please elaborate on this issue? What is the expectation in details. I am planning on working on this. :)

**Comment by tiltec** [comment]
It's about adding conversations to stores, similar to the group conversations (used in the "Wall" component in frontend).

![image](https://user-images.githubusercontent.com/4410802/38304189-d16a0954-3808-11e8-9792-c8799eca62b3.png)

That's quite a big thing for getting started though, did you already work with Django REST framework and/or VueJS by any chance? How much time do you have available?

**Comment by NakitaOza** [comment]
I have some experience with DJango/Python. I haven't worked in VueJS yet. I can spend 5 hrs a week on this.

**Comment by tiltec** [comment]
Cool! So I would suggest to focus on the backend part. Did you already have a look into karrot-backend codebase?

**Comment by NakitaOza** [comment]
So i did the below steps in the below order : 
1. git clone https://github.com/yunity/karrot-docker.git
2. cd karrot-docker
3. git clone https://github.com/yunity/karrot-frontend.git
4. git clone https://github.com/yunity/karrot-backend.git
5. docker-compose up -d
6. docker-compose exec backend ./manage.py create_sample_data      //in karrot-docker folder

For the 6th point i get the error : No container found for backend_1

I am on Windows 7 and i am using docker quickstart terminal for the above commands.

Can you please help me to solve this?

**Comment by nakita-oza-incontact** [comment]
Setup is complete. Will start to work on this issue. Thanks! :)

**Comment by NakitaOza** [comment]
Setup is complete. Will start to work on this. Thanks!

**Comment by tiltec** [comment]
Maybe it can be coupled with #986.

**Comment by tiltec** [comment]
I'll close this in favor of #986
