### ISSUE TITLE
Add localeSelect to settings menu

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#669]
It has more details than the existing one in the settings menu (translation progress, link to transifex), so would be good to use it there too.

![image](https://user-images.githubusercontent.com/4410802/32171929-19e9e3b6-bd7a-11e7-82f0-17022e593aa6.png)

Problem is that the button to open the popover doesn't fit very well into settings menu. A bit of UI rework could be nice.

**Comment by nicksellen** [comment]
Now it's always in the header, I think we can remove it from the settings page no?

**Comment by nicksellen** [comment]
... or maybe I'm forgetting mobile

**Comment by tiltec** [comment]
yes, probably makes sense to remove it from settings for now.
