### ISSUE TITLE
Display membership roles in UI

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#670]
Idea is to include it on the group members page https://karrot-dev.foodsaving.world/#/group/6/members

**Comment by tiltec** [comment]
Seems to be connected to having minimal admin roles.

**Comment by nicksellen** [comment]
They exist already! Check the API response for getting group info, has "memberships" field or something like that iirc

**Comment by tiltec** [comment]
I raised the priority of this issue to Release 5 because the other "minimal admin roles" issues are in there. I think we need to show the membership roles when group agreement have an effect.

**Comment by tiltec** [comment]
Stepping down from this because it seems to go into the wrong direction. My thinking is that we should allow group members to self-select roles that gives them certain rights and require explicit approval from other group members (one, some or all) if the action has big effects.

**Comment by nicksellen** [comment]
We realised we have some uncertainty about the approach to take with roles and permissions, and this task is a bit too concrete for now.
