### ISSUE TITLE
Add person-to-person sharing ("food baskets")

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#672]

**Comment by tiltec** [comment]
Similar to foodsharing.de, a feature where one person can say "I have food left over, who wants to have it?" and others can reply to it.

Detailed decisions are not made yet, but to give an overview:

- each offer should have a location and be shown on a public map.
- offers should expired automatically after some time
- notifications could be sent out to potentially interested people (e.g. nearby)
- a feedback system could be nice, to say if somebody didn't show up or everything went nicely

**Comment by tiltec** [comment]
@nicksellen is quite interested in it and I'd find it great too.

Here's what I wrote:
> person-to-person food sharing ("food baskets") would be a fitting addition so that people don't have to use other platforms for sharing food. It would also be a huge plus if new visitors arrive on the website (or the app) and can see the food baskets.

**Comment by varsha6319** [comment]
Can you elaborate on the issue so that I can contribute to it

**Comment by tiltec** [comment]
As you're new to the project, I'd be interested in how much time you have to contribute? I think it might take several weeks of development until the first version can be released.

If you feel up to it, I think the best way forward would be to have a call about it. @nicksellen would you be interested to participate as well?

**Comment by varsha6319** [comment]
I have applied for RGSoC 2018, So I have much time to contribute to it. 
Call would be a great option @tiltec 
Will I mail you my skype handle?

**Comment by tiltec** [comment]
I'll talk with @nicksellen and then come back to you. We're currently working on other topics, so it might take some days.

To get you started, you could already do market research and get familiar how other foodsharing apps work, for example https://olioex.com/

**Comment by tiltec** [comment]
This feature seems rather decoupled from other karrot features and relatively low priority, but it seems worth implementing in the next year or so.
