### ISSUE TITLE
Profile pictures

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#673]
A few things to consider:
- [x] backend general file upload and storage
- [x] photo resizing (thumbnail stuff)
- [ ] making sure we are not an arbitary file server for people on the internet (or maybe that is fine)
- [x] frontend display/edit

**Comment by djahnie** [comment]
I'd loooove to have this... :3 
Would add a lot more personal atmosphere to the tool if you ask me...

**Comment by tiltec** [comment]
> making sure we are not an arbitary file server for people on the internet (or maybe that is fine)

What scenarios are you thinking of @nicksellen ?

**Comment by tiltec** [comment]
Mostly done with #842
