### ISSUE TITLE
Create mobile app

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#674]
Using cordova... https://github.com/yunity/karrot-frontend/pull/648

Only android support for now (because we don't have macs available).

**Comment by ReneCode** [comment]
That would be a good opportunity to use / learn [react-native](https://facebook.github.io/react-native/)

**Comment by tiltec** [comment]
I really like the approach of react-native, however I feel like we don't have enough manpower to maintain everything. 

Are you interested in taking stewardship of developing a mobile app using react?
That would probably also include some redesign, a different UX and getting feedback from prospective users. The backend part is mostly done and I'm happy to work on backend features that are needed for a good app experience.

**Comment by tiltec** [comment]
> Thank you for your confidence. But taking stewardship ist currently much to challenging for me. (I’ve no real experience in react - only some learning courses. Also I’ve never published an app to andriod play store / ios-store.) sorry, but I don’t want to promise something that I can’t keep.

Thanks for the honest response! Then I guess the best way forward is the hybrid cordova app, optimize the mobile views more. In future, we can try out Weex, which is to Vue what React-Native is to React.

**Comment by nicksellen** [comment]
I would like to think about what we need to do before making a low-key production release of the cordova mobile app. I've been using the one that points to the dev server for a while now (randomly clicking around), and seems reasonable.... so:

- [ ] show a big carrot IMMEDIATELY when you open the app (slack does this, but with the slack logo of course), whereas ours shows a plain white screen it it feels broken
- [ ] consider whether to add in some offline handling (what would it do? show a banner at the top? I would not want to add proper offline data storage management yet, so just not make it look totally broken when you are offline)
- [ ] (re) attempt to make android builds via circleci (not essential as I can build them on my laptop)
- [ ] need a little way to switch between dev and production cordova environments (I have a little symlinking setup already, but not perfected yet, basically it's nice to change the config.xml such that you can install the production version at the same time as the dev version, and for them to use different fcm accounts, and maybe other things)
- [ ] see if we can find someone who can work on the ios side of things
- [ ] see if we want the push notifications to be different to how they are at the moment (1 tag per conversation, shows "<group> / <last message author name>" as the title, and "<last message content>" as the body
- [ ] consider if we need to do anything different on the backend to not make the websocket connections go all crappy (had loads of inactive channel subscriptions in the db, and it was trying to send to all of them, then breaking/delaying websocket sending a lot, we send a ping/heartbeat from the client now and filter them by how recently they ping'd, but still do not clear out old ones, there is a command to do it....)

**Comment by nicksellen** [comment]
For the offline handling, could perhaps abort all requests by intercepting them and checking if we think we are offline, then silently ignoring them (plus show banner at the top). OR fancier would be disable all inputs, but sounds a bit more work and painful (at the moment you get loads of piled up "server error" toasts).

**Comment by tiltec** [comment]
How do we handle updates? I think it's important to inform the user when a new version is released, and show a version number to them.

**Comment by nicksellen** [comment]
Maybe just putting on f-droid is enough for updates? I'm really thinking quite beta version here, where users are more responsible for managing the app.

For _real_ users I would think we do whatever we have to do to get it in the play store.

**Comment by nicksellen** [comment]
f-droid inclusion policy says:

> We cannot build apps using proprietary tracking/analytic dependencies like Crashlytics and Firebase.

Not sure if that means we can't use fcm with f-droid.

https://f-droid.org/en/docs/Inclusion_Policy/

**Comment by tiltec** [comment]
Oh, forgot about that! Yes, they don't want to include them in their build setup or something like that. That's also the reason why Signal is not available there. I guess we then just ship an APK from karrot.world and the beta-users have to update themselves.

**Comment by nicco11a** [comment]
Everyone wants a mobile app nowadays, but you end up with extra development work and for those that are aware of the environment (search e-waste and conflict minerals) and wait with upgrading our phones until it's impossible to continue it's not a option to install all those applications. First we run out of space and then we get the OS version mismatch..

I suggest that you work on the so called Progressive Web Apps (PWA), you can add those annoying popups, the GPS can be used, passwords can be saved in local databases and offline versions of the PWA can be stored like a icon and run against those offline databases so on so the question is, do you really need to make a native app on your smartphone anymore?

**Comment by tiltec** [comment]
I agree that adding PWA features would be nice, but the last time I looked (August 2017), most browsers/OS didn't support any notable PWA features and no browser/OS supported push notifications via PWA. The latter was the main reason why we decided to go with Cordova.

It seems a bit different now: at least Chrome and Firefox support push notifications in all OS except iOS: https://blog.goodbarber.com/Web-Push-Notifications-demystified_a866.html
On the other hand, Firefox doesn't seem to support the PWA manifest file yet: https://caniuse.com/#feat=web-app-manifest

Although it's already in development, I suppose that it might take a while until PWA push notifications land in iOS: https://webkit.org/status/#specification-web-app-manifest

Anyway, PWA features can be integrated in addition to having a Cordova app. I'm a bit limited on time though. Maybe you're up for working on that?

**Comment by tiltec** [comment]
Android app is continuously deployed to https://karrot.world/app.apk

The next step could be to publish it on some app store for automated updates. Google's Play store seem to have the most outreach, but we could start a bit smaller with alternative app stores to test drive the app.

F-Droid unfortunately doesn't work because we use FCM. Wolfi used https://www.aptoide.com/ before, but the page doesn't look very trustworthy to me.
So maybe directly go to Play Store? It seems to be possible to push directly from CI: https://github.com/codepath/android_guides/wiki/Automating-Publishing-to-the-Play-Store

**Comment by djahnie** [comment]
This issue is done, we should do some of the stuff that @tiltec described above.
