### ISSUE TITLE
Add conversations to individual pickups

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#677]

**Comment by tiltec** [comment]
This seems relevant because people requested a feature where they can notify their group about spontaneous cancellation of pickups. To fulfill this, the pickup conversations should be readable and writable by all group members, but only pickup collectors should be notified by default about new messages.

**Comment by tiltec** [comment]
Bruno from Solikyl requested this feature:

> We have pickups when we need more intense communication and that is unfortunately not available yet on Karrot, for example when we have big pickups and need to coordinate people loading cars in one place and people helping offload in other places, or when we have spontaneous pickups that require quick action. For now it's usually one of us calling around, but I know you have discussed features like conversations for the pickups. That, combined with push notifications, might do the job in the future. I just wanted to bring to your attention that this is a much needed feature at Solikyl and probably in any other foodsaving collective that is growing in size and activity.

**Comment by nicksellen** [comment]
Ok, I added a backend implementation. The frontend is a much bigger topic though. It might make sense to built it on top of https://github.com/yunity/karrot-frontend/pull/855. Or maybe not.

**Comment by nicksellen** [comment]
So it might be a sidebar thing like the slack thread UI will work well here. On desktop it would sort of sit over the top, and on mobile be a full page.

**Comment by nicksellen** [comment]
Here's a quick idea. It's the existing `<Conversation>` component (reversed) put inside a `<QLayoutDrawer>` on the right:

![pickupchat](https://user-images.githubusercontent.com/31616/41203437-24c19c54-6cd7-11e8-9b00-856a30c35336.png)

**Comment by nicksellen** [comment]
... and getting it a bit more refined ...

![pickup-conversation](https://user-images.githubusercontent.com/31616/41418782-c3699124-6ff0-11e8-9d35-08d4bdebf1e6.png)

**Comment by tiltec** [comment]
Done :)
