### ISSUE TITLE
History component is not reactive

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#678]
As all state is loaded via a `mounted` lifecycle hook, when the props change it is not updated. A simple way to recreate the issue:
- open https://dev.foodsaving.world/#/user/22
- switch the _22_ in the url to _222_
- notice the history entries are still for user 22

Possible solutions:
- remove use of vuex-connect and swap it for a simple wrapper component that can use watchers to refetch history data on props change
- revert to previous approach (stateful component that does not take props)
- checkout vue-router/vuex-connect docs to look at router update hooks to trigger data loading
- come up with another approach

**Comment by tiltec** [comment]
@alangecker are you motivated to work on this?
