### ISSUE TITLE
Sidenav Restructure Proposal

### ISSUE THREAD

**Issue by alangecker** [yunity/karrot-frontend#683]
![screenshot_2017-10-31_01-09-10](https://user-images.githubusercontent.com/10246027/32219585-eeb50a44-be2e-11e7-986a-78e74d71ce71.png)

## further ideas
- Store/User-toggles on top of the map on hover
- Maximize map button

**Comment by D0nPiano** [comment]
Is it meant to be the new sidenav for desktop?

**Comment by tiltec** [comment]
I like your work on this!

**Comment by alangecker** [comment]
![image](https://user-images.githubusercontent.com/10246027/32238769-0172dee2-be69-11e7-9e79-afe0a9a82e0c.png)

**Comment by tiltec** [comment]
This is quite important to me, maybe I'll have a try at implementing the design proposal. Would be happy about support :)

**Comment by tiltec** [comment]
This is being superseded by the experiment in #1047
