### ISSUE TITLE
Have the possibility to set a pick-up date without specific hour (or with start/finish)

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#709]
The association 'Essen für Alle' from Groß-Gerau is interested in using Karrot and started investigating its features. They pointed out that it's not possible to set pick-up dates without specifying the hour and would like that to be changed.

From the mails with EfA:
> Die Uhrzeit "ganztägig" trifft bei uns zu, da wir 2 Märkte haben, denen es egal ist, wann wir auftauchen. Das heißt, dass jeder dort flexibel abholen kann, wie es ihm passt. Bisher haben wir das so geregelt, dass wir 23 Uhr als Uhrzeit eingetragen haben, damit klar ist, dass man da nochmal nachfragen oder in der Beschreibung nachlesen sollte, weil 23 Uhr merkwürdig wäre. Aber eine Option,"flexibel" oder "ganztägig" oder etwas in der Art wäre natürlich praktisch.

I remembered that there were stores like that in Bilbao, too, and also the Kräuterfee in Wurzen is a similar case. Could definitely be nice to have! :)

**Comment by tiltec** [comment]
That reminds me of the "all day" functionality that most calendar applications have. But "all day" sounds not the right thing for this purpose, I guess the stores won't be accessible at 4am or midnight. Having a "start-finish" time sounds like the best solution for this.

I think it would be not too hard to implement, here are some considerations:

- the "start" date seems just for informational purposes, maybe it should be even possible to create a pickup where the "start" date is in the past?
- the "finish" date seems to say that afterwards the pickup is done (or missed), nobody can sign up for the pickup anymore

It seems to me that we could add an optional "start" (or "begin") date that is shown in the frontend, but doesn't have any additional functionality. The existing "date" would be used as the "finish" date if a "start" date is present.

**Comment by nicksellen** [comment]
Postgres has range types, and django supports them ---> https://docs.djangoproject.com/en/1.11/ref/contrib/postgres/fields/#range-fields. Could be nice!

**Comment by nicksellen** [comment]
... might also need another field to explicitly record whether a given pickup is either:
- turn up exactly at the specified time
- turn up any time in this period

... or perhaps keeping start/end fields is better, as if it only has a start then this kind of clearly means "turn up at that time"

**Comment by tiltec** [comment]
Bruno from Solikyl requested a feature similar to this:

> A period of time for setting a pickup is sometimes more desirable than a specific point in time (for instance from 2 pm to 4 pm instead of 3pm only).

**Comment by tiltec** [comment]
#1013 is a related issue


Original message from Unai:

> It would be great to have the option to set 2 mutually exclusive pick ups, meaning that there’s the chance to do it both for example on Thursday evening and on Friday morning, and the moment somebody signs up for one of them the other option becomes no longer available.

> It’s because the shop owners are happy if we do the pick up both at night or the next morning. There might be some foodsavers who can make it at night and cannot in the morning and viceversa. And this way we could offer both options.

**Comment by tiltec** [comment]
I guess this could be tackled when thinking about generalized pickups? #354

**Comment by tiltec** [comment]
Questions about this:

Having `start` and `end` should satisfy all requirements, or did I overlook something? Even if it's "the whole day", there are still opening hours.

Should it be allowed to join and leave after it started? Joining seems to make sense to me.

Should we restrict the duration? I tend to leave it up to the group to set a sane duration.

Also, Nicks questions from some posts above: Might be necessary to add another setting that specifies if it's necessary to turn up exactly at the specified time or any time in this period.

**Comment by brnsolikyl** [comment]
`start` and `end` are the basic parameters that are sufficient in my opinion. When we have a time span we usually write it on the comments field. If there's a preferred time in the period of time, one could also just write it down. It makes things simpler and more flexible than adding another setting to specify the time in the period. It's also a question for the UI to make things simple when defining a time, to make the specific time a default and just have something like a checkbox stating "Does your pickup have a time to end?" and make the option of setting the end-time available if the person checks the box, for example.

I don't think duration should be restricted, but then I wonder only how the pickup will be ordered in the pickup's list. Let's say we have a 3-day's pickup from the 7th to the 10th and now we're on the 8th. Do we take the `end` date as the reference point in relation to other pickups with specified times? I guess that would make more sense...?

I think there's no apparent reason why people should not be able to join the pickup when it is still ongoing, but leaving it is a tricky one. What about adding another setting to mark the pickup as done, would that complicate things a lot? Maybe marking pickups as done can be a good feature for all of the pickups, as a way to require some extra commitment and accountability from people in the group, to confirm they actually showed up?

**Comment by tiltec** [comment]
Now that @nicksellen implemented end dates for pickups, I guess we can close this issue.
