### ISSUE TITLE
Show distance between a user and a store

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#711]
The EfA people would like to have a feature, that displays the distance between a user and a store. They did nor specify this further.

Original phrase from the mail:
> Ist es möglich, eine Funktion einzuführen, die es ermöglicht, die Entfernung eines Mitglieds zu einem Markt aufzuzeigen?

I imagine it being only about the user that is currently logged in and being displayed in the store view in some kind of additional box e.g. beneath the map. It could say "Your distance to this store is xyz m.".

**Comment by tiltec** [comment]
I would need to get some more feedback on the purpose of this feature, otherwise it seems hard to implement in a good way.

**Comment by djahnie** [comment]
As discussed further with @tiltec, this could be a starter task as well:
- If we use a routing service we can make this super easy and simply link to it.

My idea of how it should look like:
- Add another of the green, round buttons (displaying fa-bicycle) right of 'manage pickups'
- The less fancy version would be a new tab opening, in which some kind of route planner opens, that shows the way from the home location of the user to the store.
- The more fancy version would be to have a pop-up displaying a map, that lets you calculate directions. The store location would be already set as goal and the user would be asked if their home or current location should be used as starting point. But I have to admit that I have no idea how complex this would be, as you'd need to access the gps of a mobile device and integrate the route planner directly into the karrot app. So I'd be happy with the less fancy version as well, if somebody wanted to work on that... ;)

**Comment by tiltec** [comment]
The starter task could be to add a button on the store page that links to a routing software. 

For example, OSM has this API:
`https://www.openstreetmap.org/directions?engine=graphhopper_bicycle&route=52.5%2C13.4%3B23.7%2C90.4`
where the last cryptic bit is `52.517,13.389;23.716,90.404` URL-encoded (`start;destination`)

**Comment by tiltec** [comment]
Maybe there's something in the Material icons? 
https://material.io/tools/icons/?search=directions&icon=directions&style=baseline

You can just use them, they're included already.

**Comment by pogopaule** [comment]
@djahnie Is it possible for me to get in touch with the EfA folks? They asked for a specific solution but I would like to get more information on the underlying problem they face. Plus I would like to show them my solution(s) to get a direct feedback.

**Comment by djahnie** [comment]
Yes sure! I can give you an email address @pogopaule, if you write me via djahnie@disroot.org. I'm certain that they will be happy to have someone working on their request! :blush:

**Comment by pogopaule** [comment]
@djahnie I presented an EfA representative the new feature. She was happy with it's implementation.
