### ISSUE TITLE
API documentation shows wrong URLs 

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#725]
https://karrot.world/api/ shows all URLs with invalid paths.

![image](https://user-images.githubusercontent.com/4410802/32697631-439aaa9a-c795-11e7-90f7-bbcfca6fb6a9.png)

Somehow it leaks out the deployment path. I don't know if this causes any problems, would need to investigate further.

(Backend/deployment issue)

**Comment by nicksellen** [comment]
Oh, interesting :/

**Comment by tiltec** [comment]
I tried to solve the problem, Djangos `reverse` method returns the wrong path. I looked into DRF as well, but the APIRootView and DRFs `reverse` method already get the wrong path as input.
I went back through our commit and requirements, but the problem persisted.

I guess it might be triggered by some deployment configuration.

Another hint could be that Swagger is partially broken for both master and production. On the other hand, the openapi response seems fine: https://dev.karrot.world/docs/?format=openapi

![image](https://user-images.githubusercontent.com/4410802/32699113-a02bedda-c7b0-11e7-97a6-6ed4a09fa07c.png)

**Comment by tiltec** [comment]
I'm not going to work on it further due to limited battery for now.

**Comment by tiltec** [comment]
Fixed by https://github.com/yunity/karrot-backend/commit/fa0b0d4df6622816f52c2c40df703675afe2076c and https://github.com/yunity/yuca/commit/423d3f887b0a40f95decb68b80e3fd90cb688095

**Comment by tiltec** [comment]
Swagger problem is fixed by https://github.com/yunity/yuca/commit/fdbcd583a52943db2e82e744d82baae09438104e
