### ISSUE TITLE
Rationalize loading of route-dependent data

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#726]
Currently it's a bit scattered around, some are loaded via `src/store/plugins/router.js`, [some via `mounted` lifecycle](https://github.com/yunity/karrot-frontend/blob/bdd7326c8edcc4dbbd017b994278a0223fe9d0a6/src/pages/Store/PickupsManage.vue#L167) or alike, and [some use `watch`](https://github.com/yunity/karrot-frontend/blob/bdd7326c8edcc4dbbd017b994278a0223fe9d0a6/src/components/History/HistoryList.vue#L35).

A common problem is that loading via `mounted` lifecycle is non-reactive to route changes when the component stays rendered. `watch` or `beforeRouteEnter` solves this problem, but it's not available when using vuex-connect, forcing us to write boilerplate. Loading with router plugin is a good solution, but it's detached from the page itself (coupling only via param id).

Ideally, we would load all data with `beforeEnter`/`beforeUpdate` hooks in the route definitions. I think the problem is that we can't easily use vuex there. Maybe we get inspired by how the breadcrumbs work, introducing a custom `resolve` object to the route definitions that runs in a router plugin.

**Comment by nicksellen** [comment]
Yes, I think introducing another custom meta property that can do some vuex stuff would be a nice idea. I guess it needs to be a function so it can make use of route params, although perhaps being able to specify by default as a simple string (for action triggering) would be nice.

**Comment by nicksellen** [comment]
Maybe a good approach is to remove all the complicated logic in `selectGroup` (and similar places) and put it into the routing logic and/or plugins, and maybe some changes to minimize cross-dependence between vuex modules.

I would like to get rid of things that look like procedural logic (fetch this, fetch this, fetch this, etc). It is more accurately expressed as declarative logic (when this changes, fetch this, when that changes, fetch that).

We want an approach that inherently works by design, not one that works by careful thinking about the ordering of statements.

**Comment by tiltec** [comment]
Declarative approaches sound like a good idea, usually they need a good understanding of the requirements to be powerful enough without allowing unwanted side effects though.

Maybe a list of actions that need to be triggered while loading could be enough? Ideally, they shouldn't depend on each other, so redirects and detection of route errors should happen before. It's a bit tricky since this can depend on resolved data.

At some point, we have to trigger the fetching actions. I guess it's best do to this in a router afterEach hook (or beforeEach if redirects are processed first).

**Comment by nicksellen** [comment]
There is some data which at the moment we always load (e.g. the pickups), as it gets used in quite a lot of places. This is normally/usually derived data from the active group (which is obtained from the route params), and to me makes sense to load it in our derived state plugin.

Other data is only loaded for a specific page (e.g. pickup series, or history). which then makes sense to load it based on the route, but if it depends on anything other than the route params it needs to have a way to reload.

Although as we get all the route params in the state too, perhaps it's _all_ derrived state (looks like the router sync also comes with the name of the route too [1]).

As a goal I'd quite like to be able to break up any complex actions (e.g. `selectGroup`) into various reactive registrations (register watcher/getter, trigger action).

[1] https://github.com/vuejs/vuex-router-sync/blob/master/src/index.js#L62

**Comment by nicksellen** [comment]
.... or perhaps we are better off not keeping so much state lying around in the client, so load the pickups as needed for display on the page we are on (per group, per store, etc). Which also makes the refresh problem go away. The cost is more requests and more waiting in the ui.

**Comment by tiltec** [comment]
I think it's a good approach loading all the data when they are needed by default, and additionally preload some frequently used data. If we use the precaching, the load action should check the last refresh date (stored in `meta` module) and only refresh when it's older than x minutes. I'd also love websocket push, but seems a bit more complex to handle the subscriptions (also offtopic for here).

**Comment by tiltec** [comment]
Maybe this would also be an option to handle route errors - if an `resolveData` hook returns an error, trigger an `routeError` hook.

**Comment by nicksellen** [comment]
Yeah, I would like to try and remove routing considerations from the actions, and this seems like it could help with that.

**Comment by tiltec** [comment]
I'll work on this for a bit
