### ISSUE TITLE
Pick-up comment layout

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#728]
I wanted to add more information to a pick-up series and found the field to do so pretty small:
![image](https://user-images.githubusercontent.com/17573771/32701504-8e6096d8-c7d7-11e7-8534-a9ca5e8634de.png)
 Also, I was disappointed that I couldn't add any formatting at all: No paragraphs, no boldness, no italics.

Use case is that the Wednesday pick-up is normally done by Villa Klug and the Friday pick-up by us. I wanted to add that to the pick-up info, while pointing out that this doesn't mean that the pick-ups are reserved for only us and no other people are allowed to join...

It's not very evident like this:
![image](https://user-images.githubusercontent.com/17573771/32701529-edd8d74c-c7d7-11e7-8694-c9606e619715.png)

**Comment by tiltec** [comment]
I'd make it a textarea and make it support newlines while rendering. 

I would maybe set a limit to 200 characters or so? Ideally there shouldn't be too many newlines either… maybe a text-truncate could do the trick.
