### ISSUE TITLE
Request additional IntelliJ licenses

### ISSUE THREAD

**Issue by mr-kojo** [yunity/karrot-frontend#743]
This might be interesting both for frontend and backend developers.

A note from @tiltec:

> We have 4 JetBrains all-product licenses, I think 3 of them are in use by me, @nicksellen and @NerdyProjects. So we should have one license left. I'm not sure how to give one to you though.
Generally it could make sense to ask for more licenses again, we had 8 during yunity times.

**Comment by tiltec** [comment]
The link to the form is here: https://www.jetbrains.com/shop/eform/opensource

**Comment by mr-kojo** [comment]
I requested a total of 8 JetBrains All-Product licenses. I will let you know as soon as I get a response.

**Comment by mr-kojo** [comment]
It has turned out that we actually have 6 licenses, of which 3 are currently unused. So there is no need to request more licenses. I'll use one of the remaining 3 licenses so we have 2 licenses left as a reserve for new developers.
