### ISSUE TITLE
Pickups from other stores are shown if page is loaded directly

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#746]
When I open https://dev.karrot.world/#/group/1/store/64/pickups, I see pickups that don't belong to the store.
When I navigate there by clicking on the store name in the side menu, it correctly shows the pickups of this store.

Correct pickups at this time:

![image](https://user-images.githubusercontent.com/4410802/32734068-3246e702-c891-11e7-9452-4ffd33823853.png)

**Comment by tiltec** [comment]
It seems that `selectGroup` and `selectStore` have a battle about clear/setting the pickups. `selectGroup` clears the pickups on load before fetching them.  `selectStore` sets the store filter, but the filter gets cleared by `selectGroup`.

I think both do the correct thing on their own, but it only works when `selectStore` runs after `selectGroup`.

I solved it by putting an `await` statement before `selectGroup` in the router beforeEach. This way we don't have to deal with this concurrency issue anymore, but I'm sure that we have many more issues like this.

We should find a solution to this in #726 

Vue Devtools wasn't helpful at all to debug this.

**Comment by nicksellen** [comment]
> Vue Devtools wasn't helpful at all to debug this.

I wonder why not? List of vuex mutations should have shown the order? And stepping back to different states should have shown the issue? And the vuex getters should have shown all the pickups?

**Comment by tiltec** [comment]
It had some delay before it captured the mutations. I didn't see the questionable mutation…
