### ISSUE TITLE
Remove messages that have been marked as translated by mistake

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#749]
I tried to be clever and pushed some translated files back to transifex when changin from angular to vue-i18n formatting. Unfortunately, this also pushed a lot of English strings and Transifex marked them as translated.

The task is now to go through all translated *frontend* strings in languages other than English and delete English messages in the "translated" field.
https://www.transifex.com/yunity-1/karrot/translate/

- [x] German
- [x] Chinese
- [x] Czech
- [x] Esperanto
- [x] Spanish
- [x] French
- [x] Italian
- [x] Russian

**Comment by djahnie** [comment]
Done.
