### ISSUE TITLE
Day of the week is not displayed anymore with pick-up dates

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#756]
Sylvia from EfA says that her members complained about the fact that the day of the week is not displayed with the pick-ups anymore but only the date. This is annoying to them because many have fix days of the week assigned and now need to use a calendar seperately to verify the day of the week.

Original mail:

> Dr. Sylvia Schneider (November 13, 2017 3:19 PM)
> To: djahnie@disroot.org
> 
> Hallo Janina,
> vielen Dank für Deine Antwort und das Besprechen bei den Entwicklern.
> Eine Übersicht über alle Slots wäre schon extrem wichtig für uns. **(This references #741)**
> Die Abholer beklagen gerade, dass auch der Wochentag nicht mehr sichtbar ist, sondern nur noch das Datum.
> (Die meisten Menschen, haben feste Termin an bestimmten Wochentagen. Ohne den sichtbaren Wochentag muss man einen Taschenkalender zu Rate ziehen, um den Wochentag zu ermitteln und sich einzutragen….)
> Vielen Dank und liebe grüße Sylvia

**Comment by tiltec** [comment]
How was it before? Can't remember exactly..

**Comment by SylviaSchneider** [comment]
In the former release date + weekday was displayed.
In the new relase only the date is visible. -> This is quite unconvenient. We need to check everytime, which day of the week it is. 
Even an abbreviation of the weekday would be sufficient and better than nothing.

**Comment by tiltec** [comment]
![screen shot 2017-11-15 at 17 20 20](https://user-images.githubusercontent.com/4410802/32847086-48bec416-ca29-11e7-96ae-1458fb5e7751.png)

I added the short weekday and removed the year name, it seems unneeded here.

**Comment by SylviaSchneider** [comment]
Thanks a lot for adding the weekday!!!
___
Is there also a possibility to see all pick-ups in our group, like it was before in the old release?
Since everyone in our group has the same rights to register for a pick-up and responsibility that, every store will be served, it is absolutely necessary for everyone in the group to have an overview of all pickups in the next weeks, not only the own pickups. Thanks a lot for taking care of this issue.

**Comment by tiltec** [comment]
Yes, that's possible, see #741 and #610 for more discussion on this. I'll add another comment in #741.
