### ISSUE TITLE
Mobile: Bottom bar hides page content

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#757]
* When editing a store there's no way to save the changes. The necessary button is probably hidden behind the botton bar?
* In the store view half of the pretty card which tells you that there are no upcoming pick-ups is hidden behind the bottom bar.

(Sorry I'm on the phone, so no screenshots)

**Comment by tiltec** [comment]
I can't reproduce this on Chrome for Android. It looks like this:
![screenshot_20171117-184731](https://user-images.githubusercontent.com/4410802/32961292-4993eb64-cbc8-11e7-9d4c-a3e4c1ed20d5.png)

**Comment by tiltec** [comment]
@djahnie 
Can you check again on dev.karrot.world if the problem still exists? Otherwise please close :)

**Comment by djahnie** [comment]
Looks great! 😊 👍
