### ISSUE TITLE
Fix websockets when using token auth

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#766]
Websocket does not work when using token auth (e.g. in cordova).

Backend task https://github.com/yunity/karrot-backend/issues/439

Once it's implemented in the backend, the frontend task is to send the token down (either as a header (preferred) or a url parameter)

**Comment by tiltec** [comment]
What's the status of this? I think backend is ready, did you implement it in the frontend too?

**Comment by nicksellen** [comment]
This works now :)
