### ISSUE TITLE
Update presence status

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#770]
The backend supports keeping track of prescence (is the user actually at the computer). This is to enabler smart decisions about whether to send push notifications.

It uses the websocket connection to update it, see [the tests](https://github.com/yunity/karrot-backend/blob/master/foodsaving/subscriptions/tests/test_consumers.py#L54-L66) for what to send.

Some of the following libaries/apis might be useful:
- https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API (if this is well supported could be good, although doesn't detect idling I guess)
- https://github.com/serkanyersen/ifvisible.js/
- https://github.com/defunctzombie/away

**Comment by tiltec** [comment]
Before adding more conversation types ( #677 #832 ) I would like to add this.
