### ISSUE TITLE
editMixin: keep user's modifications when enriched field changes

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#771]
Nick commented:

>We have to be careful here as enriched fields might change based on other data, and if it changed then it would cause the form to be reset and overwrite the users changes.
>
>The reason to have the watching in the first place is to get the updated data after saving to the server (other fields could have changed (or an id added in the case of creation)).
>
>One solution would be to store a changes object, so we can reset from value, then reapply any changes (where there should be none in the case of updating due to save, and some in the case of update due to enriched field change).

Need to investigate how to trigger the problem and how to solve it in a nice way.

**Comment by nicksellen** [comment]
> What would be a case where this behavior would get visible to the user? I can't think of any right now, it should only trigger during page load and after submit.

The issue was if you saved the form and got a server validation error, it would reset changes to other fields. I think it actually will still suffer from that, I somehow was thinking that the deep change check prevented it. If so, that is a bug.

**Comment by nicksellen** [comment]
Also, another impact now: when you press save, the value changes (as the status changes), the form resets, so the values all jump to the old value, then it's saved and refresh from the server, and they jump back again.

**Comment by nicksellen** [comment]
... load status also got broken, as the value changes, which triggers a meta/clear immediately.
