### ISSUE TITLE
Handle invalid token server response

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#777]
If you use websocket token auth (and probably normal auth too) with an invalid token, you get back a 403 error with `{ "detail": "Invalid token." }` (the drf code looks like it should have returns a 401, but something overrides it as it can't tell the client how to authenticate, see http://www.django-rest-framework.org/api-guide/authentication/#unauthorized-and-forbidden-responses).

The client should not continue to use this token as you can't do anything on the site :/

As we store the token in local storage these errors are returned for all pages, e.g. `/api/groups-info/` so it's that specific error we need to check for all requests, which might mean checking the detail message as otherwise I don't know how to distinguish it from other 4xx type errors which might be for that specific request. However, the drf code has that message in internationalization so might get back other languages. Need to think about it. Perhaps we override it with a custom response that contains a/the error code.

**Comment by tiltec** [comment]
Is this also valid for non-websocket requests?

**Comment by nicksellen** [comment]
No, either you have a valid session (= logged in) or you don't (= logged out). And the auth failures are handled when you login on the form. Whereas token auth is more like logging in again for every request so has to detail with those failures in the other places.

Although we could deal with in a simpler way, and just ignore invalid tokens on the server (as if they don't have a valid session). The frontend would still have a token, and keep on sending it, but it won't consider itself logged in just by having a token around. This might be a better/simpler option actually.

**Comment by nicksellen** [comment]
I would rather not have to make a custom token authenticator backend in drf, so I think it is best to handle it in the client, however, there is not much information returned from the API, so I added more (see https://github.com/yunity/karrot-backend/pull/445) which _should_ be enough to pick out those auth failures.

**Comment by tiltec** [comment]
Seems to be done.
