### ISSUE TITLE
Add a notice for unsupported browsers (Safari <9.1, IE <11)

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#786]
I think it would be helpful to inform users that their browser is unsupported by quasar and we can't do much about it except asking upstream for support.

This mostly about older Apple devices and older Microsoft browsers: http://quasar-framework.org/guide/browser-support.html

---

This is an example error that we get from unsupported browsers:
(It's an error in the quasar browser detection code, funnily. Maybe at least this error can get fixed upstream?)

https://sentry.io/foodsaving-worldwide/karrot/issues/408157538/

```
TypeError: 'undefined' is not a function
  at onResize (/js/vendor.54a0396f8b977e976cd2.js:11)
  at n (/js/vendor.54a0396f8b977e976cd2.js:1)
  at None (/js/vendor.54a0396f8b977e976cd2.js:11)
  at None (/js/vendor.54a0396f8b977e976cd2.js:1)
  at rt (/js/vendor.54a0396f8b977e976cd2.js:1)
...
(1 additional frame(s) were not displayed)
```

**Comment by Hardiki** [comment]
I am taking up this issue. @tiltec

**Comment by peterkshultz** [comment]
Makes sense. I had tried implementing it with `Vue.use` in `src/main.js`, but wasn't seeing the behavior I was hoping for there either.

Given the size of the bundle, I'll try another implementation so long as @Hardiki is no longer working on this.

**Comment by peterkshultz** [comment]
@tiltec: Given that older browsers don't support Quasar, it probably doesn't make sense to use one of Quasar's components (like a modal) to display the notice. 

Would a simple Javascript window `alert()` make sense?

**Comment by Hardiki** [comment]
Hi @peterkshultz, Sorry for the delay message, I am working on it, I have done some work on it. Will share the code with you soon.

**Comment by peterkshultz** [comment]
Sounds great @Hardiki !

**Comment by Hardiki** [comment]
Here is the link to my Github repo here I have a bit of code, hope this helps. https://github.com/Hardiki/browserdetect
