### ISSUE TITLE
Only empty pickups are listed in the main view

### ISSUE THREAD

**Issue by nicco11a** [yunity/karrot-frontend#791]
In the main view only lists empty pickups

![image](https://user-images.githubusercontent.com/8119306/33231359-86825fa6-d1f4-11e7-8454-b2440f95669e.png)

I have to choose a particular pickup to list the ones that are not full..

![image](https://user-images.githubusercontent.com/8119306/33231394-27437740-d1f5-11e7-99c5-3dc1cd08739a.png)

It would be more convenient to also show the none full ones in the main view, it's easy to miss pickups with too few participants otherwise.

**Comment by tiltec** [comment]
What do you think about the ideas in #741?

**Comment by nicco11a** [comment]
Did not know there was a similar issue, switching to #741.
