### ISSUE TITLE
URL of public group info doesn't work as external link

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#792]
Example foodsharing UIO:
When accessing the public group info via the group overview page at https://karrot.world/#/groupInfo it successfully leads to the public info page and displays the URL https://karrot.world/#/groupInfo/31. When reloading the page, as well as trying to directly access above-mentioned link one gets to this page instead of the info one:

![image](https://user-images.githubusercontent.com/17573771/33233213-92f6e900-d212-11e7-9ef2-1a513fe9e81f.png)

I tried another group and it was the same.

**Comment by tiltec** [comment]
Tried it on my phone and it works… maybe it fails under mysterious circumstances?

@djahnie, can you look into your browser console and see if there is something suspicious? Thanks!

**Comment by nicksellen** [comment]
I can re-create it here on my desktop browser (firefox), it fails every time. No console errors.

If I press the "TAKE ME HOME" (to the plaaaaaaaaaaaaaaace where I beelooooong, wwwwwest virgiiiiiniiiaaaaaaaaaaaaa, mountain mooooooooomaaaa, taaaake me hooooooooome, couuuuuntry roads. ahem) button, it briefly shows me the correct group info landing page, before going home.

I think the route error data is being set erroneously. Perhaps timing sensitive to the group info data loading.

**Comment by tiltec** [comment]
Interested how that can happen, don't we `await` the fetching of groups in main.js?

My laptop is over at the neighbour for charging (still no electricity here…), so I can't have a look myself.

**Comment by tiltec** [comment]
I fixed it the easy way in master without understanding all the details - I think some of the errors come from unclean separation between currentGroup and groupInfo stuff because they live together in the groups module, but have not much in common. I think it would be good to split them up...
