### ISSUE TITLE
Add possibility to remove user from group

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#798]
As requested by Sylvia.
The possibility to remove toxic people from their group is very important to the EfA people. An idea against abuse is to require multiple users to agree on kicking another one. Another way would be classic admin roles.

Original point from mail:

> Mitglieder löschen zu können
> (falls wir jemanden eingeladen haben, bei dem sich herausstellt, dass er nicht die besten Absichten hat, dann können wir ihn derzeit nicht löschen.
> Wenn Ihr Bedenken habt, dass diese Funktion missbraucht werden kann, dann könnte man ja z.B. erst die Löschung umsetzten, wenn 2 Personen die Löschung anklicken. Das würde dann bei uns 2 Vorstandsmitglieder machen…)

**Comment by djahnie** [comment]
Sylvia put emphasis on this again and stated, that it is of vital importance to protect a group from users going rogue. (I have to add that my personal experience with foodsharing Bielefeld also provided a case, in which a user suddenly became toxic and needed to be removed.)

Since not everyone should be able to randomly kick users, this issue touches #550 and #356.

How can we make sure to have groups of equals, while still making sure that destructive individuals cannot bring a whole group to ruin?

**Comment by SylviaSchneider** [comment]
We need the possibility to delete a toxic member, to make sure, that he doesn't demage all notes while going mad.
Suggestion: a toxic member can be deleted, if 2 members in charge delete him from the group.

**Comment by tiltec** [comment]
> a toxic member can be deleted, if 2 members in charge delete him from the group

Sounds reasonable, though to have "members in charge" it needs a concept of admin roles first (#356), with decisions like "who can add an admin" and "who can remove a (toxic) admin" not made yet.

If there's only one admin, the limitation of "2 admins need to accept removal" does not apply. If there's ten admins, it could make sense to require 3 or more approvals. Also, should we take "veto" among admins into account? To avoid adverse effects of "veto", a simple systemic-consensus-based system (like https://ukuvota.world) might be good.

That's a lot to implement and will surely take a while, so we should go for a less complex solution first (one that doesn't solve the concerns in my previous paragraph) that can be improved later on. Maybe it could be good to outline some steps...

**Comment by tiltec** [comment]
Related proposal is here: https://github.com/yunity/karrot-frontend/issues/853

**Comment by tiltec** [comment]
@djahnie received a request from Foodsharing Poland to remove a member. We didn't act on it, but @nicksellen had the idea to found a karrot.world admin group and define a formal process how users could be removed from groups. This could be a good solution for general admin topics and it might be a relief for affected groups before karrot receives a built-in removal feature.

**Comment by tiltec** [comment]
This is being discussed in #853 so closing this as duplicate.
