### ISSUE TITLE
Intuitive editing

### ISSUE THREAD

**Issue by Quasijojo** [yunity/karrot-frontend#802]
Buttons are not consistently recognizable in the design and by that making it very unintuitive> longer time spend navigating the site or even leaving frustrated for first time visitors. 

Example:
The editing for the group has a pencil icon as button while the "check and manage pickups " does not have that icon but instead flashes green when i hover over it....but is apart from that not visibly distinguishable from other surfaces that are non clickable.

I would recommend to give all buttons and clickable surfaces a clear design that makes them easy to find...like for example here in github the green buttons.

**Comment by tiltec** [comment]
I made a few changes, mostly to the store page. You can try it out here: https://802-button-highlights--karrot.netlify.com (login with foo@foo.com, password foofoo)

**Comment by djahnie** [comment]
I like it! Although I'm not so sure about the clock icon. I think I'd like the calendar icon better here.

**Comment by tiltec** [comment]
@Quasijojo 
Have a look in #807 - what do you think of it?
