### ISSUE TITLE
Upgrade to fontawesome 5

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#820]
[Quasar Extras](https://github.com/quasarframework/quasar-extras#readme) was upgraded to Fontawesome 5, which is a complete overhaul of FA4 which we currently use.

Some icons were renamed: https://fontawesome.com/how-to-use/upgrading-from-4
I think also the style changed a bit.

Do we want to do this upgrade?

Alternatively, we could install FA4 as additional dependency and not use the one bundled with Quasar Extras.

**Comment by tiltec** [comment]
I think we should try to do the upgrade to FA5 and see how it looks.

Steps:
- (optional) add the "[version 4 shim](https://fontawesome.com/how-to-use/upgrading-from-4)" and submit a pull request containing a few representative screenshots to give other contributors the chance for feedback. Probably need to temporarily disable the `import 'quasar-extras/fontawesome'` line in `main.js`.
- upgrade the package `quasar-extras` to the newest version
- rename usages of font-awesome (new prefixes, sometimes changed name): https://fontawesome.com/how-to-use/upgrading-from-4

**Comment by Anjalizi** [comment]
I would like to take up this task.

**Comment by agarwalpooja** [comment]
hey.. @tiltec I am working in this issue. I have downloaded the files for font awesome 5 and have given its link in index.html.And i have changed the prefix and icon name as per FA5.
But now the icons are removed from the page.

**Comment by anishaagrawal** [comment]
hey.. @tiltec i am working on this issue. I have downloaded the files for font awesome 5. And i have given the link for font awesome files in index.html .I havereplaced the old prefixes and icons name with the new one.
But now the icons are removed from the page.!!!! can u help me to resolve this.

**Comment by tiltec** [comment]
Hi @anishaagrawal, can you open a `WIP` pull request containing your changes? Then I can have a closer look!

**Comment by anishaagrawal** [comment]
i have pulled the files changed for upgrading to font awesome 5.... please check it.

**Comment by ananya-agrawal** [comment]
since there has been inactivity in this issue for some time, I want to give it a shot
