### ISSUE TITLE
Random Art in pickup manage looks not the same

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#824]
![image](https://user-images.githubusercontent.com/4410802/34523069-1f7a55dc-f096-11e7-977d-574e517838cf.png)

Could you have a look at this @D0nPiano ?
I think it should look exactly the same, or be removed to reduce confusion.

**Comment by D0nPiano** [comment]
This was actually on purpose, to create some sort of parallax effect, but you are actually right. Just removed it in #822
