### ISSUE TITLE
Mobile: No option to create store

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#826]
There is no option in the mobile UI to create a new store.
Nobody except me complained about it so far and I also just wanted to do it to test something, but still... I guess it's not a good idea to have super big differences between the functionality of the desktop and the mobile version.

I would have expected to find a create button in the store list or in a dynamically adapted three-bars-menu (top left). The next spot I looked for it was the group page, but finding it there would have already annoyed me... 😉

**Comment by Anjalizi** [comment]
Can you give some more insight into this issue please so that I can start working on it?

**Comment by tiltec** [comment]
In the desktop view, there's this "plus" button to create a new store:

![image](https://user-images.githubusercontent.com/4410802/36344293-60c78e1a-1418-11e8-8f7a-6b015c4e9373.png)

It's not possible in the mobile UI yet. @djahnie's proposal is to add it to the store list:

![image](https://user-images.githubusercontent.com/4410802/36344364-9497bd9a-1419-11e8-8eef-0e7067e21fe7.png)

You can use your browser to simulate the mobile view, for example https://developer.mozilla.org/en-US/docs/Tools/Responsive_Design_Mode
