### ISSUE TITLE
Display a foodsharing logo somewhere?

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#831]
I realized that many of the people, who contact us come via foodsharing.de. They expect something foodsharing.de-related and would feel way more at ease if they could clearly see that there's a close connection. Even if I keep telling them that this connection exists, we never display it openly.

Through this g0v thing I thought about the possibility to similarly display a foodsharing logo in the footor of karrot. Just the fork. And with some kind of explanatory writing like 'Inspired by' or 'Bringing X worldwide'. Something like that.

This would probably also ease the confusion we could come across when recruiting new people for foodsharing in Wurzen but then leading them to a different page. Here a more obvious connection between the two projects would be really beneficial. :)

**Comment by tiltec** [comment]
This is primarily about karrot.world I guess? Not the software itself, which would affect all people who (will) self-host. I guess we could add a customization option #676 where people can change footer text.

**Comment by djahnie** [comment]
Yes true, karrot.world is what I'm talking about and not the software itself.
If there was an easy to use customization option I'd totally do it myself! ^^

**Comment by tiltec** [comment]
Hm, it probably will be some server-side setting. Although we could think of using the Django admin interface for site admin tasks. For this we would need to make some users into superusers that have read-write access to all the data..

**Comment by D0nPiano** [comment]
I think it's a very good idea to include the logo somewhere.

I would suggest adding a file in `src/themes/` for karrot.world (like `app.karrot.styl`) and add it via css / app variables. The file could be included/excluded in the build process then as far as I understood how the theming works.

**Comment by tiltec** [comment]
> I would suggest adding a file in src/themes/ for karrot.world (like app.karrot.styl) and add it via css / app variables. The file could be included/excluded in the build process then as far as I understood how the theming works.

This seems a bad idea to me because then other sites will have to maintain a fork of our git repo with their custom images in it and run their own build process.

I think the workflow should rather be like this: get bundle from https://github.com/yunity/karrot-frontend/releases, copy to server, done!
The customizations should either happen in the backend and served via API, or be defined in a file `site.json` that gets loaded from the server (similar to `about.json`). This makes it much easier to ship code updates.

**Comment by djahnie** [comment]
So... can we decide on something and then maybe even hand this task to a Rails Girl..? :wink:

**Comment by tiltec** [comment]
I would propose the `site.json` file. It could look like this:

```
{ "siteLogo": "https://karrot.world/site/logo.png" }
```

The frontend implementation will try to load `site.json` and if it finds the `siteLogo` property, it will add the logo in a defined location, with a defined size.

**Comment by tiltec** [comment]
I'll wait a few days for feedback from @nicksellen and @D0nPiano until I make this a starter task.

**Comment by tiltec** [comment]
I think this topic is mostly covered by #676 and will close this issue because it's not actively being worked on.
