### ISSUE TITLE
Add one-to-one conversations

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#832]
It seems quite common for user to expect one-to-one communication. While we haven't got much feedback on the group conversations so far, I already received the request to add one-to-one conversations (from @djahnie and Björn).

So I'll open this issue to discuss the request for a _minimal one-to-one conversations feature_.

My proposal would be:
- use as much code as possible from the existing group conversations
- keep user interface simple, namely:
- support newlines on enter
- send on button click or ctrl+enter
- linkification for URLs
- input on bottom, most-recent-on-bottom (slack/telegram style)
- no editing of messages
- no formatting capabilities (markdown rendering is slow)

**Comment by D0nPiano** [comment]
Sounds Great! Is this ready to be implemented backend-wise / is it already useful to start with the frontend UI?

**Comment by tiltec** [comment]
I think it's useful to start this from a user/frontend perspective, the backend implementation can follow up later.

But some things seem quite certain already:
- data format will be the same as for group conversations https://dev.karrot.world/docs/#!/conversations/conversations_list
- each one-to-one conversation will get a conversation id, messages can be retrieved from https://dev.karrot.world/docs/#!/messages/messages_list

Open issues:
- I guess we'll need to add a `type` field to conversations to filter one-to-one conversations from group conversations
- We need a way to start a conversation, by default there is no conversation between any user
- Notifications!? #257

**Comment by djahnie** [comment]
In the call I had today with Unai from Bilbao this was immediately requested, when I asked him for quick feedback from the top of his head.

**Comment by tiltec** [comment]
I thought a bit about the backend implementation yesterday.

About **initializing a conversation**: if we had an API like this

`GET /api/user/{id}/conversation/`

then we would need to create the conversation on first access. That seems a bit unexpected, as GET requests shouldn't modify the database.

We could make it more explicit and say that `GET /api/user/{id}/conversation/` can return HTTP 404. Then the frontend would need to call `POST /api/user/{id}/conversation/` in order to create the conversation. I don't know what would happen if the POST request gets called a second time - would it throw an error or just return the conversation?

About **differentiating one-to-one conversations from other conversations**: it seems to me that one-to-one conversations shouldn't have a `target`, as they would need two targets and this would duplicate the `participants` field.
Instead, I would use the `participants` field to identify the conversation. To find out if it's really an one-to-one conversation (or a group with just two members), we will need to add a `type` field to the conversation.

**Comment by tiltec** [comment]
From foodsharing Poland

> what do you think about private messages? it could work like on pinterest or linkedin... now we still need to use facebook for communication
