### ISSUE TITLE
Resend invitation email (assigned)

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#837]
I want to add Maxi to foodsharing Wurzen. I sent her an invitation months ago, but she said she never received it.

I'd like to have a possibility to resend the invitation email. E.g with a pop-up that warns me that an invitation was already sent to this address, but still offers me to do it again.

**Comment by djahnie** [comment]
LOL after putting _great_ emphasis on the fact that she'd never have overlooked a mail, an hour ago Maxi joined foodsharing Wurzen...^^
So the personally perceived immediate urgency of this issue is gone for me now... 😉

**Comment by tiltec** [comment]
Doesn't the invite expire after a while? Then it can be send again. But I'm not completely sure, need to check in the backend.

**Comment by tiltec** [comment]
Yes, can confirm: invitations expire after 14 days and get removed from the server. Sending again is possible then.

(There might be a chance that the invitations gets not removed from the server because the removal is only triggered when somebody else sends an invitation.)

I guess it would still be sensible to allow sending invitations again a bit earlier. Will leave this as a feature request.

**Comment by djahnie** [comment]
Erm okay, that is really strange then... I definitely sent this invitation longer ago than 14 days. And when I tried to do it again I directly got the error message. Could it be that karrot sent the mail anyways, or that I double-clicked and that was enough? Cause otherwise I really don't understand what happened here... 😅

**Comment by tiltec** [comment]
Yes, indeed you sent out the mail some days ago. Probably the earlier invitation was expired and it was possible to send the invitation again. It seems like a frontend bug.

**Comment by tiltec** [comment]
I guess that could be a starter task: implement frontend and backend parts to allow for (limited) resending of invitation emails.

I would imagine to allow resending 1 hour after the invitation has been sent.

**Comment by mvellasco** [comment]
Can I start working on it?

**Comment by tiltec** [comment]
Hi @mvellasco, welcome! Yes, this seems a good task to get started with.
If you have any questions, you can ask them here or in our Slack channel (see Readme file)

**Comment by mvellasco** [comment]
Hello @tiltec, thank you for the welcome! I'm just wrapping up the code, and I'll submit a PR on the next day or so.
