### ISSUE TITLE
Feedback does not update properly

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#838]
I just saw the feedback for the first time and thus I could give feedback for multiple pickups. When clicking the info that '4 pickups await feedback' karrot automatically directed me to the first. I entered the information and went back to the wall to click the info again and give more feedback. But it still said that _4_ pickups await feedback and directed me to the one I already gave feedback for.
When reloading the page on the feedback form, another one (the next one?) was displayed. I entered the info again, saved, went back to the wall, clicked the info (which now said that '3 pickups await feedback') and the same thing as before happened: No automatic update.

**Comment by tiltec** [comment]
Thanks, I probably forgot to remove the pickup from the feedback possible list.
