### ISSUE TITLE
Send out weekly summary e-mail

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#847]
As discussed today with @D0nPiano and @brunomc, it would be good for Karrot groups to keep their users up-to-date, with the idea of getting inactive members back.

We came up with the idea of sending out a weekly email, maybe with the following content:
- unread conversations of last week
- done pickups of last week
- upcoming pickups next week

The user should be able to disable this summary e-mail (or change it to daily/monthly?).
The e-mail should have an unsubscribe link at the bottom.
When we introduce the feature, we should maybe offer opt-in? (as in: send out a first e-mail asking if they want to get regular updates)

It could be nice to sign up for pickups directly from the e-mail.
It could be nice to send out HTML e-mail (but also send out text fallback).

**Comment by brnsolikyl** [comment]
Great, I like it!

- Maybe we should also include missed pickups?

- And on done pickups, should we include number of slots (if any) that were not filled by anyone? Or the number of pickups who had at least one vacancy on their slots, in which case the message would be something like "Help was needed on X pickups"

**Comment by djahnie** [comment]
Another nice and kinda gamified feature would be highscores:
- Who participated in the highest number of pickups?
- Who picked up the biggest amounts?

But maybe a week is to short to have this in a way this makes sense. And also I wouldn't wanna give any incentive to people who exaggerate the saved amounts...

**Comment by tiltec** [comment]
Nice ideas! I'll try to identify the *minimum requirements*:

- everyone should be able receive the e-mail in their favourite language (if a translation has been done, otherwise fall back to English)
- unsubscribe link at the bottom of the e-mail
- option to subscribe again (needs something like a _personal group settings_ page)
- content as text-only: unread conversations of last week & upcoming pickups next week 

Optional:
- send out the first e-mail asking if they want to get regular updates in future
- content: done pickups last week
- content: missed pickups last week
- user can switch to daily or monthly frequency
- send out HTML e-mails

Needs discussion:
- content: highlight done pickups where slots have been free, with a message "Help needed"
- content: total amount of food picked up last week
- content: who did most pickups?
- content: who picked up the biggest amount

**Comment by djahnie** [comment]
Since @tiltec and me had a talk about this again yesterday I'll just write down some ideas:

- The subscribe/unsubscribe option needs to be available for every group a user belongs to. I imagine it being accessible in the personal settings. Just one line per group where a simple radio button determines if the mail should be sent out or not. The text could say 'Do you want to receive a weekly summary mail for <group>?', default being 'yes' of course.

**Comment by nicksellen** [comment]
I'll start working on this now.
