### ISSUE TITLE
"Mail unverified" notice only disappears after page refresh

### ISSUE THREAD

**Issue by mr-kojo** [yunity/karrot-frontend#851]
If I change my e-mail address, open the e-mail verification link and then go to the _Settings_ page, I still see the warning that my new e-mail address has not been verified yet. Only after refreshing the page the warning disappears.

Apparently, a cached user object is used when the _Settings_ page is shown because the frontend only calls the backend on page refresh.

I observed this bug on Firefox and Chrome, both with the release and the dev version of karrot.

**Comment by nupurbaghel** [comment]
I tried replicating this bug, but as soon as I switch page from the 'your mail was verified page' to 'settings' page, the warning disappears. It doesn't create a cache for me I believe.
@mr-kojo Is this still the same for you? 
I tested on Version 63.0.3239.132 of Chrome.

**Comment by nupurbaghel** [comment]
Okay i think it was because I had not verified my previous email and I was trying to change it back to my verified email. It was working well in this case.

**Comment by mr-kojo** [comment]
Have you finally been able to replicate it?

**Comment by nupurbaghel** [comment]
Yes, I replicated it successfully.

**Comment by tiltec** [comment]
@nupurbaghel How is your work going?

**Comment by nupurbaghel** [comment]
Sorry, I got busy with my exams. You can assign it to someone else for the time being😅

**Comment by mr-kojo** [comment]
No longer reproducible :)
