### ISSUE TITLE
On verifying new e-mail address, the old address is shown

### ISSUE THREAD

**Issue by mr-kojo** [yunity/karrot-frontend#852]
If I change my e-mail address from `a@b.cd` to `b@c.de` and open the e-mail verification link, the page says:

> a@b.cd
> Your e-mail address was successfully verified!

It would be better if it showed

> b@c.de
> Your e-mail address was successfully verified!

I observed this on Firefox and Chrome, both with the release and the dev version of karrot.

**Comment by paavininanda** [comment]
Hi i would like to work on this issue.
