### ISSUE TITLE
Fix image serving for cordova app

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#857]
Some images are rendering with the full domain e.g. `https://dev.karrot.world/media/__sized__/user__photos/photo_tytYiOv-3227be82cdb6ab52127c1936654cb57a.jpeg` - this is good, and how it should be.

Other images are broken as they are missing the full domain e.g. `/media/__sized__/user__photos/photo_07qXsXD-3227be82cdb6ab52127c1936654cb57a.jpeg`

Not sure why the difference right now.

**Comment by tiltec** [comment]
Oh, that's my fault. I added some code to the frontend to strip the domain because it made some problems while developing locally (especially when proxying to dev.karrot.world). Maybe we should switch it off in deploment.

**Comment by nicksellen** [comment]
You could just enable it under cordova. There is a global variable in the webpack config that you can check.

**Comment by nicksellen** [comment]
> Oh, that's my fault. I added some code to the frontend to strip the domain because it made some problems while developing locally (especially when proxying to dev.karrot.world). Maybe we should switch it off in deploment.

It's also because the websocket sends the image urls back without the domain, so even if it didn't strip it, it still wouldn't work for the logged in user. Other users aren't affected by either of those things and their profile images still show.

So, we should make the backend consistent, either including the domain or not. I would be inclined to keep the domain in the URL (as potentially the images get served by another domain at some point, and that's something for the backend to know about). That would require modifying the websocket part.

What was the problem with local development specifically? I would be inclined then to solve that independently of anything else.

**Comment by nicksellen** [comment]
I made it include domain via the socket in the backend https://github.com/yunity/karrot-backend/pull/476

**Comment by tiltec** [comment]
I guess it should be fixed, but I couldn't try it out yet because https://dev.karrot.world/app.apk seems to be an invalid apk.
