### ISSUE TITLE
[Settings page] Disable "save photo" button if photo wasn't changed

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#860]
![image](https://user-images.githubusercontent.com/4410802/35777825-de6d7604-09b4-11e8-8be0-a47e59c51d76.png)

This button should only be enabled if the photo was changed, to aid the user.

**Comment by LyraXaph** [comment]
I would like to work on this.

**Comment by tiltec** [comment]
I had a look at it before, my problem back then was that [vue-croppa's hasImage()](https://github.com/zhanziyang/vue-croppa#hasimage) wasn't reactive. Looking forward to your solution! 👍
