### ISSUE TITLE
Make fullscreen map available for desktop

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#861]
The fullscreen map is currently only available to mobile users, by clicking on the bottom nav "Map" button: 

![image](https://user-images.githubusercontent.com/4410802/35777892-14e7bfcc-09b6-11e8-92cd-9f161006dce3.png)

https://dev.karrot.world/#/group/6/map (link only works if you joined the _01_testgroup_with_maps_and_password_ before)

Tasks:

- add links to the fullscreen map on desktop view, too
- make the fullscreen map look nice on all screen sizes
- (optional) make sure that the user ends up in the same map view when using browser back navigation
- (optional) sync the current zoom level and position to the URL, so that copy/paste-ing the URL puts the user into the same map view

**Comment by LyraXaph** [comment]
I would like to try this.
