### ISSUE TITLE
Enable Ctrl+Enter as "submit" action in all form textareas

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#862]
User experience improvement for power users: be able to fill & submit forms with keyboard only. One step towards this is to enable "enter to submit" in input fields and "ctrl+enter to submit" in textareas.

An example of this is: 

https://github.com/yunity/karrot-frontend/blob/21f14ad5f5dba0c70012039995bc274dece566aa/src/components/Conversation/ConversationCompose.vue#L15-L23

Steps:
- Identify other forms that contain textareas
- Add "ctrl+enter" as submit action
- support "right Ctrl" key in addition to "left Ctrl" key (probably needs additional key code shortcuts: https://vuejs.org/v2/api/#keyCodes )

**Comment by Divya063** [comment]
@tiltec I would like to work on this

**Comment by tiltec** [comment]
Great @Divya063 !

**Comment by simran-pandey** [comment]
@tiltec Can I take up this issue?

**Comment by tiltec** [comment]
There's a work-in-progress pull request in #879, so I recommend to start with another issue. If #879 is not being worked on the next days, feel free to take over the issue.

**Comment by tiltec** [comment]
Thanks for the notice @anishaagrawal - I merged the issue a while ago, but forgot to close this issue: https://github.com/yunity/karrot-frontend/pull/879

A little hint: if you write "Closes #862" into your Pull Request description, the issue will get closed automatically when merged. Makes things a little bit easier for maintainers :)
