### ISSUE TITLE
Add map to mobile store page

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#863]
To show the location of a store to the user. This is already solved in desktop view by zooming in the sidebar map, but the sidebar map doesn't exist in mobile.

@D0nPiano had the idea to add a small map to the store, similar to what's shown in the profile view:

![image](https://user-images.githubusercontent.com/4410802/35778147-5775ea68-09ba-11e8-9e2f-b58be306d2c6.png)

I would add it next to the description in the main store view, and only in mobile.

![image](https://user-images.githubusercontent.com/4410802/35778161-a920757c-09ba-11e8-8a24-0351e08dc3e4.png)

**Comment by mathewdbutton** [comment]
Hi there, 

I'm new to contributing to open source. Can I pick this issue up?

**Comment by djahnie** [comment]
Great @matthewdbutton, go for it! If you need more help you can join our [team chat on Slack](https://slackin.yunity.org) and ask in #karrot-dev.
