### ISSUE TITLE
Make search show info box if no results were found

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#864]
The topbar search doesn't show any information when no results were found. It would be nicer to show a message "No results found.".

![image](https://user-images.githubusercontent.com/4410802/35778455-c6cd4f56-09be-11e8-8dc2-1e9a8c7ed8e5.png)

Refs #817

**Comment by kallepallimounikasmitha** [comment]
I want to work on this.

**Comment by tiltec** [comment]
Great!

**Comment by tiltec** [comment]
@kallepallimounikasmitha How is your work going?

**Comment by varsha6319** [comment]
I have solved this issue, can I send the pull request

**Comment by tiltec** [comment]
@varsha6319 Yes please :)
