### ISSUE TITLE
Add user photos to search results

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#865]
It would be nice to show user photos in the search results instead of the icon. Makes it easier to identify users.

![image](https://user-images.githubusercontent.com/4410802/35778489-121c7932-09bf-11e8-9047-36a7348a97b6.png)

Refs #817

**Comment by tiltec** [comment]
Yes @SiddharthaSarma, please go ahead :)

**Comment by SiddharthaSarma** [comment]
Thanks @tiltec  :)

Do you want me to show the default user icon if the user doesn't have any image?

**Comment by tiltec** [comment]
I think users would expect to see the same thing in search as the `ProfilePicture` component shows. Makes it nice and uniform.

Therefore, I would add the user random art, the initials and not have the picture rounded.

**Comment by SiddharthaSarma** [comment]
Okay @tiltec 
But when I went through the documentation of quasar autocomplete component.
I found there is no option to add the custom HTML.
As Random art gives the svg image, I found there is no way to link to autocomplete.
For reference please check the properties section of autocomplete
http://quasar-framework.org/components/autocomplete.html#Using-Static-Data

If you know any other ways of doing it, could you please tell me?

**Comment by tiltec** [comment]
Ah, that could be the reason why we didn't add it yet. Would it be hard to replace the autocomplete component with a custom setup, e.g. a input box as search and a popover with list items as result?

**Comment by SiddharthaSarma** [comment]
I will try it

**Comment by varsha6319** [comment]
Hey tiltec
Do you want to have the user photo in a square shape, Can I work towards it?

**Comment by tiltec** [comment]
Hi @varsha6319 yes please. I think this feature is much quicker to solve than #672.

It would be good it would use the existing `ProfilePicture` component, so that the look is unified.

**Comment by harsha4444** [comment]
Hi @tiltec  . Can i work on it

**Comment by tiltec** [comment]
Sure @harsha4444 !

**Comment by agatatalita** [comment]
Hi @harsha4444  did you make any progress with this?

**Comment by tiltec** [comment]
I really want to have this myself, I use the search quite a lot :)

**Comment by tiltec** [comment]
Done as part of the Quasar v1 upgrade.
