### ISSUE TITLE
Upcoming pickups box is merging with the navigation bar when scrolled

### ISSUE THREAD

**Issue by kallepallimounikasmitha** [yunity/karrot-frontend#866]
![screen shot 2018-02-06 at 5 24 09 pm](https://user-images.githubusercontent.com/21152843/35858508-b5ba3dbe-0b62-11e8-9286-3a319976be7b.png) Chechout the above link you can find a screenshot in which upcoming box was coinciding with navigation bar. Sorry if I am wrong.

**Comment by djahnie** [comment]
I can't reproduce this bug. As your browser says 'localhost', I guess you did not actually encounter this behaviour on karrot.world or dev.karrot.world?

**Comment by kallepallimounikasmitha** [comment]
Yeah you are right, thankyou. Closing the issue.

**Comment by tiltec** [comment]
It seems like you are using Safari, right? Currently, karrot is not well-tested on Safari, so I would be happy about feedback (best with screenshots).

I would start to mark these issues with a `Safari` and a `Starter Task` label, so new contributors that also use Safari can fix these kinds of bugs.
