### ISSUE TITLE
Wrong pickup list order in Chrome

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#873]
It should be sorted by date, ascending order. It works in Firefox, but not in Chrome. It also affects our mobile app:

![image](https://user-images.githubusercontent.com/4410802/36027869-415786ec-0d9d-11e8-9176-20b3c8d6e004.png)

Investigate how this happens and explore ways to fix it.

**Comment by tiltec** [comment]
Great! :)

**Comment by shreya99oak** [comment]
I would like to work on it too :)

**Comment by tiltec** [comment]
How is your progress on this issue? @lilliekhogg @shreya99oak

**Comment by nicksellen** [comment]
@searchingfor it would be worth installing the vue dev tools [1] if you haven't already, it's has a nice component inspector that lets you see exactly which vue components are rendered on the page. I added a screenshot of it below (in firefox). See if that helps!

[1] https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd

![vuejsdevtool](https://user-images.githubusercontent.com/31616/36394399-6e364c92-15b4-11e8-8901-b0f988a3d973.png)

**Comment by searchingfor** [comment]
@nicksellen Ah thanks. I see how it works now.

**Comment by searchingfor** [comment]
@tiltec @nicksellen One last question, where are you storing the test data for the group pickups? I've checked all over the files, is the front end getting it from a remote location?

**Comment by nicksellen** [comment]
@searchingfor by default the frontend connects to our dev backend at https://dev.karrot.world/ - so if you're doing frontend-only development everything should just work out the box.

Optionally you can configure a local backend and add a `.env` entry to use it (has some notes in the readme about it).
