### ISSUE TITLE
Add project to quasar site

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#874]
https://github.com/quasarframework/quasar-awesome#projects-using-quasar

**Comment by agarwalpooja** [comment]
Hi @nicksellen, I would like to work on this issue and add project to quasar site.

**Comment by agarwalpooja** [comment]
I have solved the issue, and applied for pull request:  https://github.com/quasarframework/quasar-awesome/pull/9

**Comment by D0nPiano** [comment]
Thank you @agarwalpooja !
