### ISSUE TITLE
Add filtering option for groupPreview

### ISSUE THREAD

**Issue by D0nPiano** [yunity/karrot-frontend#877]
When you are logged out, there is no way of filtering all groups on karrot. My proposal would be adding a search bar underneath `groupPreview`'s "Which group do you want to join?" headline for when you are logged out.

**Comment by tiltec** [comment]
I would like a location filter, perhaps we can get an approximate location of the user (GeoIP and/or browser location API) and show groups close to the user first.

**Comment by tiltec** [comment]
> When you are logged out, there is no way of filtering all groups on karrot. My proposal would be adding a search bar underneath groupPreview's "Which group do you want to join?" headline for when you are logged out.

seems implemented in master, will close.
