### ISSUE TITLE
Localisation of https://karrot.world in Gujarati (Indian regional)

### ISSUE THREAD

**Issue by Hardiki** [yunity/karrot-frontend#883]
The https://karrot.world/ is not available in Gujarati (Indian regional) language.

**Comment by YS4100** [comment]
Hardiki and I will be working on this issue.

**Comment by Hardiki** [comment]
@tiltec can you please enable Gujarati on Transifex.

**Comment by tiltec** [comment]
@Hardiki @YS4100 Enabled! https://www.transifex.com/yunity-1/karrot/language/gu/

**Comment by Hardiki** [comment]
@tiltec We are done with translation in Gujarati.

**Comment by tiltec** [comment]
Thanks you two, looks great! I uploaded it to https://dev.karrot.world

**Comment by Hardiki** [comment]
Your welcome @tiltec
