### ISSUE TITLE
Try out nullsafe optional chaining thing

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#886]
It's a bit bleeding edge.... https://tc39.github.io/proposal-optional-chaining/

It might be not very supported in some of the tooling, so needs a play around. There is an official babel plugin here ---> https://www.npmjs.com/package/babel-plugin-transform-optional-chaining

**Comment by tiltec** [comment]
I had a look just now and the babel plugin didn't work out of the box and eslint couldn't handle it. I'd try it again when Babel 7 is released...
