### ISSUE TITLE
Add edit button to profile page

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#890]
So far editing one's personal profile is done via accessing 'settings' in the three dot menu in the upper right (desktop view) or the three bar menu in the upper left (mobile view).

It would be much more intuitive to have an edit button directly on the profile page. The green pencil button, like the one we use in the store view, would be the logical choice.

**Comment by NaelaTarannum** [comment]
We would like to give this a try

**Comment by djahnie** [comment]
Great! Go for it! :smile_cat:

**Comment by agarwalpooja** [comment]
Hello @djahnie, I am working on this issue but I am unable to find the green pencil button.Can you give a picture or the font awesome icon name or the exact place where it is used in store view.

**Comment by tiltec** [comment]
@agarwalpooja Try out [Vue Devtools](https://github.com/vuejs/vue-devtools), it's a browser extension that gives you nice overview and insight. I'm sure you can find the button with it :)

![vuejsdevtool](https://user-images.githubusercontent.com/31616/36394399-6e364c92-15b4-11e8-8901-b0f988a3d973.png)

**Comment by agarwalpooja** [comment]
Thank you.

**Comment by agarwalpooja** [comment]
![screenshot from 2018-02-25 12-50-24](https://user-images.githubusercontent.com/30632125/36639119-f5b6615a-1a2a-11e8-8d6c-b913eaf6598e.png)


I have added an edit button which on click is redirecting to settings page. Is this button icon fine or its alignment, color needs to be changed.

**Comment by tiltec** [comment]
Great that you made it work! I guess we can discuss a bit more on the design, could you open a Pull Request for it?

**Comment by agarwalpooja** [comment]
Yup, sure.

On Feb 25, 2018 3:28 PM, "Tilmann Becker" <notifications@github.com> wrote:

Great that you made it work! I guess we can discuss a bit more on the
design, could you open a Pull Request for it?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/yunity/karrot-frontend/issues/890#issuecomment-368296998>,
or mute the thread

**Comment by agarwalpooja** [comment]
![screenshot from 2018-02-26 01-40-14](https://user-images.githubusercontent.com/30632125/36642596-af504d92-1a67-11e8-9f1e-18e1d0543eaf.png)


![screenshot from 2018-02-26 02-09-18](https://user-images.githubusercontent.com/30632125/36642998-1248572e-1a6c-11e8-9e7d-99b196db1664.png)
![screenshot from 2018-02-26 02-11-44](https://user-images.githubusercontent.com/30632125/36642999-124aaef2-1a6c-11e8-977c-972febcea752.png)

I have changed the icon and tried to add it at various positions. Which position is appropriate or the position still needs to be changed.

**Comment by D0nPiano** [comment]
Great! I think I like the second one you posted best, but I would put the button on the left hand side of the map.

![20180225_202506](https://user-images.githubusercontent.com/16825880/36645511-282521be-1a6a-11e8-8962-3933ed7be3af.jpg)

**Comment by agarwalpooja** [comment]
Okay, I will change the position.

**Comment by agarwalpooja** [comment]
![screenshot from 2018-02-26 23-12-20](https://user-images.githubusercontent.com/30632125/36669771-12eccede-1b1c-11e8-884f-05fb541f6992.png)


Is this fine?

**Comment by agarwalpooja** [comment]
![screenshot from 2018-02-26 23-12-20](https://user-images.githubusercontent.com/30632125/36669771-12eccede-1b1c-11e8-884f-05fb541f6992.png)


Is this fine?

**Comment by D0nPiano** [comment]
Looks good to me! Thanks! :slightly_smiling_face:

**Comment by agarwalpooja** [comment]
Welcome

**Comment by agarwalpooja** [comment]
Welcome.
