### ISSUE TITLE
Add image to group

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#891]
Would look great on the group home page if there was a nice image/photo. Could use similar code paths to the user images.

**Comment by AneriMehta** [comment]
Hi, I and my teammate would like to work on this.

**Comment by agarwalpooja** [comment]
Hi @nicksellen, can you specify more clearly about this issue, like whether to add same group image, add image as profile picture or so.

**Comment by tiltec** [comment]
I guess it could look like this (in the group gallery):

![screenshot_2018-02-25_10-49-22](https://user-images.githubusercontent.com/4410802/36640149-ffef1dee-1a19-11e8-9e0e-d9edfffaab04.png)

But of course it shouldn't be the same image for every group, instead each group should be able to specify their own in the group settings. You could use the same cropping tool as for user photos (vue-croppa).
The backend implementation would probably also use code that's similar to user photos.

**Comment by VeggieTeriyaki** [comment]
Hi @tiltec , I think I will try to work on this issue.

**Comment by VeggieTeriyaki** [comment]
I'm currently working on it. Just exploring the backend so I can understand what's going on and then will work on it.

**Comment by nicksellen** [comment]
Great! Feel free to ask us questions in slack, etc...

**Comment by ShreyashAnarase** [comment]
Hi @nicksellen  I'm a first timer and I would like to work on this.

**Comment by tiltec** [comment]
@ShreyashAnarase great! Are you familiar with Django, Django REST Framework or VueJS already?

**Comment by ShreyashAnarase** [comment]
No, but I really want to learn.

**Comment by tiltec** [comment]
I recommend to start with the frontend and use mock images for prototyping.

**Comment by tiltec** [comment]
The backend part of this could be quite similar to the user profile picture implementation. For reference:

Model field: https://github.com/yunity/karrot-backend/blob/baf5c817852b8f5ed4810f6a3c7f29b11a034147/foodsaving/users/models.py#L92-L96
Serialization: https://github.com/yunity/karrot-backend/blob/baf5c817852b8f5ed4810f6a3c7f29b11a034147/foodsaving/userauth/serializers.py#L29-L30

**Comment by cstefanj** [comment]
@tiltec Hi. I got this working locally (thank goodness for docker-compose) with a forked version of the backend. I added the fields to the group model and serializers and got it working (after remembering to do the database migration...) - the API response now include the 'photo_urls' field. I left a comment about it at the bottom [here](https://github.com/cstefanj/karrot-backend/commit/5cf1ce116fd657e7bcf523f19ef261d6d8c5cb29). Any chance you could point me in the right direction what to do next? :D

**Comment by tiltec** [comment]
Great! I left you a comment, seems all good.

The next step would be adding a test. Maybe you can figure it out yourself, based on the tests in the user(-auth) API?

**Comment by cstefanj** [comment]
Great, that's encouraging! :-) I took a stab at the tests but that was a bit trickier. I left a few comments [here](https://github.com/cstefanj/karrot-backend/commit/d27e991beef726428798d679301ddc64f69d182f).

**Comment by cstefanj** [comment]
@tiltec I'm making progress on the tests but have a question [here](https://github.com/cstefanj/karrot-backend/commit/345823510e6657680e4247d28b144b48fbc50ce9).
