### ISSUE TITLE
spanish translation is remaining

### ISSUE THREAD

**Issue by YS4100** [yunity/karrot-frontend#897]
Spanish translation on transifex is remaining in both frontend and backend.

**Comment by YS4100** [comment]
I have completed the spanish translation on transifex ,both frontend and backend

**Comment by djahnie** [comment]
Thank you very much for pushing this! We'll take care of putting it live as soon as possible!

**Comment by tiltec** [comment]
Merged in https://github.com/yunity/karrot-frontend/commit/c3ecfb2c648ccee2f25b6087fe57095af80dcdcb
