### ISSUE TITLE
Get started tutorial for the website

### ISSUE THREAD

**Issue by snehalgupta** [yunity/karrot-frontend#905]
We can create a tutorial that familiarizes the user with the functionality of Karrot. When the user logs in for the first time, a mini-tutorial starts explaining how to get started, how to create groups, how to join groups etc. With the help of this tutorial,the user can tour the website and become more familiar with the features of Karrot. The tutorial can be displayed in form of small cards with next button.@riyasinha and I would really love to work on this feature.

**Comment by djahnie** [comment]
Sounds great! Just yesterday we had a meeting where we also talked about a lack of help inside the karrot app. Having this tutorial would be really nice! :smiley:

**Comment by tiltec** [comment]
Sounds good to me too! I think there is no writeup whatsoever how to use the website yet. If it's of any help, here's my walkthrough for the previous karrot version (when it was still called _foodsaving tool_): https://blog.karrot.world/2017/05/11/walkthrough.html

**Comment by tiltec** [comment]
@snehalgupta Would you like to work on this before RGSoC starts in July?

**Comment by snehalgupta** [comment]
Riya and I would love to work on this. As you told Riya to get started with location filter feature in issue #912 ,we were planning to finish this first.But we are excited to work on this as well. If you want, we can work on both these issues together.
@riyasinha

**Comment by tiltec** [comment]
Ah great! I just wanted to make sure that I understood it correctly. I'm happy if you forget about this issue for now and focus solely on #912 :)

**Comment by snehalgupta** [comment]
Okay, so we"ll continue working on issue #912.

**Comment by tiltec** [comment]
Would be good to have, but we should work on better navigation first.
