### ISSUE TITLE
Dead and test groups are cluttering the group list

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#915]
In the meeting I had yesterday with @nicksellen and @mr-kojo we realized that the least of the groups displayed on karrot.world are actually used. I'd much prefer to hide the groups which are not active (anymore) as a short-term solution and as a long-term solution maybe find a way to automate this and /or offer a button in the group settings to flag a group as inactive. Inactive groups could be displayed in grey or a bit transparent at the end of the group list for example.

To prevent even more test groups popping up it would be reasonable to have one clearly designated to this purpose, as discussed in #914.

To make sure we always have a contact to protected groups it would be beneficial to have a field for public contact information in the group settings, as discussed in #898. This way it would be much easier to find out if a group was forgotten and is dead or if it is maybe just on hiatus or stagnating.

**Comment by nicksellen** [comment]
I would suggest groups get a status field like the stores do. Maybe they start off as "new" or "initial" or something. And can be "active" or "inactive" later.

**Comment by tiltec** [comment]
I'd like an automated solution, but a manual status field seems fine to get started with.

**Comment by nicksellen** [comment]
So, how about we create the status field in the model/db, and we can set ones we know about manually in the db. Then, instead of introducing an option in the group form in the frontend, have a next step to promote a group to "active" status, based on user group activity, and hide the others behind a "See ALL groups" button/link.

**Comment by tiltec** [comment]
I'll add the field!

**Comment by tiltec** [comment]
I'll tackle this as part of #914, not showing inactive groups in the group gallery page by default and ranking them after active groups in the search.
