### ISSUE TITLE
Report aggregate activity data to influxdb and create dashboards

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#923]
Purpose: to see how/whether users are using the features

Information I think would be interesting are:
- joined pickup
- left pickup
- did pickup (at least, had >0 collectors at time of pickup)
- missed pickup (had 0 collectors at time of pickup)
- wrote mesage on group wall
- joined group
- left group
- gave feedback
- visited page associated with group (using new mark_user_activity)
- member count
- active member count (last activity <1 week|day|30day|year ago)
- store count
- new version deployed

Should not be personally identifiable as we are supportive of data privacy, so only include group id as the identifiable information.

Most of them would be sent when the event occurs. Counts would be sent via periodic huey task, once per day would be sufficient I think.

@tiltec are you comfortable/uncomfortable with this amount of data collection?

**Comment by tiltec** [comment]
Seems good, as it would give us quite deep insight what people do on karrot.world. I don't have concerns, as the activity of a single user would most probably not identifiable through this data. Except if a group only has few members, but that seems tolerable, or we could enable activity reporting only when a group has more than 5 members.

This feature should also give us insight in what data we want to show in the website -> #355

**Comment by djembejohn** [comment]
In general this looks good.

I wonder what questions you might envisage answering with these data. Thinking a little about this can be helpful in focussing data collection and revealing something you might be able to do.

Naïvely, I can write some suggestion questions but those closer to the site will have much better ideas...

1. Is the user base growing?
2. Where is the site being used the most?
3. Are current users increasing their usage of the site?
4. Are there different types of users? 
5. Can we say something about differences between people who leave / stay?
6. If someone joins their first pickup - how likely is it that they'll join a second?

**Comment by tiltec** [comment]
Next step would be to create Grafana dashboards, possibly in version control with https://github.com/weaveworks/grafanalib

**Comment by nicksellen** [comment]
I had a play with grafanalib, and https://github.com/grafana/grafonnet-lib, but neither had good support for influxdb, then I started building a nodejs builder (which is well suited to building up json data structures), but then the task was bigger than I felt doing at that time.

**Comment by tiltec** [comment]
Seems mostly done. We could add the dashboard JSON export to karrot-backend git or yuca ansible git from time to time, in order to not lose configuration on bad luck.
