### ISSUE TITLE
Create reusable filters and querysets

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#932]
We have need to have reusable filters now, and after discussing with @NerdyProjects and @tiltec we came up with a tentative plan!

The idea is to:
- add reusable querysets on custom managers (e.g. `UserManager.unverified_or_ignored()`)
- add reusable filters in another place related to the type of queryset you want to filter (e.g. `StoreFilters`, or a filters object inside the model might be nicer, `User.filters.inactive_in_group(1)`?), the usage would be like `User.objects.filter(User.filters.foo())`

The main bit is that the filters are only applicable querysets of that model type. The reusable querysets might be used inside those filters. So 2 levels of reuse.

I propose to deprecate the pattern I recently added --> `group.members_with_notification_types()`

**Comment by tiltec** [comment]
Seems the best option is to use custom querysets, like this:

```py
class ConversationMessageQuerySet(QuerySet):
    def exclude_replies(self):
        return self.filter(Q(thread_id=None) | Q(id=F('thread_id')))

    def annotate_unread_replies_count_for(self, user):
        unread_replies_filter = Q(
            participants__user=user,
        ) & ~Q(thread_messages__id=F('thread_id')  # replies have id != thread_id
               ) & (Q(participants__seen_up_to=None) | Q(thread_messages__id__gt=F('participants__seen_up_to')))
        return self.annotate(
            unread_replies_count=Count('thread_messages', filter=unread_replies_filter, distinct=True)
        )

class ConversationMessage(BaseModel):
    objects = ConversationMessageQuerySet.as_manager()
```

They are chainable and allow for dynamic parameters:

```py
ConversationMessage.objects.exclude_replies().annotate_unread_replies_count_for(self.request.user)
```
