### ISSUE TITLE
Dynamically disable/enable submit buttons 

### ISSUE THREAD

**Issue by mr-kojo** [yunity/karrot-frontend#937]
Buttons used for form submission should be disabled programmatically
- when client-side validation fails, and
- while awaiting the response of the backend.

This applies to the following buttons (feel free to extend the list):

- [x] Change email address
- [ ] Change password

**Comment by tiltec** [comment]
Button should also be disabled if there's nothing to save (if there are no changes made to the form)

**Comment by mr-kojo** [comment]
@chocos10 right, @tiltec has already mentioned that in his comment above ;-)
And I think this is part of client-side validation anyway (which is why I didn't create an extra bullet point for it).

**Comment by chocos10** [comment]
I thought @tiltec  was talking about something else .

**Comment by mr-kojo** [comment]
@chocos10 I requested two changes to your pull request (please see respective comments in the code).
Sorry I couldn't review earlier...
