### ISSUE TITLE
Solve stale data issue

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#940]
The app sometimes contains outdated data because the websockets are disconnected in background. Some ways to resolve it:

- implement pull-down-to-refresh to let the user manually refresh (it should work on every page)
- store last timestamp when data was retrieved from the server and update when timestamp is older than x minutes
- detect event when app comes into foreground and update data then

If possible, keep existing data while updating. It seems to be different from "reloading" where the goal is to explicitly clear out data before (e.g. when reloading pickups after a series has been changed). Not sure it it's possible to "update" all data without reloading.

Maybe this process could be assisted by the backend, but it's largely a frontend task.

**Comment by nicksellen** [comment]
https://stackoverflow.com/a/25583962 describes the Cordova background and foreground events. 

https://github.com/apache/cordova-plugin-network-information/blob/master/README.md (or similar) exposes the network information. We want to make sure we don't request/remove data when it is offline. 

The easiest at that point is just a browser refresh. Although it would clear any form fields that a user has written into that would be annoying.

Maybe each store module should implement a refresh action which means "keep any 'selected' IDs you have, but reload the associated data from the server"

**Comment by tiltec** [comment]
https://github.com/yunity/karrot-frontend/pull/944 is the first step to solving it. It refreshes:

- users
- stores
- pickups
- pickupSeries
- invitations
- history
- groups

Missing are:

- messages
- feedback
- currentGroup (detailed data)
- authUser (detailed data)

I wonder if it still makes sense to add a pull-to-refresh to trigger a complete browser reload. Maybe yes, for unforeseen cases. On the other hand, the user can always close the app and reopen. But that may seem buggy.

**Comment by tiltec** [comment]
From foodsharing Poland:

> i've been using android app for quite some time now and it runs nicely and smoothly, but it's not refreshing, so if i want to see any changes, i have to close the app and then reopen it. maybe it's possible to introduce a refresh button  by swiping from top (like in some apps based on material design)

I wonder if he is using the version that includes #944....

Other than that, I agree that it would be good to implement pull-to-refresh to make it look less buggy.
