### ISSUE TITLE
Improve history layout for pickups with many participants

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#943]
Currently it looks like this:

![image](https://user-images.githubusercontent.com/4410802/37043549-2d5474ca-2161-11e8-8821-5cc68df85ed6.png)

The space usage and alignment could be a bit better

**Comment by pogopaule** [comment]
I'm new to this project, but I'll give this issue a shot.

**Comment by pogopaule** [comment]
@tiltec Could you give me a hint on how to create the 17 members in the pickup? I'm struggling to modify https://github.com/yunity/karrot-backend/blob/master/foodsaving/management/commands/create_sample_data.py to behave that way.

**Comment by pogopaule** [comment]
@tiltec I did not manage to change https://github.com/yunity/karrot-backend/blob/master/foodsaving/management/commands/create_sample_data.py in a way that I get multiple users in a pickup like your screenshot shows. There is always only one user in a past pickup. Could you give me a hint on how to do this?

**Comment by tiltec** [comment]
Hey @pogopaule, I see several ways how you could try it out:

1. use storybook (`yarn storybook`) to show a history entry with many users (`src/components/History/HistoryList.story.js`)
2. modify history getters to show many users (`src/store/modules/history.js` Line 30)
3. use the Django console and the Django ORM to add more users to a history entry (`manage.py shell` and `History.objects.get(id).users.add(user)`)

**Comment by pogopaule** [comment]
@tiltec 
What do you think about displaying the number of users in a pickup if there is more than one user. The names are displayed in a tooltip.
The downside of this approach: you cannot click on a profile picture.
I tried to arrange multiple profile pictures in different ways but none looked acceptable to me...
![screenshot at may 05 14-28-47](https://user-images.githubusercontent.com/576949/39663291-d73a9e04-5070-11e8-82ad-94c5b3721458.png)
So should I continue implementing the solution shown above?

**Comment by tiltec** [comment]
Seems good! Maybe even without the tooltip... the user can still access the names by clicking on the history entry, which shows the history detail view.

**Comment by pogopaule** [comment]
Issue can be closed. Branch was merged https://github.com/yunity/karrot-frontend/pull/1014

**Comment by tiltec** [comment]
Indeed.

You can automate this next time by starting your Pull Request message with the words "Closes #1014".
