### ISSUE TITLE
Remove edit button from other users profile preview.

### ISSUE THREAD

**Issue by chocos10** [yunity/karrot-frontend#945]
Whenever we visit any other profile we find a edit button that should not be there as that redirects to the settings page of the user logged in .

**Comment by chocos10** [comment]
i myself would like to work on it.

**Comment by tiltec** [comment]
@chocos10 sounds good!
How far did you get already? I'm thinking about making a production deployment tomorrow and this would be one of the important bits to fix.

**Comment by chocos10** [comment]
#951 solves this issue :) done with it please review .
