### ISSUE TITLE
Add proper pickups pagination

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-frontend#952]
Update: pagination might be the solution, see https://github.com/yunity/karrot-frontend/issues/952#issuecomment-434743691

---

Sometimes rendering the pickups page seems a bit slow. I used the new [vue performance tool](https://github.com/vue-perf-devtool/vue-perf-devtool) to record when loading that page:

![pickups-performance](https://user-images.githubusercontent.com/31616/37142701-27cf7cee-22b9-11e8-880d-5e24fccbeef1.png)

It shows it taking 745ms to render the `<Pickups>` component with the data I have in my localhost database, and the breakdown of which subcomponents make up that time.

I don't think it's a high priority issue, as maybe groups don't have that many pickups on the page, but something to be aware of, or to investigate if you feel particularly motivated :)

**Comment by tiltec** [comment]
My last profiling showed that `PickupUsers` is especially slow. I would focus on rendering less pickups, ideally only those that the user is looking for. Could add some filters to the pickup list ("this week", "next week")

**Comment by tiltec** [comment]
I guess we should just enable pagination for pickups, then it's less critical.

**Comment by tiltec** [comment]
The group wall needs all upcoming and joined pickups, so this could conflict with smaller page sizes.
We might need to add another filter to the backend that returns only upcoming and joined pickups and only fetch all if the user clicks on the pickups page.
