### ISSUE TITLE
Improve navigation for typical user flows

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#958]
Yesterday at the Gothenburg hackathon presentation I noticed that karrot already has quite a lot navigation elements, with sometimes unclear priorities. It could be good to write down some typical karrot user flows and develop a navigation concept with clearer guidance.

I'd consider this issue as done when we identified 2-3 typical things that most people do on karrot and  streamlined the navigation by raising the visibility of those navigation elements and hiding some of the less important pages.

(sorry, no pictures yet)

Related: Janina conducted our first formal usability test and wrote down some notes about it: https://slack-files.com/T0B6WCFM5-F9M5KMN8G-db8a31ec5d

Related issues:
#683 about a redesigned sidenav bar
#905 about a tutorial for karrot

**Comment by djahnie** [comment]
How do you imagine coming up with typical user flows? I could write up some examples and then ask in the facebook group if that's close to reality or where the differences are if there are any. I just fear that we won't get as detailed answers as we'd hope for... I'll still give it a try, I guess.

Any suggestions what to start with?

**Comment by tiltec** [comment]
As this is being revisited in #1047, I'll close this issue.
