### ISSUE TITLE
Dates should respect group timezone (and not browser timezone)

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#959]
The frontend shows all dates in the timezone of the browser, not in the timezone of the group. This becomes clear when the two differ.
It becomes even more apparent when an offset change happens, e.g. on March 23th when the `Europe/Berlin` timezone switches from UTC+1 to UTC+2. The group timezone is set to `Hong Kong`, which doesn't have Daylight Saving Time:

![image](https://user-images.githubusercontent.com/4410802/37257279-a8e1a27a-2567-11e8-997a-daec7f32b136.png)
![image](https://user-images.githubusercontent.com/4410802/37257288-ccde6c3a-2567-11e8-9d02-573b92faad41.png)

I wonder if there is a proper fix for this. The frontend is technically right, showing the time in the browser timezone. But maybe it's more expected to always show the times in the groups' timezone.

**Comment by nicksellen** [comment]
I looked into this a bit, (some|most) browsers do support some timezone handling, via the [Intl.DateTimeFormat stuff](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat).

This is exposed in vue-i18n by setting `timeZone` on the date time format options, e.g.:

```js
const defaultDateTimeFormat = {
  timeShort: {
    hour: 'numeric',
    minute: 'numeric',
    timeZone: 'America/New_York',
  },
  // ... etc
```

It worked, but does not seem to support dynamic setting as we would need.

There are js libraries that do support timezone handling, but they are either huge (e.g. moment), or look crappy.

date-fns doesn't do timezone stuff yet, but has some support in [the pipeline](https://github.com/date-fns/date-fns/pull/676) (based on `Intl.DateTimeFormat`).

I quite like this idea:
* return date in the API using `.astimezone(group.timezone)` to get values like `2018-03-14T15:30:03.014000-04:00`
* strip the offset in the frontend for display purposes

That way the API is still returning unambiguous proper date time with correct time zone information, specifiying a point in time - and the browser can display what it wants for the benefit of the user.

Another option would be to return a local date time value (e.g. `2018-03-14T15:30:03.014000`) but values without time zone information make me a bit uneasy, and they no longer contain enough information on their own to specify a point in time.

**Comment by tiltec** [comment]
I like the API approach, seems to offer the benefits of group-localized time without the downsides of having naive time.

**Comment by nicksellen** [comment]
A tricky thing is editing. I guess the expectation is that people are editing in their local time, but we need to save it in the group timezone.

In the proposal above the backend would still need to accept valid timezone aware timestamps, so the display would be using "local" timestamps (although the Date objects are not aware of anything but UTC or local timezone, so it's a fudge - the point in time represented by our "presentational" timestamps would be incorrect). It would then need to convert to correct point in time representation before saving.

This is not actually _per pickup_ of course, but per group, so I think to include an offset value (maybe provided in the group serializer), and the frontend can then add/substract hours as needed for the correct display/update. The offset has to come from the API as the offset is only available with proper timezone libraries (it includes considerations of daylight savings, etc).

**Comment by nicksellen** [comment]
Ok, I have a plan!

The backend sends dates like `2018-03-14T15:30:03.014000-04:00` - the frontend keeps a seperate localDate field (which it can calculate by knowlege of it's current timezone and the offset from the string).

For editing we do one of two things:
1. forbid editing if the users timezone is different to the group timezone
2. use a library that knows about all the timezones and can calculate the difference correctly (the lib might be a bit big, but will only be loaded when needed on the edit pages)

Also need to consider what is intuitive for the user - I think if someone is editing pickups from another timezone, they expect everything to just be local times which get converted magically (e.g. someone is in the USA on holidays fiddling with pickup times for Berlin, I think they expect to set 9pm in the UI, and it mean 9pm in Berlin time).
