### ISSUE TITLE
Add possibility to include pictures in pickup feedback

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#963]
Requested by LMR Fürth.

At the moment they are examining the possibilities Karrot offers and may switch to it around Easter. It's not dependent on this and not decided upon.

**Comment by tiltec** [comment]
Cool feature, I like it! Maybe just one picture in the beginning, to see how people adopt it?

**Comment by tiltec** [comment]
Could be tackled as a starter task! :)

**Comment by cstefanj** [comment]
Hi! I'm looking for a starter task to tackle. What skills do I need to be able to contribute to this one?

**Comment by tiltec** [comment]
Hi @cstefanj, welcome! This task needs both frontend and backend changes, so Vue/JS and Django/Python skills would be helpful. (If you prefer to work only in Python or JavaScript land, you might be better off with another task)

**Comment by cstefanj** [comment]
Hi! Ok, then I think I need to keep looking. I would be happy to look at the Python/Django part (although I have used Flask more) but have no clue when it comes to the frontend. Thanks for the quick reply!

**Comment by tiltec** [comment]
Yeah, I like Python more than JavaScript, but it's actually not too bad working with VueJS. 

Anyhow, if you want to work on the backend bits, I could take over the frontend part. https://github.com/yunity/karrot-frontend/issues/891 might be a bit more needed than this issue and has good chunk of backend work as well, so maybe that's something you would like to have a try?

Coming from Flask, the Django & Django REST Framework architecture might feel a bit heavy to you, so I'm happy to answer any questions about where to find parts of the code :)

**Comment by cstefanj** [comment]
With that approach I would be happy to give the backend part of #891 a try. Looking at that thread it looks like several people have already given it a go, not sure if I'm perhaps getting in over my head here since this would be my first contribution .. Do you already have thoughts on the frontend part and what you would need from the backend?

**Comment by tiltec** [comment]
I added some information to the other issue.

About getting over your head: after setting up the backend locally, the hardest work should already be done ;)

**Comment by tiltec** [comment]
Coming back to this issue: it's already possible to reference a picture in pickup feedback because the text is rendered as Markdown, but users would need to figure out the hosting solution by themselves (needs to be on https to fulfill our Content Security Policy).
This is closely related to having pictures in any message on Karrot, so if we decide to implement that, we might add an option to upload pictures and add them into a Markdown field with a single click. Might look into Discourse how they do it.

**Comment by tiltec** [comment]
Sure! My last comment was of general nature, there's no need to implement it in near future.

For more backend tasks, I marked some as "help wanted" here: https://github.com/yunity/karrot-frontend/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3Abackend+label%3Ahelp-wanted
For example, https://github.com/yunity/karrot-frontend/issues/1038 might be straightforward :)

**Comment by tiltec** [comment]
Andrea from Solikyl Gothenburg requested that recently:
> Possibility to upload photos to the pickup feedback

**Comment by tiltec** [comment]
The goal is to give users the possibility to upload one or more pictures when giving feedback. From a backend perspective, there should be API endpoints to upload, change and retrieve pictures. We already have some infrastructure in place to handle picture upload.

The `offers` feature demonstrates it. There's a separate [image model](https://github.com/yunity/karrot-backend/blob/be4fb0c5e871843deaf27af6dcc5806cadd46cf9/karrot/offers/models.py#L42), the [serializer](https://github.com/yunity/karrot-backend/blob/master/karrot/offers/serializers.py) has the logic to add, remove and reorder pictures. There's also a special [parser](https://github.com/yunity/karrot-backend/blob/be4fb0c5e871843deaf27af6dcc5806cadd46cf9/karrot/offers/api.py#L30) for handling combined JSON+multipart requests, to allow one request that includes data and pictures. The [tests](https://github.com/yunity/karrot-backend/blob/be4fb0c5e871843deaf27af6dcc5806cadd46cf9/karrot/offers/tests/test_api.py#L48) should make it a bit clearer how the API can be used.

On to [feedback](https://github.com/yunity/karrot-backend/blob/be4fb0c5e871843deaf27af6dcc5806cadd46cf9/karrot/pickups/models.py#L341)! I guess it could be quite similar to offers.

That's so far for the backend. Frontend can be ignored for now.
