### ISSUE TITLE
Add visible absence marker on userpic

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#964]
requested by LMR Fürth.
_At the moment they are examining the possibilities Karrot offers and may switch to it around Easter. It's not dependent on this and not decided upon._

Two options:
- short-term for a specific time of today
- long-term for a specific date range

Both would need different optics, maybe one could be a yellow and the other a red frame around the user pic in all the locations where it's displayed. Very similar to the 'Schlafmütze' feature of foodsharing.de.

**Comment by tiltec** [comment]
What user need would this fulfill?

**Comment by djahnie** [comment]
They did not say, but I guess to know when responsible people are reachable and when not.

**Comment by tiltec** [comment]
Hm, I guess marking the user as inactive after 30 days doesn't help them. I wonder how both features interact if we add this.
Maybe it's really just a visible marker that every user can set themselves and does not come with any other effect (like disabled notifications)?

**Comment by nicksellen** [comment]
The `inactive_at` field (and the correspond `active` field in the API) would seem to be useful for that for me? I know it's not customizable, but it seems a similar purpose no? Alternatively the `lastseen_at` field can be used to check for activity within any time period.

For the short term activity, there is the `lastseen_at` field, or the channel subscription field (which means they actually have an active session).

Without the user need directly I guess it's hard to say.

**Comment by djahnie** [comment]
> Maybe it's really just a visible marker that every user can set themselves and does not come with any other effect (like disabled notifications)?

That's how I imagine it, and probably them, too. Just like the feature on foodsharing.de...
But I don't think this is of great importance to anybody right now actually, they just put it down as nice to have.

**Comment by tiltec** [comment]
As far as I know, LMR Fürth are not using karrot and nobody else requested this feature, so I'll give it some rest :)
