### ISSUE TITLE
Fix user deletion

### ISSUE THREAD

**Issue by mr-kojo** [yunity/karrot-frontend#970]
The account deletion flow is implemented now (#934). However, when testing it manually, I observed several related problems:

1. `foodsaving.users.models.erase()` should set `user.mail` to `None` but it doesn't. Maybe some DB constraints prevent it from being erased. Some unit tests would certainly be a good idea.
2. The profile of a deleted user can still be displayed.
3. The icon of a deleted user is clickable (and redirects to the start page).

After further investigations, we may want to split this issue.

**Comment by tiltec** [comment]
> `foodsaving.users.models.erase()` should set `user.mail` to `None` but it doesn't. Maybe some DB constraints prevent it from being erased. Some unit tests would certainly be a good idea.

`email` is a unique field and as far as I remember it was not possible to set it to `None`. I think we could either remove the constraint or set the email to a random value.

> The profile of a deleted user can still be displayed.

That seems unexpected to me. Doesn't it show the "ooops" message? Does it also happen after you reload the page?

**Comment by mr-kojo** [comment]
1. Fixed (b1a080a)
2. @tiltec you were right, it was a caching issue. After page reload it shows the "oops" page. I didn't think about caching issues because I disabled HTTP caching in the developer console. Apparently, vue.js also has some caching mechanism?
3. Moved to #980

**Comment by tiltec** [comment]
> Apparently, vue.js also has some caching mechanism?

I think the user profile data is still in the `vuex` store. Could be updated via websockets, but it's not of priority because I don't suppose that deletions of active users happen frequently.

**Comment by tiltec** [comment]
A related issue is people that left a group, then the profile is also not accessible. This should be updated via websocket, maybe it already is?

**Comment by mr-kojo** [comment]
@tiltec Okay, can you please open an issue for this?
