### ISSUE TITLE
Improve group sidenav

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#973]
I'm just now writing a new walkthrough and thus have a closer look at Karrot from all angles. I'm now at the chapter 'Navigation', and I guess we all agree that this is not perfect...

So here are some concrete suggestions!

The group sidenav is pretty redundant imho. That's what it looks like rn:
![image](https://user-images.githubusercontent.com/17573771/37613547-936e21ec-2ba8-11e8-8b6b-66a39ac6ddae.png)

How about this:
- Move 'edit group' into the group settings (which so far only hold the email notification settings)
- Remove 'show public group info', since it's already shown in the private description
- Remove 'invite member to group', since it's already accessible on the member page
- Move 'leave group' to the personal profile (only visible on your own profile, e.g. as a collapsible list with an option to directly switch to a different group or leave it - details for this would be a different issue. But moving it makes a lot of sense, since the EfA people did not find the option to leave a group at all...)
- Now we can get rid of the three dot menu! :smiley:

**Comment by ananya-agrawal** [comment]
I want to do this issue.

**Comment by djahnie** [comment]
I'm not sure if this is ready to just be tackled like this - I first would like to get more feedback, e.g. from @nicksellen and @D0nPiano. I'm not even sure @tiltec has said anything so far.

Also, didn't you just grab issue #898 @ananya-agrawal? I didn't see a pull request concerning the public group info thingy. Please don't claim new issues before finishing (or giving up on) the one you already started working on.

**Comment by tiltec** [comment]
@ananya-agrawal From my POV, this topic needs discussion before code changes can start. What do you think about the points that @djahnie proposed?

My comments:

> Remove 'show public group info', since it's already shown in the private description
> Remove 'invite member to group', since it's already accessible on the member page

These options are there for backwards compatibility, but maybe we can remove them by now. Actually I don't know. I don't have a good concept how we can do UI changes gradually, without confusing existing users too much.

Additionally, the "show public group info" functionality in the private description page is a bit inferior, since it can't be linked to (it just toggles the page content). So if we remove the button in the "three dots menu", there's no way to reach the public group info page. I guess we should first modify the button in the private group info page to at least change the URL appropriately, or have both descriptions on the same page below each other.

> Move 'edit group' into the group settings (which so far only hold the email notification settings)

You mean move the button into the group settings page, or the whole group edit form? I think moving the button there could be good, but it comes at the cost of needing two clicks to reach the group edit form.

> Move 'leave group' to the personal profile (only visible on your own profile, e.g. as a collapsible list with an option to directly switch to a different group or leave it - details for this would be a different issue. But moving it makes a lot of sense, since the EfA people did not find the option to leave a group at all...)

I asked the woman from EfA where she expected the "group leave" button, but I didn't receive any answer. I think many other people managed to leave groups so far, so I don't see it as urgent to move the button.
If we move it, I'd probably put it to the group settings page, below the notification options.

The bigger topic of improving navigation could also be discussed in this issue -> #958

**Comment by djahnie** [comment]
> I don't have a good concept how we can do UI changes gradually, without confusing existing users too much.

Me neither... we'd need to collect more data on what people actually use. Or just do what we think is okay and wait for them to complain. (Not the best way to go probably...)
Maybe we can get Sebastian to do some more testing for us? He said he'd be willing to at CiviTechGbg.

> I guess we should first modify the button in the private group info page to at least change the URL appropriately, or have both descriptions on the same page below each other.

If it's not too much effort, I'd prefer the first option.

> You mean move the button into the group settings page, or the whole group edit form? I think moving the button there could be good, but it comes at the cost of needing two clicks to reach the group edit form.

Only the button. It already takes two clicks to reach it, cause you need to click the three dots menu first.

> If we move it [the group leave button], I'd probably put it to the group settings page, below the notification options.

Hm, could be okay. I first wanted to say that it doesn't fit because it's not a global group setting but a personal one, but then again, so are the notification settings, so...
I'm not completely happy with it though, because of that exact reason. I'd actually like to have an extra box on the personal profile with all the personal group settings in it. Where all groups one is a member of are listed below each other - just one line each - and there you have all the options together very concisely. A bit like this:

Solikyl: [ ] Weekly summary   [ ] Pickup notifications   [ ] wall notifications   [Leave group button]

**Comment by ananya-agrawal** [comment]
>I don't have a good concept how we can do UI changes gradually, without confusing existing users too much.

Maybe we can do a 50-50 testing among users by showing 50% of the people one version and the 50% the rest. That way we can maybe track somehow which one functions better.
>Only the button. It already takes two clicks to reach it, cause you need to click the three dots menu first.

I also feel that putting edit button inside settings page is a good idea.
> I'd actually like to have an extra box on the personal profile with all the personal group settings in it. Where all groups one is a member of are listed below each other - just one line each - and there you have all the options together very concisely. A bit like this:
Solikyl: [ ] Weekly summary [ ] Pickup notifications [ ] wall notifications [Leave group button]

I guess it would be better to do this and maybe we should open another issue for this and work on this separately.

**Comment by nicksellen** [comment]
> Maybe we can do a 50-50 testing among users by showing 50% of the people one version and the 50% the rest. That way we can maybe track somehow which one functions better.

This is a good technique for sites with lots of users, I don't think we have anywhere near enough to get any meaningful data at this point. I think we are also quite under-resourced for developing two concepts at once, _and_ implementing A/B testing :)

> I'd actually like to have an extra box on the personal profile with all the personal group settings in it. Where all groups one is a member of are listed below each other - just one line each - and there you have all the options together very concisely

Are most people actually in multiple groups? I think this might be one of those things that affects us more than the actual users.

**Comment by djahnie** [comment]
Tilmann was also already bringing up A/B testing, but I completely agree with Nick, that we simply don't have the resources - neither wrt users, nor developers - to do this in a way that makes sense.

The multiple groups are not a use case that is intended to be frequent as of now, that's true. But I can imagine that changing in the future, e.g. when bigger cities are divided into multiple groups, or when more travellers also use this. (I'm not sure though if I really see this as important arguments or if I'm just looking for reasons why my wish should be granted...^^)

**Comment by tiltec** [comment]
As Nick is revisiting this topic up in #1047 and makes much bigger changes, I'll close this issue.
