### ISSUE TITLE
Rework maps: group map, fullscreen map, gallery map

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#975]
We have three types of map that fulfill different purposes, but could be improved. Here are some issues with the current implementation:

- Fullscreen map (which is the same as mobile map) doesn't have an option to show users and hide stores -> #902
    - When switching from group map to fullscreen map, it's unexpected for the user that the map view and map content changes -> state would need to be synchronized between them
- Group map and fullscreen map could show other groups in some way, e.g. as bubbles. This would bring it closer to the gallery map
- There is no way to find out the location of a store on mobile -> #863 
- At the hackathon in Göteborg, the fullscreen map was sometimes a bit "jumpy" on Chrome. Although the computer was also rather slow, it's good to keep in mind that not all computers are as fast as our dev machines ;)

**Comment by djahnie** [comment]
Feedback from Warsaw:
- Tomasz missed an obvious option for exiting the fullscreen map.
- He also criticized the missing options to show and hide things.
- And that in the mobile version there is no full screen mode at all, and no controls (show/hide users) by default.

**Comment by tiltec** [comment]
The mobile map _is_ the fullscreen map, by the way.
