### ISSUE TITLE
Make it possible to give feedback without entering weight

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#976]
Currently, the feedback form is quite focused on entering the weight:

![image](https://user-images.githubusercontent.com/4410802/37686275-04fe4672-2c97-11e8-9545-abe3c3f28aed.png)

It should be possible to give feedback without weight, because people might not want to estimate the amount. Entering a weight of "0 g" doesn't really fit and will drastically change the statistics.

The backend already supports comment-only feedback.

**Comment by ananya-agrawal** [comment]
should the default be made blank or you are planning something else?

**Comment by tiltec** [comment]
The weight field can be set to `null` or `undefined`, then the backend can differentiate it from being `0`.

**Comment by trmendes** [comment]
@tiltec What is the beckend status on this feature? If I set it to null or undefined will the beckend differ it from 0?

Btw....Is zero a valid weight for a pickup? I mean, If you have a pickup it must have a non zero weight. So if the user leave it as zero it is beacause the user has no idea about the weigth so the backend should take it as null or undefined and not use this for the statistcs, right?

**Comment by tiltec** [comment]
@trmendes 
The backend accepts feedback entries with either `comment` or `weight` set, or both. If `weight` is set, any non-negative value is allowed, also 0. `null` and `undefined` are different from 0.

The rationale is that the `weight` field should be also used for statistics calculation, while the `comment` field is meant for humans only. A weight of 0 can be valid if people went to a food pick-up, but there was no food to save. This seems relevant for statistics calculation.

In the end, we need to check how people use this field and adjust the code accordingly. Right now, a lot of people enter "0" weight because the UI makes it hard to enter no weight. It might be safe to assume that all "0" weight fields up to now are actually meant as "null" by the user...
