### ISSUE TITLE
Add Telegram notifications

### ISSUE THREAD

**Issue by tiltec** [yunity/karrot-frontend#982]
From user feedback we know that many foodsaving groups use Telegram groups as primary communication channel. It would be nice if karrot could send out notifications to Telegram groups. As a start, I would only enable the daily pickup notifications.

The telegram group should be set per karrot group.

**Comment by nicksellen** [comment]
https://github.com/python-telegram-bot/python-telegram-bot seems the libary to use

**Comment by khalilchoudhry** [comment]
@nicksellen hi, do you or anyone else working on this feature?

**Comment by nicksellen** [comment]
So far I just played around with the bot library and we discussed a flow that might make sense.

There would be one bot registered per karrot deployment. Someone would invite the bot into their group and ask it to register a group. It would then give you a code you can copy and paste into the group settings page.

That just gets the registration done. The next part is working out what to send to it. That could be quite tricky. 

I have a work in progress branch on my laptop which I could push at the weekend.

Are you interested to work on it?

**Comment by nicksellen** [comment]
Also this isn't a starter task so you would need to have done experience already before taking it on. What do you think?

**Comment by khalilchoudhry** [comment]
Yes it isn't a starter task but i have been working with facebook chatbots lately with api.ai. I am interested to work on it this weekend. I will share the code with you guys and if it would make any sense, you can accept it or we can modifiy it as per suggestions if it is possible ?

**Comment by tiltec** [comment]
How would you add telegram notifications @khalilchoudhry ? Do you think api.ai would improve this significantly?

**Comment by nicksellen** [comment]
https://github.com/yunity/karrot-backend/tree/telegram-notifications is my branch from ages ago. I can't remember the state of it. Don't expect much.

**Comment by lwm** [comment]
Just floating around the issues now and can't help but think that this could be an interesting candidate for [Matrix open protocol](https://matrix.org/docs/guides/faq#what-is-matrix's-mission%3F) bindings. All groups can use whatever chat application they want (the inevitable 'support X chat application' feature request) to send messages to the Matrix room [using a bridge for their app](https://matrix.org/docs/projects/bridges). That would require some extra infrastructure though (a homeserver for each Karrot instance, I think).

**Comment by tiltec** [comment]
Closing this on the request of @nicksellen - "notifications are hard enough and we should focus on improving our own first"
