### ISSUE TITLE
Annoy people to fill in personal information

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#983]
This is meant to make the karrot group as a whole more interesting, more useful and less anonymous.
The idea, as discussed with @tiltec, was to display some kind of annoying popup that reminds them to give additional information such as:
- uploading a profile picture
- writing some words in the description field
- adding a mobile number (and means of transport as soon as that's possible)

Open questions:
- When should the reminder be displayed? Straight from the beginning or after some time of using a boring profile? If the latter, what is an appropriate time frame?
- How should the reminder be displayed? A popup in the middle? Different toasts popping up from all sides of the screen? ^^
- Where should the reminder be displayed? Directly on the wall? Only when accessing the profile of someone? On every single page switch?
- For what exactly should we push? More/less than what I suggested above?

**Comment by tiltec** [comment]
Maybe not _annoy_ people ;)

**Comment by djahnie** [comment]
I thought that was the exact idea. Do we need to sugarcoat it more..? :wink:

**Comment by chocos10** [comment]
I think whenever user login or visits his own profile page a reminder popup on right bottom of the page should be displayed containing some message like "Would you like to complete your profile ?" or anything else.  @djahnie  @tiltec  your suggestions ?

**Comment by djahnie** [comment]
I think I'd make the phrasing more explicit. Like 'You haven't added a mobile number yet!' and so on. I guess that would make for a huge popup if those phrases were added for description, profile picture and means of transport respectively, but I imagine them also disappearing one by one when the requirements are met.
Since this version would be pretty annoying indeed I think your suggestion to display it only in these two cases (directly after login and when visiting one's own profile), @chocos10, would be sufficient.

I'm not decided on this though. Maybe my proposed phrasing sounds too aggressive now..? :thinking:

**Comment by chocos10** [comment]
@djahnie  ya poking user on every detail will be too much annoying (aggressive :laughing: ) and if popup or any alert appears on every page then also it wont be user friendly according to me.

**Comment by tiltec** [comment]
This could do with some progressing ;)

**Comment by djahnie** [comment]
Not important enough to bug people about this, especially when we want to bug them to give trust to other users at the same time.
