### ISSUE TITLE
Release Android app in Play Store

### ISSUE THREAD

**Issue by djahnie** [yunity/karrot-frontend#984]
As discussed in #674, we should release the karrot Android app in the Google Play Store. An account costs 25$, which we could register as "Foodsaving Worldwide" (to be shared with a potential Foodsharing.de mobile app).
Deployment should be automatically done from CI.

UPDATE (tiltec):

To finish this issue:

- [x] fix known bugs (see sentry)
- [ ] ~advertise app on website~ forum should be enough for now
- [x] disable or remove built-in updater
- [x] improve refresh behavior (e.g. do not delete messages)
- [x] improve fcm push titles (e.g. application messages)
- [x] disable firebase analytics ~(maybe needs better firebase plugin: https://github.com/arnesson/cordova-plugin-firebase)~
- [x] hide browser push setting
- [x] add splash icon (at least a very simple one)
- [x] fix map popup links, they are currently broken
- [x] group description is narrow
- [x] add groupgallery spinner when groups are loading
- [x] https://github.com/yunity/karrot-frontend/issues/949
- [x] current group didn't get saved
- [x] pull-to-refresh on all pages
- [ ] publish app to production track
- [ ] open issue about follow-up tasks
- [x] disable push notifications when conversation is muted
- [x] pickup chat header is missing

**Comment by djahnie** [comment]
We now prepared most things for the release but got this error:
> Your app has an apk with version code 10000 that requests the following permission(s): android.permission.READ_PHONE_STATE. Apps using these permissions in an APK are required to have a privacy policy set.
@nicksellen, do you know what's up with the phone state reading?

**Comment by tiltec** [comment]
We apparently have the developer account now (at least I paid 25$), so it seems worth getting the app released. I'll draft a simple privacy policy in English and then check the next steps.

**Comment by MaximeGTB** [comment]
Hello guys! Great work, thanks to advise us of when we can start testing the app.

**Comment by tiltec** [comment]
Hey @MaximeGTB, you can already test the app here: https://play.google.com/store/apps/details?id=world.karrot 
It says "Unreleased", but it should still work and receive updates!

You can also download the app file here, but you will have to update it manually: https://karrot.world/app.apk

**Comment by tiltec** [comment]
To finish this issue:

- [] advertise app on website
- [] disable or remove built-in updater
- [] improve refresh behavior (e.g. do not delete messages)
- [] improve fcm push titles (e.g. application messages)
- [] disable firebase analytics (maybe needs better firebase plugin: https://github.com/arnesson/cordova-plugin-firebase)
- [] hide browser push setting
- [] add splash icon
- [] publish app to production track
- [] open issue about follow-up tasks

**Comment by MaximeGTB** [comment]
Cool!
