### ISSUE TITLE
Open/Close message below search box should be Show/HIde

### ISSUE THREAD

**Issue by inktrap** [yunity/karrot-frontend#994]
IMHO the Open/Close messages below the search box should be Show/HIde because that is what they do.

**Comment by inktrap** [comment]
Would it be beneficial to look through the whole app at some point for similar improvements, or is this irrelevant for now?

**Comment by tiltec** [comment]
Can you clarify what this is about, e.g. with a screenshot?

> Would it be beneficial to look through the whole app at some point for similar improvements, or is this irrelevant for now?

I think it's important, improving UX is a constant focus for karrot.

**Comment by inktrap** [comment]
![karrot-world-open-close](https://user-images.githubusercontent.com/1449471/38386197-3114434a-3914-11e8-97fc-30751b13d384.png)

Since the result list is part of the same window, it shows/hides that part, the window stays open. That would be opinion.

**Comment by tiltec** [comment]
I think it's reasonable to change it to show/hide and keep representing the action, not the current state.

Maybe the main reason why it's open/close is because we had it already translated: https://github.com/yunity/karrot-frontend/blob/master/src/locales/locale-en.json ;)

**Comment by codebyuma** [comment]
@tiltec would it be ok if I attempted to fix this issue?

**Comment by tiltec** [comment]
@codebyuma please go ahead :)

**Comment by tiltec** [comment]
Ah, I need to clarify that. There's two steps for adding messages:

1. add them to `locale-en.json`
2. upload to transifex

Step 2 should only happen once the changes are merged into `master`, so you don't need care about it now.

**Comment by codebyuma** [comment]
@tiltec awesome - ok I'll likely push up my PR tonight for review 👍

**Comment by codebyuma** [comment]
PR is ready for your review: https://github.com/yunity/karrot-frontend/pull/1003
